### ISSUE TITLE
'render_math' prevents 'summary' from working

### ISSUE THREAD

**Issue by szhorvat** [getpelican/pelican-plugins#1007]
The `summary` plugin makes it possible to customize the length of summaries.  For example, `<!-- PELICAN_END_SUMMARY -->` can be used to mark the end of the summary (instead of using the default length).

The `render_math` plugin allows including math with LaTeX notation.

If there is some math (e.g., `$x$`) before the summary end marker, then the end marker won't work. The default summary length will be used again.

Is there a simple fix for this?

**Comment by avaris** [comment]
This looks like a race condition. Both plugins are activated in the same signal and `render_math` wants to process `summary` and it'll generate the default summary if there is none at that point. So it's basically who runs first.

**Comment by szhorvat** [comment]
Is there any way I can control the order in which they are run?

**Comment by avaris** [comment]
Unfortunately, no. The plugin package pelican uses, `blinker`, doesn't guarantee the order of callbacks.

**Comment by justinmayer** [comment]
@szhorvat: Sorry there's no easy fix for this. If you come up with a workaround, please let us know!
