### ISSUE TITLE
[Assets] {{ ASSET_URL }} contains unnecessary leading slash

### ISSUE THREAD

**Issue by sagamusix** [getpelican/pelican-plugins#1018]
`{{ ASSET_URL }}` contains a leading slash, which is inconsistent with the provided example usage pattern `{{ SITEURL }}/{{ ASSET_URL }}` that can be found in the readme. This turns into `https://example.org//path/to/asset` instead of the expected `https://example.org/path/to/asset`. Either the examples should be updated to not contain a slash between `{{ SITEURL }}` and `{{ ASSET_URL }}`, or `{{ ASSET_URL }}` should not contain a leading slash, which would be more consistent with the rest of Pelican.

**Comment by kdeldycke** [comment]
The legacy `assets` plugin has been moved to a new dedicated repository at: https://github.com/pelican-plugins/webassets .

Please report there if you're still impacted by the issue. In the mean time, I guess this can be closed.

**Comment by sagamusix** [comment]
Ported to https://github.com/pelican-plugins/webassets/issues/3
