### ISSUE TITLE
Can I show first few lines of code in collapsed state using notebook liquid tag?

### ISSUE THREAD

**Issue by benlindsay** [getpelican/pelican-plugins#1019]
The collapsible code functionality with the notebook liquid tag is great! I'm wondering if it's possible to extend it to show the first n lines of code in the collapsed state rather than showing now code. For me it would be nice if someone could more easily see there's code there. I'm not familiar enough with javascript to know how to implement this right away. Any thoughts would be great.

Thanks!

**Comment by justinmayer** [comment]
I have never used the Liquid Tags plugin and thus can't be of much assistance. If someone would like to work on this, PRs are welcome.
