### ISSUE TITLE
bug(permalinks): redirect to non-existent page

### ISSUE THREAD

**Issue by Kristinita** [getpelican/pelican-plugins#1023]
@cscutcher, ping.

### 1. Summary

Files, that generated via permalinks plugin, redirected to non-existent pages.

### 2. Environment

+ Windows 10 Enterprise LTSB 64-bit EN
+ Python 3.6.5
+ Pelican 3.7.1
+ Python Markdown 2.6.11
+ gitpython 2.1.9
+ filetime_from_git 16.4.2018
+ permalinks 16.4.2018

### 3. Configuration

Example configuration on [**`SashaPermalinks2` branch of my demo repository**](https://github.com/Kristinita/KristinitaPelican/tree/SashaPermalinks2).

`content/SashaContent/SashaPermalinks.md`:

```markdown
Title: SashaPermalinks

Sasha Goddess!
```

Part of `pelicanconf.py`:

```python
PLUGIN_PATHS = ['pelican-plugins']
PLUGINS = [
    'filetime_from_git',
    'permalinks',
]

GIT_HISTORY_FOLLOWS_RENAME = True
GIT_GENERATE_PERMALINK = True
GIT_SHA_METADATA = True
GIT_FILETIME_FROM_GIT = True

ARTICLE_PATHS = ['SashaContent']
```

### 4. Steps to reproduce

    pelican content -s pelicanconf.py

`output/permalinks/7-41RBoVSE-2JpSvMPLMUIqIWD8=.html` file generated for me. I open `7-41RBoVSE-2JpSvMPLMUIqIWD8=.html` in browser.

### 5. Expected behavior

Generated file:

```html
<!DOCTYPE HTML>
<html lang="en-US">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="refresh" content="0;url=../sashapermalinks.html">
        <script type="text/javascript">
            window.location.href = "../sashapermalinks.html";
        </script>
        <title>Page Redirection to SashaPermalinks</title>
    </head>
    <body>
        If you are not redirected automatically, follow the
        <a href='../sashapermalinks.html'>link to SashaPermalinks</a>
    </body>
</html>

```

File correct redirect to `../sashapermalinks.html`.

### 6. Actual behavior

[**Generated file**](https://github.com/Kristinita/KristinitaPelican/blob/SashaPermalinks2/output/permalinks/7-41RBoVSE-2JpSvMPLMUIqIWD8%3D.html):

```html

<!DOCTYPE HTML>
<html lang="en-US">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="refresh" content="0;url=b'/sashapermalinks.html'">
        <script type="text/javascript">
            window.location.href = "b'/sashapermalinks.html'"
        </script>
        <title>Page Redirection to SashaPermalinks</title>
    </head>
    <body>
        If you are not redirected automatically, follow the
        <a href='b'/sashapermalinks.html''>link to SashaPermalinks</a>
    </body>
</html>

```

File redirect to `http://localhost:3001/SashaDemoRepositories/SashaPelicanDebugging/output/permalinks/b'/sashapermalinks.html'` page →

> Error response

> Error code: 404

> Message: File not found.

> Error code explanation: 404 - Nothing matches the given URI.

![Error response](https://i.imgur.com/ckFksLH.png)

Thanks.

**Comment by cscutcher** [comment]
Sorry, I fixed this on my personal fork and forgot to merge upstream. PR is up now.

**Comment by panhaoyu** [comment]
Hey, could someone merge this PR?
I met the same problem and this works well.
