### ISSUE TITLE
Assets plugin not working

### ISSUE THREAD

**Issue by gDelgado14** [getpelican/pelican-plugins#1046]
This is probably an error on my part and am looking for assistance more than anything. 

Pelican version: 3.7.1
Python version: 2.7.10

I am trying to pre-process SASS CSS files. Hence I'm using the `assets` plugin (which i assume means that I have to download the webassets + libsass packages).

When I run `make devserver`, the error I get is:

```
TemplateSyntaxError: Encountered unknown tag 'assets'.
```

This error is coming from the following line of code located in `theme/templates/index.html`:

```
{% assets filters="sass", output="css/style.min.css", "css/theme.sass" %}
  <link rel="stylesheet" href="{{ SITEURL }}/{{ ASSET_URL }}">
{% endassets %}
```

The full source code of my blog is located on [Gitlab](https://gitlab.com/gDelgado14/gdelgado14.gitlab.io/tree/custom-theme). Note that I have linked to a temporary / WIP branch called `custom-theme` 

What am I doing wrong here?

**Comment by avaris** [comment]
Your plugin settings are in `publishconf.py` instead of `pelicanconf.py`. `make devserver` uses `pelicanconf.py`, i.e. plugin isn't active.

**Comment by justinmayer** [comment]
@gDelgado14: I hope @avaris was able to assist you with your problem. No need to reach out via Twitter, by the way. Doing so just adds noise to an already heavy volume of notifications.

Also, in the future, please consider reaching out via the Pelican IRC channel, as noted in the [How to Get Help](http://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the documentation. Thanks!
