### ISSUE TITLE
Liquid tags code collapse

### ISSUE THREAD

**Issue by pietromarchesi** [getpelican/pelican-plugins#1047]
I am having trouble getting the `liquid_tags` code collapse to work. 
- I have put `pelicanhtml_3.tpl` in the my `content` folder.
- I have IPython 3 installed 
- I have added `#` and `# <!-- collapse=False -->` in some input cells for testing
- I have built the site with `fab build`

But somehow all input code is rendered normally, and cannot be collapsed. I have also tried doing the same with IPython 1 and 2 and the respective `pelicanthtml` files, but nothing seems to work. Any ideas?

**Comment by justinmayer** [comment]
Hi Pietro. I have never used the Liquid Tags plugin and thus can't be of much assistance. Were you ever able to resolve this issue?

**Comment by pietromarchesi** [comment]
Nope! I have sort of accepted a life of uncollapsed code.

**Comment by kdeldycke** [comment]
The `liquid_tags` plugin has been migrated as a stand-alone plugin at https://github.com/pelican-plugins/liquid-tags . I recommend you to try out that new version as some bugs were fixed and the plugin is actively being worked on over there.

In the mean time I guess we can close this issue.

**Comment by justinmayer** [comment]
@pietromarchesi: Sorry we weren't able to provide more assistance with this issue. Perhaps someone will address it via the new repository mentioned above.

@kdeldycke: Thanks for the nudge!
