### ISSUE TITLE
[tag cloud] Tag cloud emits tag-0 class (bug)

### ISSUE THREAD

**Issue by tofof** [getpelican/pelican-plugins#1058]
### Observed behavior
When min_count is 1, max_count is 6, and steps is the default of 4, the emitted class for the tags of size 6 is 0, not 1.

### Expected behavior
Tag classes range from tag-1 to tag-N, as specified in readme:
> You should then also define CSS styles with appropriate classes (tag-1 to tag-N, where N matches TAG_CLOUD_STEPS)

### Suggested resolution
Change [this formula](https://github.com/getpelican/pelican-plugins/blob/master/tag_cloud/tag_cloud.py#L54) to `round` instead of `math.floor`. This actually has [other useful effects](https://github.com/getpelican/pelican-plugins/issues/1059) in addition to correcting what seems to be a floating point error.

**Comment by justinmayer** [comment]
@tofof: Many thanks for pointing this out, and apologies for the long delay in addressing it.

Fix applied and released in Tag Cloud 1.0.1: https://github.com/pelican-plugins/tag-cloud/releases/tag/1.0.1
