### ISSUE TITLE
org_reader: Errors when loading plugins

### ISSUE THREAD

**Issue by kwpav** [getpelican/pelican-plugins#1061]
There are some errors that are occurring when loading the `org_reader` and `org_python_reader` plugins. This looks to be related to PR #1039.

## org_reader
1. The values in the README for the config names are incorrect, e.g. using `ORG_EMACS_READER_EMACS_LOCATION` as indicated by the instructions, you get the error:
```
  CRITICAL: AssertionError: No ORG_READER_EMACS_LOCATION specified in settings
```

2. When attempting to load the `org_reader` plugin, the following error occurs:
```
  Cannot open load file: No such file or directory, pelican-plugins/org_reader/org_emacs_reader.el
```

Relevant snippet from `pelicanconf.py`:
```
  PLUGINS = ['org_reader']
  ORG_READER_EMACS_LOCATION = '/usr/bin/emacs'
```

This is occurring because the filename in the folder is `org_reader.el`.

## org_python_reader
1. When attempting to load the `org_python_reader` plugin, the following error occurs:
```
  ERROR: Cannot load plugin `org_python_reader`
    | ModuleNotFoundError: No module named 'org_python_reader.org_python_reader'
  WARNING: No valid files found in content.
```

Relevant snippet from `pelicanconf.py`:
```
  PLUGINS = ['org_python_reader']
  ORGMODE = {
          'code_highlight': True,
  }
```

The plugin filename is `org_reader.py` but pelican is looking for `org_python_reader.py`

**Comment by kwpav** [comment]
I am working on a fix for this.

**Comment by justinmayer** [comment]
@jappeace @jorgesumle Any thoughts on this PR? Your input would be helpful. 😄

**Comment by jappeace** [comment]
right so what happened was is that sebastien renamed org_reader to org_emacs_reader and put his own new python implementation in place of the existing one, I undid that because it would surely break backwards compatibility. I may have not caught all renames.

**Comment by jappeace** [comment]
Idk, if it works you got it! Thanks for the help.

**Comment by justinmayer** [comment]
Many thanks to @jappeace for the input and to @kwpav for the fix.
