### ISSUE TITLE
Cannot use plugins on hidden pages? 

### ISSUE THREAD

**Issue by beetleb** [getpelican/pelican-plugins#1068]
I use Pelican for a blog, but occasionally I want to output a page that is relatively private. So I set its status to "hidden" so it won't show up by default. I then pass the link around to whoever I need to send it to.

I recently wrote a page with some math content, and was surprised the render_math plugin was not inserting the relevant MathJax code. Digging in, I discovered it used the all_generators_finalized signal, and that since my page is hidden, the generator does *not* include it. 

What are my options? Can we have a generator for hidden pages/articles?

**Comment by avaris** [comment]
Generator does include your hidden pages. `render_math` forgot to process them. i.e. [This](https://github.com/getpelican/pelican-plugins/blob/master/render_math/math.py#L348) should be:
```python
for page in (generator.pages + 
             generator.hidden_pages 
             # + translations and whatnot
             ):
```

**Comment by beetleb** [comment]
Thanks - I didn't find that in the documentation.
