### ISSUE TITLE
[liquid tags] Unexpected keyword error when rendering notebooks

### ISSUE THREAD

**Issue by jreiberkyle** [getpelican/pelican-plugins#1069]
I am using Python3.6, pelican 3.7.0, and ipython 7.0.1.

When I attempt to render a notebook using liquid tags, I get the following error:
```
ERROR: Could not process ./test_coverage.md
  | TypeError: store() got an unexpected keyword argument 'safe'
```

test_coverage.md
```
Title: A Tutorial
Date: 12/12/2012
Tags: tutorial
Author: Test
Summary: A tutorial

{% notebook calculate_coverage.ipynb %}
```

I have a feeling this issue is due to incompatible dependencies, but I am not sure. Anyone else get this? If not, what version of python, pelican, and ipython do you have?

**Comment by Juanlu001** [comment]
also reported at https://github.com/danielfrg/pelican-ipynb/issues/101 cc @danielfrg

**Comment by manugarri** [comment]
Its a version error. Tried with specific package versions:

```
Markdown==2.6.11
MarkupSafe==1.0
nbconvert==5.4.0
nbformat==4.4.0
notebook==5.7.0
pelican==3.7.1
```

And it works.

**Comment by avaris** [comment]
Markdown 3.0+ [removed](https://github.com/Python-Markdown/markdown/commit/7f63b20b819b83afef0ddadc2e210ddce32a2be3) `safe` option.

**Comment by manugarri** [comment]
@avaris that could very well be the issue.

**Comment by astrojuanlu** [comment]
I guess this was closed because https://github.com/danielfrg/pelican-ipynb/issues/101 was fixed a long time ago, just for the record.
