### ISSUE TITLE
[autopages] Only returns the page path, does not render

### ISSUE THREAD

**Issue by Lucidiot** [getpelican/pelican-plugins#1083]
The [README](https://github.com/getpelican/pelican-plugins/blob/master/autopages/README.md) for the `autopages` plugin states the `author.page`, `category.page` and `tag.page` variables will hold the rendered content from the found pages, however they only hold a path to the pages and do not render the pages directly.

**Comment by avaris** [comment]
Code looks OK to me. How are you using them in the template?

**Comment by Lucidiot** [comment]
Excerpt from my `authors.html` template:

```
{% for author, articles in authors|sort %}
  ...
  {{ author.page }}
  ...
{% endfor %}
```

This prints the absolute path to the rst/md file associated to the author.

**Comment by avaris** [comment]
`author.page` is an actual `Page` object: same as pelican `Page`, or very similar to `Article`. So, you use it accordingly:

```
{{ author.page.content }}
{{ author.page.summary }}
{{ author.page.some_metadata }}
# etc...
```

**Comment by Lucidiot** [comment]
Oh! Okay, now it works, thanks! Shouldn't the README state that this is a Page object then, not *"rendered content"* (which I interpreted as the `.content`)?

**Comment by avaris** [comment]
Probably. Want to submit a PR? :)

**Comment by Lucidiot** [comment]
Here it is! #1085

**Comment by Lucidiot** [comment]
Closing as #1085 is merged
