### ISSUE TITLE
[better_figures_and_images] doesn't work with {static}

### ISSUE THREAD

**Issue by MeisterP** [getpelican/pelican-plugins#1117]
The warning is:
`WARNING: {filename} used for linking to staticcontent images/pages/pic.jpg in pages/text.md. Use {static} instead`

After using {static}, I get:
`Better Fig. Error: img_path should start with either {attach}, {filename}, |filename| or /static`

**Comment by vetetix** [comment]
I have submitted a pull request fixing this bug : https://github.com/getpelican/pelican-plugins/pull/1115

I don't know how things work on github, or in this project, so I don't know to help any further.

**Comment by justinmayer** [comment]
Ostensibly addressed via aforementioned pull request.

@MeisterP: If the issue persists after updating to the latest version, please feel free to comment here.
