### ISSUE TITLE
sub_parts not working

### ISSUE THREAD

**Issue by SnorlaxYum** [getpelican/pelican-plugins#1143]
Did as what it said: https://github.com/getpelican/pelican-plugins/tree/master/sub_parts
The sub parts won't be removed from the timeline. Also, the added parts in article.html just won't work.
Also did the test, the result:  
```
(work) [sim@simputer sub_parts]$ python test_sub_parts.py
Traceback (most recent call last):
  File "test_sub_parts.py", line 7, in <module>
    from pelican.tests.support import unittest, get_settings
ModuleNotFoundError: No module named 'pelican.tests'
```
Outdated?

**Comment by SnorlaxYum** [comment]
FILENAME_METADATA not working too

**Comment by Lucas-C** [comment]
`ModuleNotFoundError: No module named 'pelican.tests'`

AFAIK, this error means you haven't installed pelican from the git repo (_cf._ https://github.com/getpelican/pelican-plugins/blob/master/.travis.yml#L10), which provides this `pelican.tests` package.

But yes, the tests of this plugin are currently broken. There is already a PR to fix them: https://github.com/getpelican/pelican-plugins/pull/1179

What do you mean by:

> the added parts in article.html just won't work
