### ISSUE TITLE
Issue with MathJax availableFonts setting - [Math Processing Error] 

### ISSUE THREAD

**Issue by Timothy-Pulliam** [getpelican/pelican-plugins#1145]
I am having problems with my equations showing as [Math Processing Error] when I render them.

I have opened a issue with MathJax (see [here](https://github.com/mathjax/MathJax/issues/2148)) and they were able to determine the reason was, in the HTML-CSS preferences section of `mathjax_script_template`, there were some issues. I have been able to get my site working by making the following changes
```
 "    'HTML-CSS': {{ " +
 "        availableFonts: [{font_list}]," +                                                 
```

to this

```
"    'HTML-CSS': {{ " +
"        availableFonts: ['STIX', 'TeX']," +
"        preferredFont: 'STIX'," +
```
I tried to find where the error was in `math.py` but I do not see any issues, so I am unable to submit a pull request. However this appears to be a viable work around for now.

**Comment by Timothy-Pulliam** [comment]
I have reopened the issue with MathJax as the issue persists despite their recomendation.

**Comment by Lucas-C** [comment]
@Timothy-Pulliam : from your comment https://github.com/mathjax/MathJax/issues/2148#issuecomment-493509796 I understand you found the solution to your issue ?

**Comment by moorepants** [comment]
I'm getting this on local builds of my websites, since the last month or so. It works fine when served from a remote webserver though.

**Comment by Timothy-Pulliam** [comment]
This should be closed, a pull request has been approved. https://github.com/getpelican/pelican-plugins/pull/1146#event-2474676784
