### ISSUE TITLE
[sitemap] save_as not honoured

### ISSUE THREAD

**Issue by logological** [getpelican/pelican-plugins#1151]
For at least some of my pages, the sitemap plugin doesn't appear to be honouring the `save_as` metadata key.  For example, in [my website](https://github.com/logological/logological.org) I have a page [`miscellany.md`](https://raw.githubusercontent.com/logological/logological.org/master/content/pages/miscellany.md) with a metadata key–value pair `save_as: misc.html`.  Pelican correctly generates the file as `misc.html` but the sitemap plugin instead uses the default slug rules from [`pelicanconf.py`](https://github.com/logological/logological.org/blob/master/pelicanconf.py) (`PAGE_URL = '{slug}.html'` and `PAGE_SAVE_AS = PAGE_URL`) to generate the page's entry in `sitemap.xml`:

    <url>
    <loc>https://logological.org/miscellany.html</loc>
    <lastmod>2016-06-13T09:35:02+02:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.5</priority>
    </url>

**Comment by avaris** [comment]
It uses URL, so define `url` metadata as well. Otherwise it'll default to `PAGE_URL`.

**Comment by logological** [comment]
Is that a deliberate design decision?  If so, what's the use case?

**Comment by avaris** [comment]
Which design decision? 

`sitemap` using URL? I'm not the author but I'm fairly certain it is. Since a sitemap is supposed to list URLs (hence the `<url>...</url>`).

**Comment by logological** [comment]
But isn't the URL determined by (in part) the value of the `save_as` key?  If so, it seems like unnecessary redundancy (and a possible source of errors) to have to use `url` as well.  Is there any use case for having inconsistent values for `save_as` and `url`?  If not, then a better solution would be to make the plugin account for `save_as` the same way that Pelican itself does when determining the URL of a given page.

**Comment by avaris** [comment]
`pelican` *does not* use `save_as` to determine `url`. You have to explicitly specify. One can do as you did and set `PAGE_URL = PAGE_SAVE_AS`, but still you have to set both. Otherwise they would be out of sync. This follows to the per-content metadata.

One simpler option for you is to define `slug: misc` instead of `save_as`.

**Comment by logological** [comment]
> One simpler option for you is to define `slug: misc` instead of `save_as`.

I'm not sure how this is simpler as it isn't picked up by the sitemap plugin—I still have to manually define `url`.

**Comment by avaris** [comment]
You do? So, this doesn't work?
```
Title: Miscellany
slug: misc

[Content goes here]
```

**Comment by logological** [comment]
My apologies—I must have been doing something wrong during my previous tests.  Setting up my pages the way you suggest seems to result in correct URLs, both from Pelican and from the sitemap plugin.  Thanks for the workaround, and sorry for the false alarm.

**Comment by justinmayer** [comment]
@logological: Glad to hear it seems all has been resolved.

@avaris: Thanks for the guidance!
