### ISSUE TITLE
sitemap plugin doesn't respect *_URL settings

### ISSUE THREAD

**Issue by rdegges** [getpelican/pelican-plugins#116]
Check out: https://github.com/getpelican/pelican-plugins/blob/master/sitemap/sitemap.py#L21

It looks as if the sitemap plugin isn't respecting `ARCHIVES_URL`, `TAGS_URL`, and `CATEGORIES_URL`. I think this should be modified such that those settings are taken into account.

**Comment by justinmayer** [comment]
Not sure if this is still a problem. If so, please feel free to comment here so the issue can be re-opened.

**Comment by ggueret** [comment]
This is still a problem using Pelican 4.0.1. I've opened pull request https://github.com/getpelican/pelican-plugins/pull/1237 to support custom urls on standard pages.

**Comment by justinmayer** [comment]
Ostensibly addressed by @ggueret's PR above, so hopefully this issue has been fully resolved.
