### ISSUE TITLE
Incorrect repo URL results in CI error

### ISSUE THREAD

**Issue by justinmayer** [getpelican/pelican-plugins#1192]
This installs plugin dependencies: https://github.com/getpelican/pelican-plugins/blob/master/.travis.yml#L15

One of the dependency links is to `https://github.com/rst2pdf/rst2pdf/issues/799`, which clearly isn't a valid repository link: https://github.com/getpelican/pelican-plugins/blob/8c570febf510fc83583f69db3adcfcfff191c6ab/pdf/requirements.txt#L2

The resulting CI build failure: https://travis-ci.org/getpelican/pelican-plugins/builds/583717261

Refs #1168 #1170

**Comment by Lucas-C** [comment]
Taking a look

**Comment by Lucas-C** [comment]
I submitted https://github.com/getpelican/pelican-plugins/pull/1193 ,
let's see if the Travis CI goes further :)

**Comment by Lucas-C** [comment]
It seems better now
