### ISSUE TITLE
Liquid_tag Issue

### ISSUE THREAD

**Issue by dirkbosman** [getpelican/pelican-plugins#1196]
I am getting the following issue when uploading my repo to github pages. 

"Your site is having problems building: The tag generic on line 6 in pelican-plugins/liquid_tags/test_data/content/test-generic-config-tag.md is not a recognized Liquid tag. For more information, see"

It seems that it is not reading: {% generic config author %} for some reason. 

I added the following options in my "pelicanconf.py", but it also did not help. 

PLUGINS = ['sitemap', 'pelican-ipynb.markup', 'liquid_tags.notebook', 'liquid_tags.generic']

LIQUID_CONFIGS = (('PATH', '.', "The default path"), ('THEME', '', 'The theme in use'),
                  ('SITENAME', 'Default Sitename', 'The name of the site'), ('AUTHOR', '', 'Name of the blog author'))

Thanks in advance!

**Comment by Lucas-C** [comment]
What version of Python & Pelican are you using please ?
Also, have you updated your local copy of this repo to the latest version with `git pull` ?

Have you been able to find if this error was linked to a specific article ? Or does it appear even with zero article ? Could paste here the full stracktrace please ?

**Comment by dirkbosman** [comment]
Hi Lucase! Thanks for the reply :) 

I am running Python 3.7 in my venv.

**requirement.txt:**
appnope==0.1.0
attrs==19.1.0
backcall==0.1.0
bleach==3.1.0
blinker==1.4
decorator==4.4.0
defusedxml==0.6.0
docutils==0.15.2
entrypoints==0.3
feedgenerator==1.9
ipykernel==5.1.2
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.15.1
Jinja2==2.10.1
jsonschema==3.0.2
jupyter-client==5.3.1
jupyter-console==6.0.0
jupyter-core==4.5.0
MarkupSafe==1.1.1
mistune==0.8.4
nbformat==4.4.0
notebook==6.0.1
pandocfilters==1.4.2
parso==0.5.1
pexpect==4.7.0
pickleshare==0.7.5
prometheus-client==0.7.1
prompt-toolkit==2.0.9
ptyprocess==0.6.0
Pygments==2.4.2
pyrsistent==0.15.4
python-dateutil==2.8.0
pytz==2019.2
pyzmq==18.1.0
qtconsole==4.5.5
Send2Trash==1.5.0
six==1.12.0
terminado==0.8.2
testpath==0.4.2
tornado==6.0.3
traitlets==4.3.2
Unidecode==1.1.1
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.5.1
pelican>=3.5
jupyter>=1.0
ipython>=4.0
nbconvert>=4.0
markdown>=2.6.1

**Terminal Output:**
$ pelican content -o output
/Users/computer/project/username/pelican-plugins/liquid_tags/notebook.py:70: UserWarning: Pelican plugin is not designed to work with IPython versions greater than 1.x. CSS styles have changed in later releases.
  warnings.warn("Pelican plugin is not designed to work with IPython "

I updated my modules by doing (as in this article: https://janakiev.com/blog/pelican-jupyter/):
$ git submodule update --init --recursive
$ git submodule update --remote --merge --recursive

I still see this error when I view my commit to GH:
https://imgur.com/a/agZ1xPU

Thanks for the help :)

**Comment by Lucas-C** [comment]
I guess your blog sources must be private, but it would be very helpful to have the full execution log, and the content of this `test-generic-config-tag.md` file (or a least its 6th line).

Could you also execute those commands please:
```
pelican content -o output -D
cd pelican-plugins
git pull
git rev-parse HEAD
```

**Comment by justinmayer** [comment]
Hi @dirkbosman. I hope you were able to resolve the problem you encountered. If not, let us know how we can be of further assistance.
