### ISSUE TITLE
[summary] code blocks are messed up in article summary

### ISSUE THREAD

**Issue by edelooff** [getpelican/pelican-plugins#1203]
Using a current Pelican version and `pelican-plugins` checkout, rendering code blocks in the summary of an article fails to render correctly:

![render-bad](https://user-images.githubusercontent.com/490090/65376191-65f45b80-dc9d-11e9-871b-3a149de6bd17.png)

It appears the source of this is in #758 which indiscriminately removes all `<div>` tags, including the `<div class="highlight">` necessary for code blocks. Removing the two lines that strip those tags results in the expected summary content:

![render-correct](https://user-images.githubusercontent.com/490090/65376206-86bcb100-dc9d-11e9-8efa-ceedb858ee21.png)

Going through the generated output after reverting that PR, I can't find any obvious trailing `<div>` tags that the PR fixes, so possibly that problem has gone away in the intervening years.

**Comment by justinmayer** [comment]
Hi Elmer. Setting aside for the moment the question of whether `<div>` tags should be removed from article summaries, could you help me understand why would someone would want code blocks to appear in an article summary?

**Comment by edelooff** [comment]
Hi Justin. For the simple reason that sometimes a code snippet is the best way to summarize or open an article.

From your question I get the impression that that's an unexpected use case, or perhaps I'm missing some other concern. I'm mainly looking at this from the point of view of an article listing where you want a reasonable introduction to an article. This isn't necessarily a _summary_ (more an intro or teaser), but it appears like the tool to use.

**Comment by justinmayer** [comment]
@edelooff: I was just curious, as it would never occur to me to have a code snippet presented within an article summary. That said, after reading your explanation, I understand that being able to do so is useful for some folks.

This is perhaps part of a broader question of how to handle complex data in article summaries, a topic you helped raise years ago in https://github.com/getpelican/pelican/issues/1369. I'm not sure I have a good answer to this question. In this particular case, I wonder whether there might be a way to removed _unmatched_ `div` tags instead of removing all of them indiscriminately.

**Comment by edelooff** [comment]
I was going to write something about "but Pelican should generate valid HTML". Of course, it does, and then the summary plugin takes that well-formed HTML and carves out a literal chunk of it, causing all sorts of problems. So let's see if we can actually clean up the carved piece.

The problem described by #758 is easy enough to reproduce by putting a marker partway through a section, and it does indeed generate erroneous HTML:

```rst
.. PELICAN_BEGIN_SUMMARY

Opening heading
===============

Just a quick paragraph of text

.. PELICAN_END_SUMMARY

More content so our marker definitely breaks up a section.
```

```html
<article>
    <h2><a href="/posts/example-post">Example&nbsp;post</a></h2>
    <div class="summary">
        <div class="section" id="opening-heading">
            <h2>Opening heading</h2>
            <p>Just a quick paragraph of text</p>
            <a class="btn btn-default btn-xs" href="/posts/example-post">more ...</a>
        </div>
</article>
```

With a little bit of formatting, the missing `</div>` is pretty obvious. We could strip the last opening `div` tag but that's probably wrong, and doing anything *better* is just getting difficult. Good thing is, we don't have to do anything difficult. People far more determined have already created BeautifulSoup, which will do *The Right Thing:tm:*: `summary = str(BeautifulSoup(summary, 'html.parser'))`

This will turn the invalid HTML above into this,valid (and I think desireable) HTML:

```html
<article>
    <h2><a href="/posts/example-post">Example&nbsp;post</a></h2>
    <div class="summary">
        <div class="section" id="opening-heading">
            <h2>Opening heading</h2>
            <p>Just a quick paragraph of text</p>
        </div>
        <a class="btn btn-default btn-xs" href="/posts/example-post">more ...</a>
    </div>
</article>
```
Letting BeautifulSoup (or rather, the html5 standard) decide how to process invalid HTML seems like a significantly safer bet than deleting tags based on a guess. This has the side benefit of cleaning up all sorts of other stray tags without any real-world effect, because the browsers do (or should, anyway) the same thing in the face of invalid markup.

If you think this is reasonable, I can set up a PR with this implementation.
