### ISSUE TITLE
Math uses wrong delimiters in display mode ($$) with render_math

### ISSUE THREAD

**Issue by andrewheiss** [getpelican/pelican-plugins#1212]
Using the current version of `render_math` and Pelican 4.1.2, inline math is rendered correctly (i.e. `$math$` is converted to `\(math\)`, which is then rendered with MathJax), but display mode math gets converted to `\($math$\)`, and MathJax renders the $.

Here's minimal example using Markdown:

```
Title: Math time
Date: 2019-09-27 09:30

Here's some inline math: $x + y = 30$

And here's some display math:

$$
x + y = 30
$$
```

This gets converted to the following HTML:

```html
<p>Here's some inline math: <span class="math">\(x + y = 30\)</span></p>
<p>And here's some display math:</p>
<p><span class="math">\($
x + y = 30
$\)</span></p>
```

**Comment by andrewheiss** [comment]
Here's what it looks like when rendered (note the $s remain in the display block):

![image](https://user-images.githubusercontent.com/73663/65811648-c0078c00-e189-11e9-900e-b53c3ad98ddb.png)

**Comment by andrewheiss** [comment]
The expected output should be 

```html
<p><span class="math">$$
x + y = 30
$$</span></p>
```

**Comment by andrewheiss** [comment]
Reverting back to 6f8082c fixes this

**Comment by avaris** [comment]
I think the priorities are in wrong order. Can you switch [these](https://github.com/getpelican/pelican-plugins/blob/master/render_math/pelican_mathjax_markdown_extension.py#L149-L150) and check? `185` to `186` and vice versa.

cc: @Lucas-C

**Comment by andrewheiss** [comment]
Yep, swapping 185 and 186 for inline and display works. I just submitted a PR to fix it.

**Comment by Lucas-C** [comment]
Ah, good catch !
I must have made a mistake here when moving from the deprecated `.add` method to `.register` : https://github.com/Python-Markdown/markdown/pull/688/files#diff-0f2fbb4d1e47771e120a801756331eceR389
