### ISSUE TITLE
[i18n_subsites] Not pay attention to Page_URL & Page_SAVE_AS

### ISSUE THREAD

**Issue by hojati** [getpelican/pelican-plugins#1228]
Dear Team,
The translation plugin does not pay attention to PAGE_URL & PAGE_SAVE_AS metadata attributes.
I dont want to create any "pages" folder and the two attributes is like this:
`PAGE_URL = '{slug}.html'`
`PAGE_SAVE_AS = '{slug}.html'`
It means that all documents in pages folder are going to save in output/ root directory. but when I add a document with different language two things happen:
1. It suddenly creates pages folder in main language output directory and add <title in othe language>-<lang>.html to it.
2. It also adds <title in th language>.html in output/<lang> root directory for the other language. And it doesnt even pay attention to slug metadata.
the config for i18n_subsites is:
`I18N_SUBSITES = {
    'de': {
        'SITENAME': 'Title',
        }
    }`
It is getting a little bit complicated, so I add some images too.
![2019-11-01_19-38-32](https://user-images.githubusercontent.com/21156214/68039071-938ee480-fce0-11e9-9303-ea4ad6629f57.png)
![2019-11-01_19-38-55](https://user-images.githubusercontent.com/21156214/68039074-938ee480-fce0-11e9-8def-cbd2563a194d.png)
![2019-11-01_19-39-10](https://user-images.githubusercontent.com/21156214/68039075-94277b00-fce0-11e9-9bd6-edff5aa29d1c.png)
![2019-11-01_19-40-26](https://user-images.githubusercontent.com/21156214/68039077-94277b00-fce0-11e9-87f6-5e602f50790a.png)
![2019-11-01_19-40-47](https://user-images.githubusercontent.com/21156214/68039078-94277b00-fce0-11e9-84fa-ac32c15b994a.png)

kind regards

**Comment by avaris** [comment]
See `PAGE_LANG_URL` and `PAGE_LANG_SAVE_AS` in [`pelican` settings](http://docs.getpelican.com/en/stable/settings.html#url-settings).

Also, is that `slang` a typo and supposed to be `slug`?

**Comment by hojati** [comment]
Absolutely right, sorry for my rush
