### ISSUE TITLE
pelican-plugins as git submodule: "Server does not allow request for unadvertised object" and "Direct fetching of that commit failed."

### ISSUE THREAD

**Issue by philshem** [getpelican/pelican-plugins#1230]
I'm using this repo as a submodule of my personal website. My .gitmodules looks like this:

```
[submodule "pelican-plugins"]
	path = pelican-plugins
	url = https://github.com/getpelican/pelican-plugins
```

To get any updates to the submodule (this repo), I run `git pull` in my own repository:

```
$ git pull
Fetching submodule pelican-plugins
Already up to date.
error: Server does not allow request for unadvertised object ac7d9f342712166a4c87880fc5eef31cd6975292
Fetched in submodule path 'pelican-plugins', but it did not contain ac7d9f342712166a4c87880fc5eef31cd6975292. Direct fetching of that commit failed.
```

This is a relatively new error. The same error occurs when I run `git submodule update`

---

*Temp solution:*

     git submodule update --force --recursive --init --remote

But as the [StackOverflow answer says itself](https://stackoverflow.com/a/56621295/2327328)

> Of course this is really not a good solution. It is better to find and solve the underlying problem, but if anyone is in hurry, this was worked for me.

*Really* not a good solution.

**Comment by philshem** [comment]
Trying random things seems to have worked:

    git submodule sync

and then
   
    git submodule update

and then 

    git pull

**Comment by Lucas-C** [comment]
I tried the following to reproduce your issue:
```
# mkdir test && cd test
# git init
# git submodule add https://github.com/getpelican/pelican-plugins.git
# git commit -m 'Initial commit' && git push ...
# git ls-tree HEAD pelican-plugins
160000 commit 60791924c5f953ba5b7a463177054bfc7c3282e8  pelican-plugins
```

I did not get any error.
Could you submit some minimal set of steps to reproduce your issue please ?

I am not a git submodules expert, but my understanding from the [official tutorial](https://git-scm.com/book/en/v2/Git-Tools-Submodules) is that a `git submodule update --remote` command is probably what you need, not just `git pull`.

More useful info here: https://stackoverflow.com/questions/1979167/git-submodule-update/1979194#1979194

**Comment by philshem** [comment]
I'm not able to reproduce the error, and I think it may have been how I was running 'git submodule' (from my repo's home directory, and not from the submodule directory).
