### ISSUE TITLE
jinja2content giving "super() takes at least one argument" error

### ISSUE THREAD

**Issue by acrimer** [getpelican/pelican-plugins#1236]
Hi,

I'm trying to use the `jinja2content` plugin but then when I run pelican in any way I get a critical TypeError related to that plugin's use of super(). This is true whether I'm using Python 2 or Python 3, and I didn't modify the plugin in any way. 

Does anyone know what's going on?

**Comment by kdeldycke** [comment]
FTR, `jinja2content` plugin has been moved to its own repository at: https://github.com/pelican-plugins/jinja2content

**Comment by justinmayer** [comment]
Hi Andrew. If you can reliably reproduce the problem you reported here with Pelican 4.5.4 and Jinja2Content 1.0.1, please submit more detail at the new independent repository: https://github.com/pelican-plugins/jinja2content

Thank you!
