### ISSUE TITLE
Split out plugins into submodule repos

### ISSUE THREAD

**Issue by alfiepates** [getpelican/pelican-plugins#1239]
In the interest of keeping my Pelican installations lightweight, I only want to retain the plugins I'm actually using, instead of cloning the entire plugins repo. 

For plugins that are already submodules, this is easy - I just clone the submodule. However, for plugins like `gallery` which just exist as subdirectories in this repo, I have a grotty setup using `git-filter-repo` to clone just the subdirectories of the plugins I'm interested in. 

My workaround is bad and I'd like to not have to use it - is there an appetite for splitting out even the simpler plugins into their own repos, and retaining them as submodules in this repo for developers who may still want All The Plugins?

**Comment by avaris** [comment]
See #425

**Comment by justinmayer** [comment]
The whole sub-module business is a kludge that I never liked. As @avaris mentioned, we're now encouraging plugin developers to collaborate together, [Jazzband](https://jazzband.co)-style, in individual plugin repos under the new organization: https://github.com/pelican-plugins

This is still a work-in-progress, with only a handful of plugins migrated over. But hopefully that will accelerate in the weeks and months to come.
