### ISSUE TITLE
liquid_tags: Instagram and Flickr have the ability to define albums with more than one photo how to use them?

### ISSUE THREAD

**Issue by iranzo** [getpelican/pelican-plugins#1242]
I've been trying to get using liquid_tags al album displayed on Pelican in a similar way to what I get on telegram preview:

![image](https://user-images.githubusercontent.com/312463/73144643-1937eb80-40a8-11ea-9e2f-1d2d3f062493.png)

With both Flickr and Instagram 'plugins' in liquid_tags I just get one image (in the case of instagram is even worse because even if a set is provided, it just points to initial picture and doesn't offer a chance to link to instagram in a similar way on how it does for flickr where the image is actually linked to the flickr website).

Related with https://github.com/Pelican-Elegant/elegant/issues/385

**Comment by iranzo** [comment]
Is that even possible or planed at all?

**Comment by iranzo** [comment]
https://stackoverflow.com/questions/42491896/how-to-retrieve-all-images-from-multiple-photo-post-on-instagram

**Comment by justinmayer** [comment]
Hi Pablo. I have never used the Liquid Tags plugin and thus can't be of much assistance. Were you ever able to achieve what you wanted here?

**Comment by iranzo** [comment]
No, I finally moved to a javascript that gets the instragam pictures in multipost and similar for imgur using photoswipe javascript gallery as that required no api configured

**Comment by justinmayer** [comment]
Gotcha. Thanks for the update!
