### ISSUE TITLE
Question regarding the use of a cache in pelican plugins / where to store its state

### ISSUE THREAD

**Issue by Lucas-C** [getpelican/pelican-plugins#1245]
Pelican already uses a cache, configurable through the `CACHE_PATH` setting, defaulting to a `./cache/` sub-directory.

While starting working on [a linkbacks plugin](https://github.com/pelican-plugins/linkbacks), I realized I had a need for some cache / state between executions of my plugin.

Should it use the `CACHE_PATH` directory? Else, is there a recommandation on what cache to setup / use? Should it uses something like the [appdirs](https://pypi.org/project/appdirs/) package to determine a cache directory path?

**Comment by avaris** [comment]
`appdirs` doesn't make much sense since this will be a project specific cache. `CACHE_PATH` would be fine, I think.

**Comment by Lucas-C** [comment]
Great, I'll try this approach, thank you for your answer :)
-> WIP commit: https://github.com/pelican-plugins/linkbacks/commit/cc0412e

Closing this issue now
