### ISSUE TITLE
subcategory plugin - Change article URL

### ISSUE THREAD

**Issue by thecaligarmo** [getpelican/pelican-plugins#1255]
At the end of the readme, for subcategory it says to use the following to add subcategories into the url:

```
ARTICLE_SAVE_AS = os.path.join('{subpath}', 'articles', '{slug}.html')
ARTICLE_URL = '{suburl}/articles/{slug}.html'
```
(technically they're missing the commas, but I added those in for the os.path.join.)

When trying that I get the following error:
`CRITICAL: KeyError: u'suburl'`

Looking at the code, it looks as though it should work, so I don't know how to fix it .-.

**Comment by thecaligarmo** [comment]
I think I have found a solution to the problem. Since the plug-in hasn't been updated in forever, am I allowed to submit an update to the plug-in? Or would it be better for me to create a clone plug-in, with the necessary changes, and add that to the repository?

**Comment by oulenz** [comment]
You could also try out the [more_categories](https://github.com/pelican-plugins/more-categories) plugin, which also enables nested categories and should be up-to-date.

**Comment by avaris** [comment]
@thecaligarmo you can update the plugin and submit a PR.

**Comment by justinmayer** [comment]
Indeed, no need to duplicate the plugin. Always better to enhance existing ones than to create superfluous clones.

**Comment by thecaligarmo** [comment]
Sounds good all =) I think a good option is to use the more_categories plug-in that @oulenz  suggested and incorporate the "subcategories" idea into it as it seems cleaner. 

@avaris How do I submit a PR? (I assume PR is pull request?)  I've never worked in bigger circumstances like this =/

**Comment by justinmayer** [comment]
@thecaligarmo: Glad to hear you'll be rolling up your sleeves and digging in. A good place is the [Pelican core development docs](https://docs.getpelican.com/en/latest/contribute.html#contributing-code). Not all of it is relevant to plugin development, but most of it should be. Feel free to reach out with any questions!

**Comment by oulenz** [comment]
@thecaligarmo You misunderstand (I wasn't clear enough): the more_categories plugin already enables subcategories, so you don't need to incorporate that feature, you can simply see whether it suits your use case. (You are of course welcome to suggest additional functionality if it doesn't!)

I was facing a similar choice as you, change the subcategory plugin or write my own, except that what I wanted broke backwards compatibility and there was no good way to handle that, so I created more_categories (which also enables multiple categories per article).

So for myself the more_categories plugin supersedes the subcategory plugin, but I don't want to discourage others from continuing to use and improve the subcategory plugin, they can live side-by-side.

**Comment by thecaligarmo** [comment]
@oulenz Neither of the plugins did exactly what I wanted, but was close. I figure it's good to add functionality to at least one of them. I like the set-up of more_categories better, so I want to contribute to that =) I understood what you said, it's just that neither of them have the exact feature I want.

**Comment by thecaligarmo** [comment]
@justinmayer What should I do if I get errors in the "invoke setup" part? I can't even get past that in order to contribute .-. Should I just ignore it and do everything else without running the test-suite?

**Comment by justinmayer** [comment]
It would be better to resolve the errors. What exactly does the error output say?

**Comment by thecaligarmo** [comment]
Here's what I get from start to end:

```
/xxx/pelican$ git clone git@github.com:thecaligarmo/more-categories.git ./projects/pelican-plugins/more-categories
Cloning into './projects/pelican-plugins/more-categories'...
Enter passphrase for key '/home/xxx/.ssh/id_rsa': 
remote: Enumerating objects: 76, done.
remote: Counting objects: 100% (76/76), done.
remote: Compressing objects: 100% (45/45), done.
Receiving objects: 100% (76/76), 24.87 KiB | 2.76 MiB/s, done.
Resolving deltas: 100% (26/26), done.
remote: Total 76 (delta 26), reused 69 (delta 20), pack-reused 0
/xxx/pelican$ cd projects/pelican-plugins/more-categories/
/xxx/pelican/projects/pelican-plugins/more-categories$ git remote add upstream https://github.com/pelican-plugins/more-categories.git
/xxx/pelican/projects/pelican-plugins/more-categories$ invoke setup
Traceback (most recent call last):
  File "/usr/bin/invoke", line 9, in <module>
    load_entry_point('invoke==0.11.1', 'console_scripts', 'invoke')()
  File "/usr/lib/python2.7/dist-packages/invoke/cli.py", line 438, in main
    dispatch(sys.argv)
  File "/usr/lib/python2.7/dist-packages/invoke/cli.py", line 423, in dispatch
    args, collection, parser_contexts = parse(argv, version=version)
  File "/usr/lib/python2.7/dist-packages/invoke/cli.py", line 286, in parse
    collection = loader.load(coll_name) if coll_name else loader.load()
  File "/usr/lib/python2.7/dist-packages/invoke/loader.py", line 51, in load
    module = imp.load_module(name, fd, path, desc)
  File "/xxx/pelican/projects/pelican-plugins/more-categories/tasks.py", line 6
    PKG_PATH = Path(f'pelican/plugins/{PKG_NAME}')
                                                ^
SyntaxError: invalid syntax
```

I was using [this guideline](https://docs.getpelican.com/en/latest/contribute.html#plugin-development) to try and set it up.

**Comment by justinmayer** [comment]
It seems you are using Python 2.7, whereas Pelican now requires Python 3.6 or above. What operating system and version are you using?

**Comment by thecaligarmo** [comment]
Hmmm ok. I can try using python 3 instead (might take me some time, but I'll try later today).
I'm using Ubuntu 18.04

**Comment by thecaligarmo** [comment]
Ok, so I switched to python 3; and now when I run `invoke setup` I just get "No idea what 'setup' is!" Is there supposed to be some base file that handles set-up? Or is it ok that there is no setup file?

**Comment by justinmayer** [comment]
Ah, I see the problem. Invoke looks for a file named “tasks.py”, which in the case of the [More Categories](https://github.com/pelican-plugins/more-categories) plugin, does not contain a `setup` task. If you look at the tasks.py files inside most of the other repos under that organization, you'll see that `setup` task. [Here's an example](https://github.com/pelican-plugins/render-math/blob/master/tasks.py#L77), which does this:
```
python -m pip install -U pip poetry pre-commit
poetry install
pre-commit install
```
What happens if you run the steps above and then try running `invoke tests`?

**Comment by thecaligarmo** [comment]
But my python is version 2.7. So should I do something like:
```
python3 -m pip install -U pip poetry pre-commit
poetry install
pre-commit install
```
Or maybe `pip3` instead of pip?

Or should I be using the python 2.7 versions of the above?

**Comment by avaris** [comment]
@thecaligarmo start with creating a [virtual environment and activating it](https://docs.getpelican.com/en/latest/contribute.html#setting-up-the-development-environment) first.

**Comment by thecaligarmo** [comment]
@avaris That's already done .-. The issue right now is that when I try and `invoke setup` it says "No idea what 'setup' is!". So I'm trying to figure out how to do that properly. And since I have two versions of python on my machine, I want to make sure everything I'm doing is using the correct versions so that there aren't other issues.

**Comment by avaris** [comment]
@thecaligarmo if you created a virtual environment with `python3` and activated it, then `python`, `pip` etc would point to the venv, not your system python.

**Comment by thecaligarmo** [comment]
@avaris Yeah, I've been reading the venv docs on python's website since I'm new to it all. I just read that part. That's pretty cool =D

Ok, since I'm doing pelican-plugins instead of pelican, give me a sec to figure it out. I'll test the above once I understand what's happening.

**Comment by thecaligarmo** [comment]
Ok, I get kinda what's happening now. I'm going to update the tasks.py file to use the more standard methods that I'm seeing in the other plugins.

Thanks all =)

**Comment by thecaligarmo** [comment]
Ok, I think everything is ok now. I pushed my changes up to origin, but I'm not sure what I'm supposed to do at this point? Do I need to inform anyone that a fork/change has been made, or will the owner know that a change has been made? (I think @justinmayer you're technically the owner of that plugin and/or you've edited it before?)

**Comment by avaris** [comment]
If you go to your fork on Github, you should see something at the top for creating a Pull Request from the branch you pushed.

**Comment by thecaligarmo** [comment]
Do I request a pull request when it's all done and that's how it would get incorporated in? (I realized I should probably update the README with the new functionality, so I'm gonna do that first)

**Comment by avaris** [comment]
Any changes you do to that branch (push new commits, rebase etc) will be reflected in the pull request while it is open. So you can add stuff later. But, it is better to open PR when you consider it "done". If it is not finished but you want some feedback, you can also make a [draft pull request](https://github.blog/2019-02-14-introducing-draft-pull-requests/).

**Comment by thecaligarmo** [comment]
Done. Thank you!!!
