### ISSUE TITLE
Signal handler calling order issue

### ISSUE THREAD

**Issue by traits** [getpelican/pelican-plugins#1260]
I'm developing a plugin, which introduces some meta informations at article level in the following form (markdown example):

`scripts: a.js, b.js`

From this information, the plugin must 1) produce a list of files, enriched by path information and 2) a list of derived strings for embedding in html output (example for an element: `'<script type="module" src="a.js"></script>'` )

I registered two signal handlers to do this:

```
signals.article_generator_context.connect(format_tags)
signals.article_generator_write_article.connect(add_files)
```    

I cannot handle the creation of both mentioned lists in a single handler because the callback functions always misses at least one thing:  `format_tags`  signature takes a generator and metadata, but no content (which contains exclusively the required path information).  `add_files` has this information (and the metadata implicitely by his `content` argument) but is triggered too late in the following sense:

`format_tags` is called first. Somewhere after this call but before the call to `add_files` meta information seems to be written or at least 'freezed' for output. In any case, I'm unable to change metadata in `add_files` before writing the output (documentation for `article_generator_write_article` suggests otherwise). For the moment, I'm preserving the original metadata in some temporary key and evaluate this version in `add_files` in order to produce the first of my mentioned lists. The original metadata itself is transformed into a list of formatted strings (see above) by `format_tags` and unusable for `add_files`.

Am I'm missing something obvious here? In particular, at what point in the order of things evaluates the themes template something like `article.scripts` ?

To make it an issue: 

- plugin development documentation information lacks more precise information here
- the combination of signal handler entry points and callback signature seems incomplete to me (at least at this moment).  At the same time as the invocation of `article_generator_context` I would need a signal with a callback signature of `(gen, content)`.

**Comment by avaris** [comment]
I read this multiple times to understand, but no success. Maybe I am a bit slow today :). Then I checked the commit above and I *think* now I understand the issue and what you mean by "frozen".

At content object creation, metadata is turned into attributes [by `setattr`](https://github.com/getpelican/pelican/blob/c8639fe547e093ce5416e353e20b8ad5fde95f02/pelican/contents.py#L54-L58) so that you can do `article.my_metadata` instead of `article.metadata['my_metadata']`. That essentially creates a *copy* and changing one won't change the other [*].

That being said, you seem to be using `generator` only for path information. Which is already [in the settings](https://github.com/getpelican/pelican/blob/c8639fe547e093ce5416e353e20b8ad5fde95f02/pelican/__init__.py#L52-L54) and content objects have access to that (`content.settings`). So, you should be able to do everything you need from `content_object_init` which fires just after a `Content` is created and it passes the instance that was created.

[*] This *could* be changed into `__getattribute__` implementation to avoid this copy, but would require some refactoring (and possibly some complications).

**Comment by traits** [comment]
> `content.settings`

This simplified things a bit, but the fundamental problem remains:

> you should be able to do everything you need from `content_object_init`

I tried this, but it seems to have the same problem - it is called too late (this also follows immediately from the [provided link](https://github.com/getpelican/pelican/blob/c8639fe547e093ce5416e353e20b8ad5fde95f02/pelican/contents.py#L54-L58)) for metadata changes. But it _is_ working for `article_generator_context` for example.

**Comment by avaris** [comment]
Too late for what? What I tried to say above is that you should stop using `content.metadata` to get your metadata and do `getattr(content, 'my_metadata')` instead, if you want to access this *after* `Content` object creation.

**Comment by traits** [comment]
For read access, this is OK. But I also need write access to metadata at this point. If I understand correctly, this is simply not possible. I must change this before the `Content` constructor was called.

**Comment by avaris** [comment]
Not at all... Interface to access and modify metadata after `Content` creation is through attributes, not though `Content.metadata`. Here, I am basing this on the [this commit](https://github.com/traits/dynamic_plot/blob/5d947732a4ad8cc473c62d6ab1790719b245637c/dynamic_plot.py)

```python
def get_mapping(gen, content, tag, formatter):
    # NOPE! metadata = content.metadata
    # ...

    # do this instead:
    files_str = getattr(content, tag)
   
    # ...
    return result


def evaluate_tags(gen, content):
    """
    Receive generator, content and metadata at a single point
    and extract relevant information
    """
    # NOPE! metadata = content.metadata
    scripts = get_mapping(
        gen, content, "dynplot_scripts", '<script type="module" src="{0}"></script>',
    )
    styles = get_mapping(
        gen,
        content,
        "dynplot_styles",
        '<link rel="stylesheet" href="{0}" type="text/css" />',
    )
    global file_mapping
    if scripts:
        file_mapping += scripts
        #  user scripts
        # NOPE! metadata["dynplot_scripts"] = [x[2] for x in scripts]
        # do this instead:
        content.dynplot_scripts = [x[2] for x in scripts]
        #  master scripts
        for url_tag in ["dynplot_d3_url", "dynplot_three_url"]:
            url = get_effective_option(metadata, gen.settings, url_tag)
            url = f'<script src="{url}"></script>'
            # NOPE! metadata["dynplot_scripts"].insert(0, url)
            # do this instead:
            content.dynplot_scripts.insert(0, url)
    if styles:
        file_mapping += styles
        # user styles
        # NOPE! metadata["dynplot_styles"] = [x[2] for x in styles]
        # do this instead:
        content.dynplot_styles = [x[2] for x in styles]
```

**Comment by traits** [comment]
Now, it has clicked. Problem solved, all things are working now. I have learned a bit about Pelicans inner structure. I will close this. Thanks!
