### ISSUE TITLE
New reader for pandoc

### ISSUE THREAD

**Issue by nandac** [getpelican/pelican-plugins#1261]
Hi Pelican Plugins Team,

I made several improvements to the pandoc_reader plugin and submitted a pull request to the original author but it has not been merged and there has been no development on it for six years.

I was wondering if I could submit the plugin as myself?

Furthermore, I would like to know what you would suggest I name the plugin so that it does not cause confusion with the original plugin.

Kindly advise and I will do accordingly.

Thanks in advance.
Nanda

**Comment by justinmayer** [comment]
Hi Nandakumar. Thank you for the thoughtful message. We are actually in the process of transitioning away from the submodule pattern and have instead recently begun migrating plugins to their own repositories under the new [Pelican Plugins organization](https://github.com/pelican-plugins). That way, we can all collaborate on the endeavor together, in a sort of [Jazzband](https://jazzband.co) style. In the next day or two, I will create a repository for the Pandoc reader plugin under the new organization and open a pull request there so we can begin improving this plugin together. I'll be sure to @-mention you from there once it's ready. ✨

**Comment by nandac** [comment]
Thanks Justin for getting back to me so quickly.

I look forward to working with you and the team.

Cheers.

**Comment by nandac** [comment]
Hi Justin,

I just wanted to check in with you on how the plugin migration is going.

I am thinking of using the name pandoc-parser for my plugin to differentiate it from the old pandoc-reader plugin.

Are we free to create our own repository under the new organization or is there some permissions process I should go through.

Please keep me posted. I am happy to help in any way I can.

Cheers.

**Comment by nandac** [comment]
@justinmayer Has there been much traction on the above project. I want to create a repository for my plugin in the new organization.

Would you mind creating it for me, please?

The repo name should be `pandoc_parser` instead of `pandoc_reader` I think to avoid confusion with the existing pandoc_reader which is not functioning correctly.

Kindly let me know if you need any other information from me.

Cheers,
Nanda

**Comment by kdeldycke** [comment]
I guess this can be closed now that #1303 has been addressed and the new `pandoc_reader` plugin has been migrated and released on PyPi?

**Comment by justinmayer** [comment]
Indeed. Thanks, Kevin!
