### ISSUE TITLE
[graphviz] no labels when publish

### ISSUE THREAD

**Issue by kakila** [getpelican/pelican-plugins#1273]
Hi,
In the following blog
https://kakila.gitlab.io/mistake-learning/wta-dynamics.html
you will see that the node labels are not rendered correctly.

Locally in my machine everything works fine
![image](https://user-images.githubusercontent.com/2747655/85006564-91d43d00-b15a-11ea-83d4-de6696542d87.png)

The source code of the post is here https://gitlab.com/kakila/mistake-learning/-/blob/master/blog/content/wtadynamics.md

The script I use in the remote is here https://gitlab.com/kakila/mistake-learning/-/blob/master/.gitlab-ci.yml
The remote uses alpine-python3.8 which has graphviz 2.44.0-r0, while my local (ubuntu 20.04) has 2.42.2-3build2
All the dependencies are installed:

    pelican>=4.1.0
    typogrify
    beautifulsoup4
    # liquid_tags
    markdown
    # pelican-cite
    pybtex

Is liquid_tags expecting a particular version of graphviz?
Or maybe there is an implicit dependency to generate the png which is installed in my local and not in alpine?

Thanks for any hint.

**Comment by kakila** [comment]
Hi all,
any hints on this? I keep trying other images but can spot what's the problematic dependency.

Thanks

**Comment by justinmayer** [comment]
I'm sorry, but I have zero experience with any of the plugins/tooling you are using here, so I'm completely unable to assist you with this issue. Perhaps someone else will come across this and have a suggestion. Either way, I hope you are able to track down the source of the problem.

**Comment by kakila** [comment]
Do you know who is the original contributor of the graphviz tag?

**Comment by kdeldycke** [comment]
The `liquid_tags` plugin has been migrated as a stand-alone plugin at https://github.com/pelican-plugins/liquid-tags . I recommend you to try out that new version as some bugs were fixed and the plugin is actively being worked on over there.

In the mean time I guess we can close this issue?

**Comment by justinmayer** [comment]
@kakila: Sorry we weren't able to provide more assistance with this issue. Perhaps try the latest version via the new repository mentioned above.

@kdeldycke: Thanks for the nudge!
