### ISSUE TITLE
[i18n_subsites] Is a redirection to the detected language possible?

### ISSUE THREAD

**Issue by therealmaxmoon** [getpelican/pelican-plugins#1278]
I want the page to redirect the user to the right language if the used language in the browser is in the i18n array.

Example:
1. User has a browser with the language German as default language
2. My pelican blog has 'de' in the array and redirects to https://domain.tld/de

Example:
1. User has a browser with the language Polish as default language
2. My pelican blog has not 'pl' as a supported language and redirects to the default language (https://domain.tld)

Is something like this possible?

**Comment by avaris** [comment]
Probably, via a server configuration (e.g. [`Accept-Language`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language))

**Comment by kernc** [comment]
Was just about to concur only a server-side detection is possible. Then I stumbled upon [`navigator.languages`](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/languages#Browser_compatibility).

**Comment by therealmaxmoon** [comment]
I see the problem, if someone has English as the configured browser language, but still want to read the blog in German, the person would click on the language button to switch to German, but the website would immediately redirect the person back to the English version.

Am I understanding it right? And is there a good way to avoid this?

**Comment by kernc** [comment]
Definitely. Your initial auto-redirect and any later user's manual language switching, should store the preferred language [in a cookie](https://stackoverflow.com/questions/25154515/save-last-language-preference-of-the-user-in-a-cookie). And then don't redirect when this is set and current.

If you make a script, do consider sharing it.
