### ISSUE TITLE
New plugin proposal: Flattr button

### ISSUE THREAD

**Issue by silverhook** [getpelican/pelican-plugins#128]
[Flattr](http://flattr.com) is quite a popular microdonation system and very popular with blogs. It would be great to see a plugin exist also for Pelican.

In general all it takes is to [embed a small script](https://flattr.com/embed) into each of the blog posts and that’s it.

There are [many plugins/tools listed on Flattr’s page](http://developers.flattr.net/tools/) and amongst them there is also [a plugin for Hyde](https://github.com/melpomene/Flattr-auto-submit-for-Hyde).

I don’t know how similar Pelican and Hyde are apart from both using Python, but it could be used for reference.

**Comment by justinmayer** [comment]
If someone would like to write a plugin for this, please feel free to submit it to the repository.
