### ISSUE TITLE
Migration to https://github.com/pelican-plugins

### ISSUE THREAD

**Issue by m000** [getpelican/pelican-plugins#1280]
Hey guys, I found a comment in a recently merged PR that there's an ongoing migration from the monolithic repo to a multi-repo scheme under https://github.com/pelican-plugins.
IMHO this is something that should be prominently displayed in README.md to hint that there may be hiccups in handling PRs and such during the transition period. Perhaps also ask for helping hands if there's anything that users can do to speed up the transition.

**Comment by justinmayer** [comment]
Thanks for the nudge, @m000. I added a note via #1286. What do you think?   [cc: @kernc @jwodder]
