### ISSUE TITLE
wrong out_path in thumbnailer plugin

### ISSUE THREAD

**Issue by hojati** [getpelican/pelican-plugins#1285]
In Windows, output_path is calculated wrong when 
THUMBNAIL_KEEP_NAME = False

I think in function `get_thumbnail_name`, a condition should be added for filename start with '\\', there is actually '/' for Linux guess so.

please check.
thanks

**Comment by kdeldycke** [comment]
For the record, the canonical `thumbnailer` plugin has been moved to its own repository at: https://github.com/pelican-plugins/thumbnailer.

I guess this issue can be either closed or moved to https://github.com/pelican-plugins/thumbnailer/issues.

**Comment by justinmayer** [comment]
Many thanks for helping clean up these issues, Kevin. 💯

If anyone would like to submit a PR to fix this issue, please do so at the repository noted above.
