### ISSUE TITLE
[neighbors] Migration out of mono-repo

### ISSUE THREAD

**Issue by kdeldycke** [getpelican/pelican-plugins#1287]
I'd like to get the `neighbors` plugin moved from this mono-repo (https://github.com/getpelican/pelican-plugins/tree/master/neighbors) to its own under the umbrella of the https://github.com/pelican-plugins organization.

I'm an experienced Python packager (best example is my [`meta-package-manager` project](https://github.com/kdeldycke/meta-package-manager)) and can help a lot performing that migration. How would you like to proceed?

I just noticed that plugin has already been pushed to PyPi by @cprieto at: https://pypi.org/project/pelican-neighbors/ . I guess I need to contact him and try to get access to that project so I can consolidate all code bases.

**Comment by cprieto** [comment]
Hi @kdeldycke I don't understand what do you need from me. I will be happy if this move is done anyway, I really dislike having all the plugins in the same repository (it is a nightmare to maintain anything).

**Comment by justinmayer** [comment]
Hi Cristian. I totally agree, which is why we've moving plugins to their own repositories. In this case, the easiest path forward would be if you could add the following PyPI accounts as "Owners" to the `pelican-neighbors` package:

* `pelicanteam`
* `jmayer`

That way, once the plugin has been migrated to its own repository under the new org, the package can be published automatically via [AutoPub](https://justinmayer.com/projects/autopub/) upon pull request merge.

Would you please let me know once that's done so we can proceed to the next step?

**Comment by cprieto** [comment]
Done, I think I already own `pelican-series` as well, tell me if you need me to do the same with that one.

**Comment by justinmayer** [comment]
@cprieto: That would be great! Would you please do the same for that one as well? 😄

**Comment by kdeldycke** [comment]
Thanks @cprieto for the fast reply! With the release of Plumage 4.5, we now have a generic way to gather plugin installed independently as packages. This whole `pelican-plugins` mono-repo is now deprecated and the maintainers called upon the community to start moving all plugins to their own independent packages.

This is fantastic news as we will now be able to solve the nightmare of maintaining plugins as you mentioned, at last! 😃 The plan is detailed here: https://github.com/getpelican/pelican-plugins#pelican-plugins . Of course this will takes time.

But I want to help and starts with the `neighbors` plugin. And to distribute the package on PyPi, we need to get the appropriate access rights the https://pypi.org/project/pelican-neighbors/ . Unfortunately you are the only owner of that project on PyPi.

As @justinmayer just proposed, can you add more `Owners` on https://pypi.org/manage/project/pelican-neighbors/collaboration/ please? So we can start working on the migration? 🙂

**Comment by justinmayer** [comment]
@kdeldycke: Thank you for offering to help with the Neighbors plugin. Much appreciated! I'll create a new repository for the to-be-migrated plugin and send you an invitation to it. 🚀

**Comment by cprieto** [comment]
Done. Both repos have both users as owners, if I can help with anything else just ping me, a pleasure to be helpful :)

**Comment by justinmayer** [comment]
@cprieto: Very helpful, indeed. Much appreciated! 😁 

@kdeldycke: I'm working on a draft migration guide. I'll follow up tomorrow with more info!

**Comment by justinmayer** [comment]
@kdeldycke: I created the new repository, invited you to collaborate on it, and created an issue there (see above) to track migration of the Neighbors plugin. Let's continue this discussion over on that issue. Thanks again for offering to help out with this! 💯

**Comment by kdeldycke** [comment]
Thanks to your ownership transfer @cprieto, we were able to cut a release of `pelican-neighbors` v1.1.0 on PyPi: https://pypi.org/project/pelican-neighbors/1.1.0/ . Thanks again @cprieto ! 😃
