### ISSUE TITLE
Migration of a new and improved pandoc_reader plugin

### ISSUE THREAD

**Issue by nandac** [getpelican/pelican-plugins#1303]
Dear Folks,

I have written an improved Pandoc Reader plugin based on https://github.com/liob/pandoc_reader.

As the original plugin is not under active development I wish to contribute my version of the plugin at https://github.com/nandac/pandoc-reader to the new plugin repository you have created for Pelican Plugins.

I have made sure that it conforms to Python standards and brought in under the new format as described [here](https://github.com/getpelican/cookiecutter-pelican-plugin).

I welcome any additional feedback you may have.

I look forward to your reply.

**Comment by nandac** [comment]
Hi could I please get some response on this or feedback on what steps I should take to get my plugin accepted?

**Comment by nandac** [comment]
@kdeldycke 

Thanks for the update.

I have added more features and tests since I wrote the original message above and used the cookie-cutter recommended to restructure the project.

So far my tests give about 95% coverage of the code so I am fairly certain that the plugin works. However, I have not tested it with Pelican on a website which will be the next step for me.

Would you be confident with guiding me through the process of releasing this plugin or at least give me some feedback for improvement? Write now the plugin is set to Alpha but I would like to move it to Beta and a proper release.

For your convenience here is the [github repo](https://github.com/nandac/pandoc-reader).

cc @justinmayer

**Comment by kdeldycke** [comment]
Unfortunately I do not have enough permissions to temporarily grant you the rights to transfer your plugin under the umbrella [`pelican-plugins`](https://github.com/pelican-plugins) organization. We need help from the organization's owner, either @justinmayer or @avaris.

**Comment by justinmayer** [comment]
Hi @nandac. I responded via IRC but suspect you were no longer connected at the time. I have contacted the original plugin author in hopes of transferring the original repository to the new organization. If that doesn't happen by, say, November 1, I will create a new repository under the [Pelican Plugins organization](https://github.com/pelican-plugins), where we can begin the process of integrating your work. Many thanks for all your efforts to update this plugin! ✨

**Comment by nandac** [comment]
Thanks @justinmayer for getting back to me. Let us see if the original plugin author responds.

Many thanks,
Nanda

**Comment by nandac** [comment]
As an update since my last comment, I have tested out my plugin code on the website I am developing, and the expected HTML is generated through the plugin so it works.

**Comment by nandac** [comment]
@justinmayer I see that you have created a new repository for this plugin in the new organization. Kindly let me know what I need to do on my end to migrate the plugin over.

Since my repository is a fork of another repository does this pose any challenges?

As we have not received any word from the original plugin author I believe we can go ahead.

Many thanks,
Nanda

**Comment by kdeldycke** [comment]
I guess this issue can now be closed since the plugin has now been migrated to: https://github.com/pelican-plugins/pandoc-reader :)

**Comment by kdeldycke** [comment]
Same thing here @justinmayer: we can close this now! 😄

**Comment by justinmayer** [comment]
Many thanks to @nandac for taking the initiative to update this plugin, and thanks to @kdeldycke for the assistance! 🥇
