### ISSUE TITLE
liquid_tags plugin migration

### ISSUE THREAD

**Issue by mirekdlugosz** [getpelican/pelican-plugins#1305]
Using instructions from drafted blog post, I managed to port `liquid_tags` plugin to namespaced structure.
I keep results of my work on my Github account, in `migration` branch: https://github.com/mirekdlugosz/pelican-plugins-liquid-tags/tree/migrate

* I have not yet run code styling tools on this repo.
* Some tests related to file inclusion fail, but they also fail on legacy plugin repository
* Speaking of tests, they probably should be moved to top-level tests directory

Personally, I don't really have use for this plugin, except that I have custom liquid tag that I use in few of my posts. I did initial porting work to port my site to namespaced plugins, but I will gladly let someone else finish this work.

**Comment by kdeldycke** [comment]
Thanks @mirekdlugosz for initiating the work! `liquid_tags` is indeed a popular Pelican plugin judging by its commit history and number of open issues and PRs.

I just created an empty repository at https://github.com/pelican-plugins/liquid-tags . Can you create a PR over there so we can discuss and progress on the migration?

**Comment by kdeldycke** [comment]
@mirekdlugosz, to make you productive, I added your user as a maintainer to the newly created repository.

@justinmayer, I added you as an admin to fix any issue if I made a mistake! 😅

**Comment by justinmayer** [comment]
Thanks, Kevin. For future reference… If I understand correctly how GitHub's access controls work (and it's quite possible I don't), there shouldn't be any need to explicitly add add access to an individual repository for me, you, or any other member of the Pelican Plugins organization. That access is implicit by said org membership, so explicit per-repo access for members would only make sense if it were overriding the access level provided at the org level.

**Comment by kdeldycke** [comment]
@justinmayer oh. Better safe than sorry then! 😁

But yes, you're right, manually adding these roles is unnecessary: everything is already open enough for contributions and the important roles are setup at the organization levels. I'll clean things up.

**Comment by mirekdlugosz** [comment]
Hey @kdeldycke 

> I just created an empty repository at https://github.com/pelican-plugins/liquid-tags . Can you create a PR over there so we can discuss and progress on the migration?

Looks like I can't :( . When I click "New pull request" button, it navigates to https://github.com/pelican-plugins/liquid-tags/compare which displays "This repository is empty" message.

My guess is that since there is no commit or branch in repo, there is nothing I could compare my branch against, so entire UI refuses to load.

I think you could create new (empty) commit and push it, and then I would try to submit PR. Or you could pull in my "migrate" branch from https://github.com/mirekdlugosz/pelican-plugins-liquid-tags and push it to "migrate" branch of https://github.com/pelican-plugins/liquid-tags

**Comment by kdeldycke** [comment]
Oh I see. In that particular case you need some special rights. I just gave you admin rights on https://github.com/pelican-plugins/liquid-tags so you can properly initialize the repository.

You should receive an invitation by mail.

**Comment by mirekdlugosz** [comment]
Got it. Thanks.

I pushed two branches - `main` with empty initial commit and `migrate` with subset of monolithic plugins repo history, + filesystem conversion commit.

How would you envision further work on plugin? Which parts would you like to handle, and which would you like me to handle?

I took the liberty to edit list in https://github.com/pelican-plugins/liquid-tags/issues/1 , adding few more things we should do before 1.0 release. I'm not familiar with plugin internals, but I will have some spare time in next few days, so I can try looking into e.g. tests failures.

**Comment by kdeldycke** [comment]
I'm just a facilitator in the whole migration plan! 😄

I just happened to have been granted by @justinmayer  some admin rights on `pelican-plugins` organization a while ago. So I'm using this privilege to help others get up to speed in the migration of their own favorite plugins.

I'm not using `liquid-tags` and do not plan to use it in the future. So I do not have any incentive to contribute to it.

So I propose to let you keep the admin permission on the `liquid-tags` repository so you'll be free to package and maintain it.

No worries about pelican-plugins/liquid-tags#1 edits, and thanks to keep track of the progress! 👍 The next step is to open-up a new PR that is merging your `migrate` branch to `main`. And feel free to push things forward and fix unit-tests!

**Comment by kdeldycke** [comment]
`liquid_tags` plugin has been migrated at: https://github.com/pelican-plugins/liquid-tags . We can now close this issue.

**Comment by justinmayer** [comment]
Many thanks to @mirekdlugosz and @kdeldycke for the help migrating this plugin. 🎉
