### ISSUE TITLE
[Migration] of webassets plugin out of the monorepo

### ISSUE THREAD

**Issue by kdeldycke** [getpelican/pelican-plugins#1308]
I just has a private discussion with @bryanbrattlof, maintainer of [`pelican-webassets` plugin](https://git.bryanbrattlof.com/pelican-webassets), that was [published on PyPi](https://pypi.org/project/pelican-webassets/).

He's ready to help us merge our collective efforts to maintain that plugin.

The plan:
* [x] Create a new `webassets` repository under the [`pelican-plugins` umbrella organization](https://github.com/pelican-plugins) => see: https://github.com/pelican-plugins/webassets
* [x] Move the `assets` plugin and its whole history there
* [x] Add Bryan as maintainer of that repo
* [x] Collectively work out a new release to make sure everything's OK

In the mean time, Bryan, you can add the [`pelicanteam` user on PyPi](https://pypi.org/user/pelicanteam/) as owner of your package so we can automate the release process even more.

As I'm no official maintainer, I need @justinmayer here to evaluate my proposal.

**Comment by kdeldycke** [comment]
Oh, and something important I forgot to address: there is another `webassets`-based plugin in the monorepo named [`assets`](https://github.com/getpelican/pelican-plugins/tree/master/assets). But it seems this version never was published on PyPi and needs to be repackaged along new Pelican plugin standards.

How should we merge and deduplicate our efforts? How similar or different are these two plugins?


@kernc, you seems to be the last one with a commit on `assets`. Did you looked closely at the code? Do you have an idea 
how the two plugins relates?

**Comment by avaris** [comment]
Based on the code, they look pretty much identical.

**Comment by kdeldycke** [comment]
Thanks @avaris for the feedback. I just realised you were the original author of the [`assets`](https://github.com/getpelican/pelican-plugins/tree/master/assets) plugin. Given its more ancient history, I propose to use it as a base to migrate, then apply @bryanbrattlof's changes on top of it. What do you think?

**Comment by bryanbrattlof** [comment]
Hi @kdeldycke! My version of the project was based off of @avaris's work from years ago. They are basically identical apart from the config variable changes to align more with the `pip` package name, adding few other `logging` statements, and a great many spelling mistakes.

I'm totally on-board with using @avaris's original work and cherry-picking any changes from my version if they're needed.

**Comment by avaris** [comment]
Just to clarify, I am not the original author. However, I was the one that split the plugin from `pelican` core and moved into this separate repository. Since my git-fu wasn't as good at the time, all the history before that ended up stripped here (😦) and I appear to be the first committer.

As for the migration, starting from the version here and adding on top of it would be better I suppose. This one has more of the history.

**Comment by kdeldycke** [comment]
Thanks @avaris and @bryanbrattlof. I'll start moving out the plugin code to its own repository and merge the two version.

**Comment by kdeldycke** [comment]
Work started here: https://github.com/pelican-plugins/webassets/pull/1

**Comment by kdeldycke** [comment]
I just realized something:
* Pelican's legacy `assets` plugin is under an AGPL-3.0 licence
* @bryanbrattlof 's `pelican-webassets` plugin is under MIT

Can I merge the two given the differences?

**Comment by bryanbrattlof** [comment]
Whoops, I never paid much attention to the license. If it help I'm happy to migrate to AGPL-3.0.

Looking at the diffs between the two, it should be easier for me to migrate.

**Comment by kdeldycke** [comment]
> Whoops, I never paid much attention to the license. If it helps I'm happy to migrate to AGPL-3.0.

OK, I'll take that as authorization to re-license your work under AGPL-3.0 which allows for a merge! :) Thanks @bryanbrattlof for your flexibility! :)

**Comment by kdeldycke** [comment]
Plugin has been successfully migrated, all development activity is now happening at https://github.com/pelican-plugins/webassets .
