### ISSUE TITLE
[migration] tag_cloud

### ISSUE THREAD

**Issue by marius-mather** [getpelican/pelican-plugins#1326]
I'm not the original author but I'd like to help migrate the `tag_cloud` plugin as I use it for an internal team blog. I've set up a new repo for it based on the cookiecutter at https://github.com/marius-mather/tag_cloud. So far I've done some basic reformatting and all the existing tests are passing. I'll also try to update the README with usage instructions.

Let me know if there's anything further I need to do to get this happening.

**Comment by justinmayer** [comment]
Many thanks for reaching out, @marius-mather! I must apologize for the hard-to-find documentation regarding how to properly migrate a plugin from the legacy monolithic repository to its eventual new home under the [Pelican Plugins](https://github.com/pelican-plugins) organization. There was a long-standing draft guide available, which I have finally published in a more public place: https://blog.getpelican.com/namespace-plugin-migration.html

There is a rather-specific process that I prefer that we follow when migrating plugins from the legacy repository, as you can see from the guide linked above. As a result, I’m not sure how to best utilize the changes you made in your personal repository. So I took the liberty of following the aforementioned guide and pushing the resulting `migrate` branch to the plugin’s new home: https://github.com/pelican-plugins/tag-cloud/pull/2

(I also took the liberty of inviting you as a collaborator on that repository. Please let me know if that invitation has not arrived.)

Would you please take a moment to review the pull request targeting the new `migrate` branch and let me know your thoughts? Assuming there’s nothing too problematic with that PR, we can merge it, after which you can submit any follow-up changes in the form of subsequent pull requests to the new repository.

Once again, please accept my most sincere apologies for the duplicative effort, which is entirely my fault. I look forward to collaborating with you over at the new repository! 😸

**Comment by marius-mather** [comment]
Thanks for getting this migrated, apologies that I didn't get around to reviewing it sooner.

I've just updated my team blog with the new plugin and everything seems to be working well, I'm fully switched over to the new plugin system now.
