### ISSUE TITLE
[clean_summary] Migrate and enhance or include in Core?

### ISSUE THREAD

**Issue by wombelix** [getpelican/pelican-plugins#1330]
Hi,

my use case is to remove various HTML tags like img or h1/h2 from the summary.
Plugin [clean_summary](https://github.com/getpelican/pelican-plugins/tree/master/clean_summary) can remove img tags already, so what's the better approach:

1. Migrate clean_summary to the new Plugin Organization and enhance it to remove other tags too?
2. Add the Functionality to the Pelican Core directly due to the fact that it's not a complex feature?

Personally I would choose Option 1, in both cases i'm happy to take care and work on the appropriate PR, just thought i ask which way to go before I start.

Cheers
Dominik

**Comment by avaris** [comment]
Definitely 1 :).

**Comment by wombelix** [comment]
Thank you, then 1 it is :)
