### ISSUE TITLE
Static Comments Configuration

### ISSUE THREAD

**Issue by mpaglia0** [getpelican/pelican-plugins#1332]
I need more info about the plugin configuration but the link <https://gitorious.org/hacheblog> is broken.

**Comment by justinmayer** [comment]
Ciao Maurizio. When filing issues, would you please include a lot more details? It's not clear (at all) what you are talking about here. Could you elaborate?

**Comment by justinmayer** [comment]
As far as I can tell, all the information required is already in the Static Comments plugin's README. I do not believe you need to access the link you mentioned, which is indeed quite irreparably dead.

I just tested the plugin by following the instructions in the README, and everything functioned precisely as described there.

As is noted in the [How to Get Help](https://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the documentation, it is extremely difficult to help you if you don't provide more information (such as the contents of your settings file, template changes, etc.) via a link to a paste service.

Also, in the future, please consider reaching out via the [Pelican IRC channel](https://docs.getpelican.com/en/stable/contribute.html#the-pelican-irc-channel). I get the impression that you would benefit from a more interactive conversation. 😊

**Comment by mpaglia0** [comment]
Thank you indeed.
Please apologize again for my ignorance. :-(

**Comment by justinmayer** [comment]
No problem, Maurizio. We really do want to help you — truly — so if you include the relevant information, I'm sure we can get everything working for you. 😁
