### ISSUE TITLE
[asciidoc_reader]: Empty `article.content` when `source_path` contains spaces

### ISSUE THREAD

**Issue by devidwolf** [getpelican/pelican-plugins#1336]
When article asciidoc-files are located in a path which contains spaces, the commands built in the `read` method of the `AsciiDocReader` class are interpreted incorrectly because of the whitespaces. Wrapping the `source_path` into quotation marks would fix that:

```py
# Line 46
content = call("%s %s -o - %s" % (cmd, options, source_path))
# to
content = call("%s %s -o - '%s'" % (cmd, options, source_path))

# Line 50
content = call("%s %s -o %s %s" % (cmd, options, temp_name, source_path))
# to
content = call("%s %s -o %s '%s'" % (cmd, options, temp_name, source_path))
```

**Comment by justinmayer** [comment]
@devidwolf: Thanks for reporting this issue and suggesting a fix. Changed via 495ac6b. Please let us know if that doesn't address the problem! 💫

**Comment by podsvirov** [comment]
Hi @justinmayer, my `source_path` don't contain spaces but I get empty `article.content` after 495ac6b.

I'm trying `\"%s\"` instead and that produse good content for me.

Please review #1337.

**Comment by justinmayer** [comment]
@podsvirov: I merged the adjusted version from your PR. Many thanks! 😊
