### ISSUE TITLE
[new plugin request] pelican-yaml-metadata

### ISSUE THREAD

**Issue by pR0Ps** [getpelican/pelican-plugins#1340]
Link: https://github.com/pR0Ps/pelican-yaml-metadata

This plugin allows for markdown files to define metadata using a YAML block like Jekyll or Hugo allow (example in the repo). If no YAML block is defined, it falls back to the normal markdown metadata parsing making it fully backwards compatible with normal markdown files.

The plugin also conforms to the new pip-installable "namespace plugin" format introduced in Pelican 4.5.

**Comment by pR0Ps** [comment]
Any updates on this?

**Comment by justinmayer** [comment]
Hey Carey. I'm very sorry for the delay. I'm occupied for the next couple of weeks, but I have set a reminder to get this set up. Thank you for your patience! 😅

**Comment by justinmayer** [comment]
@pR0Ps: I started the migration endeavor in the Pelican Plugins organization, including a `migrate` branch, and I sent you an invitation to join as a maintainer: https://github.com/pelican-plugins/yaml-metadata

We can use the `migrate` branch to collaborate on some follow-up commits, adding some new tooling from the [Pelican Plugin CookieCutter Template](https://github.com/getpelican/cookiecutter-pelican-plugin), setting up automatic PyPI package publication via [AutoPub](https://justinmayer.com/projects/autopub/), etc.

**Comment by pR0Ps** [comment]
Sounds good, I joined the repo and opened a PR to merge `migrate` into `main` where we can go over the stuff you want to follow up on
