### ISSUE TITLE
[New Plugin] Theme Config

### ISSUE THREAD

**Issue by galaxy4public** [getpelican/pelican-plugins#1348]
An year ago I submitted a PR to merge my plug-in for providing hooks into Pelican to themes (#1256), but since then a new organisation was provisioned for plug-ins.  Therefore, I updated the repository (https://github.com/openwall-com-au/theme-config) to be aligned with what is expected by the new structure (was using the Simple Footnotes plug-in as a guidance for the alignment).

Could somebody assist me with moving my plug-in under the new structure, please?

**Comment by justinmayer** [comment]
Thanks for your patience, @galaxy4public. I will follow up with you as soon as I possibly can!

**Comment by galaxy4public** [comment]
@justinmayer, ping? :)

**Comment by galaxy4public** [comment]
@justinmayer,  another year has passed, can we add it to the list please? :)  The plugin enables a really flexible way for a theme to specify the dependencies it needs without touching the primary config and I think it would be very useful for theme creators.

**Comment by galaxy4public** [comment]
@justinmayer , a polite ping :)  Is every plugin to Pelican has a wait period of 2.5 years?!

**Comment by justinmayer** [comment]
Hey @galaxy4public. I have indeed seen your comments and apologize for the long delay. I am working on this now and will be in touch again shortly.

**Comment by justinmayer** [comment]
@galaxy4public: I created the repository, added the plugin commits, and sent you an invitation to the repository. Let's move follow-up discussion to issues/PRs in the new repo.

**Comment by justinmayer** [comment]
Side note… While it should eventually get cleaned up and linked somewhere from within the Pelican documentation, the process for adding new plugins is on the Pelican site: https://getpelican.com/blog/namespace-plugin-migration/
