### ISSUE TITLE
[Migration] i18n_subsites

### ISSUE THREAD

**Issue by adiroiban** [getpelican/pelican-plugins#1349]
It would be nice to have the [i18n_subsites](https://github.com/getpelican/pelican-plugins/tree/master/i18n_subsites) plugin move it's own repo.

I can help with the migration.

When doing the migration please also consider moving the [issues](https://github.com/getpelican/pelican-plugins/issues?q=is%3Aissue+is%3Aopen+i18n).

Not sure what to do with the existing [pull requests](https://github.com/getpelican/pelican-plugins/pulls?q=is%3Apr+is%3Aopen+i18n) 

I some PR for i18n are great contribution, yet they were not approved (since 2017)[https://github.com/getpelican/pelican-plugins/pull/841]

Thanks!

**Comment by georgkrause** [comment]
I'd like to get involved here, too. How can I help?

**Comment by haplo** [comment]
I use the i18n_subsites plugin for my blog and would like to help with the migration. Can anybody chime in about what work needs to be done? @justinmayer?

**Comment by georgkrause** [comment]
Its all documented here: https://blog.getpelican.com/namespace-plugin-migration.html

**Comment by haplo** [comment]
Thank you @georgkrause. So from https://blog.getpelican.com/namespace-plugin-migration.html it looks like we stand at the very beginning:

> Migration from Monolithic Repository
> 
> Create an issue at the [legacy monolithic Pelican Plugins repository](https://github.com/getpelican/pelican-plugins) and **ask a maintainer to create a corresponding new repository under the new [Pelican Plugins organization](https://github.com/pelican-plugins)** and invite you to join it.

If one of the maintainers could create a reop for `i18n_subsites` under the pelican-plugins organization then we could get started. Until then I think I'm going to downgrade my Pelican version.

**Comment by justinmayer** [comment]
I am swamped at the moment but will endeavor to kick-start the migration process sometime this month. Thanks to everyone for their patience and understanding!

**Comment by avaris** [comment]
> Until then I think I'm going to downgrade my Pelican version.

But why? `pelican` is keeping backwards compatibility with old style plugins for a while.

**Comment by haplo** [comment]
> I am swamped at the moment but will endeavor to kick-start the migration process sometime this month. Thanks to everyone for their patience and understanding!

Thank you for getting back to us @justinmayer, just let us know when it is ready.

> > Until then I think I'm going to downgrade my Pelican version.
> 
> But why? `pelican` is keeping backwards compatibility with old style plugins for a while.

Upgrading pelican broke my site so I assumed that was the issue, but maybe it's something else. I will debug it, thank you for the heads up @avaris.

**Comment by georgkrause** [comment]
I filtered the subdirectory in its own repository: https://github.com/georgkrause/i18n_subsites

I am willing to transfer the project, just let me know!

**Comment by georgkrause** [comment]
As far as I can tell there are 6 open merge requests regarding i18n_subsites, I will try to review them in the next days and merge them into my fork.

**Comment by adiroiban** [comment]
@georgkrause thanks. feel free to ping me if you need any help with testing.  I don't have much free time, and I might already used a very customized pelican to get my i18n site working, but I will try to help.

**Comment by georgkrause** [comment]
@adiroiban Jeah for me its almost the same, which is why I want to cleanup the situation. I cannot stand pulling a huge set of submodules and patching them to make it work any longer. It would be nice if you would use my fork as well, what needs to be merged to make this possible for you? So I can start with reviewing this first.

**Comment by georgkrause** [comment]
Do I get this right? This is a dump of what you have running in production? This helps a lot, lets integrate this :)

**Comment by adiroiban** [comment]
I think there are 2 main changes in my fork.

First is this change for which I have already created a PR https://github.com/getpelican/pelican-plugins/pull/1350

The second one, is support for gettext inside the main SITE dict... but maybe I am wrong and this is already standard functionality.

```
SITE = {
    'author': _('A Team'),
    'title': _('Delivering great result each time.'),
    'description': _(
        'The A Team works all day and all night long for nothing.'
    ),
}
```

**Comment by rschiang** [comment]
@adiroiban @georgkrause @haplo
So I happened to merge some of the more uncontroversial PRs (#1299, #1347, #1350), cleaned up and migrated the whole repo, and published a pre-alpha package on PyPI:

<https://pypi.org/project/pelican-i18n-subsites>

The project currently sits [here](https://github.com/rschiang/pelican-i18n-subsites). Could you help verify if it works as expected, so we can ask @justinmayer to move it into @pelican-plugins and make us maintainers? 👀

**Comment by adiroiban** [comment]
Hi. Sorry for the delay.
I don't have time  now to look into this... I did the website changes a long time ago as an experiment.

At work, we don't yet have a multi-lingual website, it was more of an experiment,

Once this goes into production I will check your repo. I started it and I hope I will not forget about it :)

Thanks for putting this all together.

**Comment by adiroiban** [comment]
Let me close this as all work should be done in the separate repo.

**Comment by rschiang** [comment]
News update: the Pelican team has set up a new repo! Please follow pelican-plugins/i18n-subsites#2 for the upcoming migration.

**Comment by justinmayer** [comment]
[I18N Subsites 1.0.0 released](https://github.com/pelican-plugins/i18n-subsites/releases/tag/1.0.0) and [published to PyPI](https://pypi.org/project/pelican-i18n-subsites/#history) 🎉 

Sincere apologies for the long delay, and many thanks to everyone here who put effort into this and/or waited patiently for me to help get the plugin into its own repository under the Pelican Plugins org 😅
