### ISSUE TITLE
[New Plugin] Pelican-Injector: A plugin to inject code into specific HTML tags in pages and articles

### ISSUE THREAD

**Issue by buanzo** [getpelican/pelican-plugins#1389]
I would like to propose a new plugin: Pelican-Injector.

**Functionality:**
Pelican-Injector is designed to allow users to inject custom code (like scripts or styles) into specific HTML tags of their Pelican-generated pages and articles. This plugin can be beneficial for users who need to customize their HTML output further, such as injecting analytics scripts or additional styles.

The plugin makes use of the 'article_generator_write_article' and 'page_generator_write_page' signals to insert the specified code into the final HTML of each page and article.

Users can specify the tag into which the code should be injected, the code to inject, and whether to inject before or after the specified tag, through settings in their Pelican configuration file. They can also control whether injection should occur in pages, articles, or both.

**Sample Configuration:**

```python
INJECTOR_CONFIG = [
    ('head', '<script>console.log("Hello, world!");</script>'),
    ('body', '<style>.custom-style { color: red; }</style>', 'before'),
]
INJECT_INTO_PAGES = True
INJECT_INTO_ARTICLES = False
```

In the given configuration example, a script logging "Hello, world!" to the console is injected into the <head> tag of each page, and a style block is injected before the <body> tag. It could also be used to easily add Google Analytics scripts, without having to use a theme designed for such a use case.

I believe this plugin would be a valuable addition to the Pelican ecosystem and look forward to feedback and suggestions.

You can find the plugin here: [Pelican-Injector](https://github.com/buanzo/pelican-injector)

**Comment by justinmayer** [comment]
Hi Arturo. Thank you for reaching out. As of a few years ago, we have been encouraging folks to host repositories under the new [Pelican Plugins](https://github.com/pelican-plugins) organization. This serves to increase visibility as well as facilitate collaboration between Pelican maintainers and plugin authors such as yourself. The end result is a more vibrant and well-maintained plugin ecosystem for Pelican users.

What do you think? Would you be amenable to having the Injector plugin located under the [Pelican Plugins](https://github.com/pelican-plugins) organization?

**Comment by buanzo** [comment]
Hi Justin! Absolutely. In fact, I thought I was opening the issue in the
right place to do just that.

I will follow your indications. Thank you!

PS: I am thrilled to contribute to Pelican.

**Comment by buanzo** [comment]
Let me know if there's anything I must do.

**Comment by justinmayer** [comment]
Hi Arturo. You did indeed open the issue in the right place. I just wanted to make sure we were on the same page. Seems like we are! 😁 

I took the liberty of creating the new plugin repository and importing your commits. Then I migrated the plugin structure to the namespace format so it can be Pip-installed, as well as a number of other changes that I think would be beneficial to the project.

Let's move this discussion to the new repo. Would you please take a look and post any comments as a review on this pull request? https://github.com/pelican-plugins/injector/pull/1
