### ISSUE TITLE
For requirements.txt, use PDM, PIP, Conda or pipreqs?

### ISSUE THREAD

**Issue by egberts** [getpelican/pelican-plugins#1404]
For the Pelican plugins, which way are we creating the proverbial "requirements.txt" file.   

I ask this because some package have a requirements subdirectory (like Pelican's `tox`) and most others do file-based requirements.txt (like `pdm`).

As a plugin repository and for all plugin, consistency is the key, no?

I have no skin in this game, other than "build consistency".

So, which tools should plugins be using?

* `pip3 freeze > requirements.txt`
* `pdm export -f requirements.txt`
* `conda list -e > requirements.txt`
* `pipreqs --print > requirements.txt`

References
=========

* [Requirements.txt file format](https://pip.pypa.io/en/latest/reference/requirements-file-format/#requirements-file-format)
* [Automatically create file requirements](https://stackoverflow.com/questions/31684375/automatically-create-file-requirements-txt)

**Comment by justinmayer** [comment]
Hi Egbert. I have very limited time and thus must respond to this (and other issues) in the most brief and efficient manner possible. Apologies in advance for anything that may sound brusque! 😊 

**Short version**: I prefer to define dependencies in `pyproject.toml` and do not see the need for any `requirements.txt` files.

**Longer version**, in no particular order, in bullet-point format for expedience…

- For what explicit purpose(s) are we talking about generating `requirements.txt` files? The linked issue above relates to generating `requirements.txt` files for Pelican-generated _sites_ — not plugins, which seems to be the genesis for this issue.
- As already stated in the README, this repository is in a transitional state, on its way toward being archived, in favor of migrating plugins to their own individual repositories under the [Pelican Plugins organization](https://github.com/pelican-plugins). As such, it's not particularly important to me to maintain consistency in this legacy repository.
- I get the impression some folks have a general idea that all projects should have a `requirements.txt` file. Given that I prefer to define dependencies in `pyproject.toml`, I do not understand why `requirements.txt` files would be warranted. As noted in the linked issue above, folks who want or need requirements can generate such files themselves.
- The article you linked to in another discussion even says: “Avoid using Pip commands to install packages into virtual environments. If you use PDM or Hatch, they manage packages in development and test environments.” That article seems to only recommend `requirements.txt` files for situations in which tools like PDM are _not_ used.
- We already have a canonical repository that generates scaffolded plugins, which also serves as a sort-of “best practices” resource for plugin development: https://github.com/getpelican/cookiecutter-pelican-plugin

**Comment by egberts** [comment]
Thank you for taking the time to given the detailed inputs. 

I sufficiently have been shown the wisdom of Pelican. 

Closing this issue.
