### ISSUE TITLE
"Read more" plugin

### ISSUE THREAD

**Issue by hrw** [getpelican/pelican-plugins#1406]
Finally found time and sorted out creation of plugin in a bit more proper way.

# What is it?

My blog was WordPress based for many years. One of functionalities I used was ability to split post into 'entry' and 'rest' by adding "" into content.

This plugin adds such functionality into Pelican.

Git repo: https://github.com/hrw/pelican-plugin-read-more

Everything is hardcoded as there were no other users.

**Comment by wombelix** [comment]
The `read-more` plugin was moved three years ago into the new `pelican-plugins` org: https://github.com/pelican-plugins/read-more
I'm curious if there was a reason why you not contributed to it and created a separate version instead?

**Comment by hrw** [comment]
O, nice. Will have to look.

My version is about 4 years old and I decided to finally take care after having to handle another Python upgrade.

**Comment by wombelix** [comment]
Good example? Idk but yes I use it ;) 
https://git.sr.ht/~wombelix/dominik-wombacher-cc/tree/main/item/pelicanconf.py#L96

**Comment by hrw** [comment]
Ok, will create a new name one day and create a new issue.

Those are two totally different plugins.

https://marcin.juszkiewicz.com.pl/ shows how it works.

**Comment by justinmayer** [comment]
Hi Marcin. Thank you for reaching out. As the primary maintainer of Pelican, I try to encourage collaboration and consolidation as much as possible, in an effort to minimize fragmentation and duplication of effort.

To that end, if I may propose a suggestion, would you consider submitting your enhancements as a pull request to the existing [Read More](https://github.com/pelican-plugins/read-more) plugin or the [Summary](https://github.com/mirekdlugosz/pelican-plugins-summary/tree/migrate) (https://github.com/getpelican/pelican-plugins/issues/1304) plugin? I realize that your plugin may behave in a different manner, but we can allow for that via configuration settings, and the Pelican community usually benefits when we can jointly collaborate on a focused number of projects. What do you think?

**Comment by hrw** [comment]
Summary one looks like extended version of what I wrote. Will take a look.
