### ISSUE TITLE
[i18n_subsites] STATIC_PATHS copied multiple times

### ISSUE THREAD

**Issue by Scheirle** [getpelican/pelican-plugins#180]
All files and folders in the STATIC_PATHS variable are copied in each subsite.

This is a huge problem if you have large files in it.

It would be better to just copy it once, but therefore correct the links in the subsites.

**Comment by shaief** [comment]
Hi, i wondered what is the state of this issue? trying to one site with two languages i get my theme, statics and images created twice. Any way to have a single copy (it's quite heavy). Thanks!
