### ISSUE TITLE
liquid_tags: No syntax highlighting with IPython 2.0

### ISSUE THREAD

**Issue by joergdietrich** [getpelican/pelican-plugins#201]
Following the PR #175 I upgraded to IPython 2.0. My Python code cells have no syntax highlighting anymore (on current pelican-plugins master, pelican 3.3.0. jinja2 2.7.2). Downgrading to IPython 1.2.1 brings the syntax highlighting back.

**Comment by justinmayer** [comment]
@joergdietrich / @ischurov: Any chance you'd like to test Alexandre's latest version in #543 and let us know how it works for you?

**Comment by joergdietrich** [comment]
It's working again, thanks! The exception, however, is IPython >=3 in collapsible input cells. See PR #676
