### ISSUE TITLE
Images not correctly linked when using summary plugin

### ISSUE THREAD

**Issue by carsonfarmer** [getpelican/pelican-plugins#23]
Using the reference-style image format (Markdown) with the summary plugin causes problems in linking to images in articles. If the image is found before the SUMMARY_END_MARKER, but the image information is found afterwards, the link is broken:

Example (^^ added because code wasn't rendering properly):

``` markdown
[![image][]][postcards]
Here is some text...

<!--SUMMARY_END_MARKER-->
Some more text...

^^[image]: |filename|/images/postcards-300x135.png
^^[postcards]: |filename|/images/postcards.png
```

**Comment by kernc** [comment]
Moderately related to https://github.com/getpelican/pelican/pull/1342

**Comment by justinmayer** [comment]
Not sure if this is still a problem. If so, please feel free to comment here so the issue can be re-opened.
