### ISSUE TITLE
tipu_search: Error if TEMPLATE_PAGES=None

### ISSUE THREAD

**Issue by seisman** [getpelican/pelican-plugins#232]
Default value of `TEMPLATE_PAGES` is None:

```
self.tpages = settings.get('TEMPLATE_PAGES')

for srclink in self.tpages:
    self.create_tpage_node(srclink)
```

 iteration over `self.tpages` with `None` value will cause an error `CRITICAL: 'NoneType' object is not iterable`

**Comment by justinmayer** [comment]
Not sure if this is still a problem. If so, please feel free to comment here so the issue can be re-opened.
