### ISSUE TITLE
Pelican 3.4 subcategory plugin usage needs updating

### ISSUE THREAD

**Issue by hyperking** [getpelican/pelican-plugins#239]
https://github.com/getpelican/pelican-plugins/tree/master/subcategory

the settings for subcategory plugins should be

'SUBCATEGORY_SAVE_AS' = os.path.join('subcategory', '{savepath}.html')
'SUBCATEGORY_URL' = 'subcategory/{fullurl}.html'

**Comment by justinmayer** [comment]
Ostensibly addressed by #319
