### ISSUE TITLE
Improve tests and testing environment

### ISSUE THREAD

**Issue by cdunklau** [getpelican/pelican-plugins#25]
Testing plugins is a pain, and it shouldn't be.

I suggest we use tox, set up with the same environments as the main pelican repo. However, we shouldn't test against `pelican/master`, the tests should be against the latest version published on PyPI.

@ametaireau @justinmayer @avaris Thoughts?

**Comment by Lucas-C** [comment]
@cdunklau are you still working on this ?

My current priority is to have a working CI pipeline executing all tests,
but factoring out utility tests functions,
_e.g._ one for building an article generator like [this](https://github.com/getpelican/pelican-plugins/pull/1184/files#diff-a436ab253f6c5ef00304bd5cbca21ebeR22),
would be handy for sure.

**Comment by cdunklau** [comment]
Unfortunately this was one of those things that got sidelined when I stopped actively messing around with Pelican. I don’t recall doing much on this front either, beyond perhaps some trivial experiments. I think I created this issue mainly as a “would be nice” suggestion more than anything.

**Comment by Lucas-C** [comment]
Ok, thanks for your answer !
I'm closing this then
