### ISSUE TITLE
subcategory - usage in article paths

### ISSUE THREAD

**Issue by vpiotr** [getpelican/pelican-plugins#279]
I cannot find a way to use subcategory path/plugin in ARTICLE_SAVE_AS and ARTICLE_URL.
I wanted to publish articles under sub-catalogs like this:

Python / FileExports / Snippets / articles / my-article.html
(for example)

I solved it already - issue is just to register problem & connect to possible solution.

**Comment by justinmayer** [comment]
Ostensibly addressed by #319
