### ISSUE TITLE
Use subdirectories in the thumbnailer plugin

### ISSUE THREAD

**Issue by bugnano** [getpelican/pelican-plugins#326]
When using the thumbnailer plugin in conjunction with the gallery plugin,
it would be nice to have the same subdirectories that are in the galleries
also for the thumbnails.

For example, if the gallery structure is as follows:

```
images/
  └──  gallery/
         ├──  firstgallery/
         │      ├──  image1.jpg
         │      ├──  image2.jpg
         │      └──  image3.jpg
         ├──  secondgallery/
         │      ├──  image1.jpg
         │      ├──  image2.jpg
         │      └──  image3.jpg
         └──  thirdgallery/
                ├──  image1.jpg
                ├──  image2.jpg
                └──  image3.jpg
```

and the thumbnailer plugin is configured as follows:

```
IMAGE_PATH = 'images/gallery'
THUMBNAIL_DIR = 'images/thumbnails'
THUMBNAIL_SIZES = {
    '150x90': '150x90',
}
THUMBNAIL_KEEP_NAME = True
```

today the output is as follows:

```
images/
  └──  thumbnails/
         └──  150x90/
                ├──  image1.jpg
                ├──  image2.jpg
                └──  image3.jpg
```

It would be nice to have an output like:

```
images/
  └──  thumbnails/
         ├──  firstgallery/
         │      └──  150x90/
         │             ├──  image1.jpg
         │             ├──  image2.jpg
         │             └──  image3.jpg
         ├──  secondgallery/
         │      └──  150x90/
         │             ├──  image1.jpg
         │             ├──  image2.jpg
         │             └──  image3.jpg
         └──  thirdgallery/
                └──  150x90/
                       ├──  image1.jpg
                       ├──  image2.jpg
                       └──  image3.jpg
```

Doing this not only results in an output structure that is more coherent with the input structure,
but it would also prevent conflicts when two or more files have the same name, but are in a different directory.

**Comment by justinmayer** [comment]
@bugnano: Is this something you would like to work on implementing?

**Comment by kdeldycke** [comment]
For the record, the canonical `thumbnailer` plugin has been moved to its own repository at: https://github.com/pelican-plugins/thumbnailer.

I guess this feature request can be either closed or moved to https://github.com/pelican-plugins/thumbnailer/issues.

**Comment by justinmayer** [comment]
Many thanks for helping clean up these issues, Kevin. 💯
