### ISSUE TITLE
asciidoc_reader unexpected error: expected string or buffer

### ISSUE THREAD

**Issue by hjwp** [getpelican/pelican-plugins#340]
I came across this when trying to compile a file that uses the pygments source-highlighter.  To repro, you can use this as a patch:

https://github.com/hjwp/pelican-plugins/commit/22288a554fdcfdde7b2f1af39604b10d336329a4

Note that the test file compiles perfectly happily if you just give it

```
asciidoc -a source-highlighter=pygments asciidoc_reader/test_data/article_for_pygments_highlighting.asc
```

I don't think it's actually pygments per se, just that somehow asciidoc is getting confused when it tries to parse the `[source,syntax]` directive.  It must be something to do with the way it's being called through the API? 

Adding a bit of debug code to asciidoc itself reveals this traceback:

```
  File "/home/harry/workspace/asciidoc/asciidoc.py", line 6026, in asciidoc
    document.translate(has_header) # Generate the output.
  File "/home/harry/workspace/asciidoc/asciidoc.py", line 1646, in translate
    self.consume_attributes_and_comments()
  File "/home/harry/workspace/asciidoc/asciidoc.py", line 1568, in consume_attributes_and_comments
    AttributeList.translate()
  File "/home/harry/workspace/asciidoc/asciidoc.py", line 1947, in translate
    parse_attributes(v, attrs)
  File "/home/harry/workspace/asciidoc/asciidoc.py", line 505, in parse_attributes
    s = re.sub(r'\s', ' ', attrs)
  File "/usr/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
```

Around line 1947 in asciidoc.py, we have:

```
                v = subs_attrs(v)
                if v:
                    parse_attributes(v, attrs)
```

A bit more debugging will reveal that `subs_attrs` is turning `v` from being a string (which is what `parse_attributes` wants, into a tuple-ised version of itself.  But now we're deep into asciidoc voodoo.

So something must be going wrong with the way asciidoc is being called at this point.  But what?

**Comment by justinmayer** [comment]
Not sure if this is still a problem. If so, please feel free to comment here so the issue can be re-opened.
