### ISSUE TITLE
Should be optional to include translations in tipue_search

### ISSUE THREAD

**Issue by helderco** [getpelican/pelican-plugins#343]
Hey, I'm using _i18n_subsites_ and don't want to include translations in my _tipue_search_ because the subsite will have it's own `tipuesearch_content.json`.

So we could have a setting with something like:

``` python
if self.settings.get('SEARCH_INCLUDE_TRANSLATIONS'):
    for article in self.context['articles']:
        pages += article.translations
```

**Comment by justinmayer** [comment]
If someone wants to implement this, please feel free to comment here so the issue can be re-opened.
