### ISSUE TITLE
Line breaks for eqnarray environment in LaTeX

### ISSUE THREAD

**Issue by terriyu** [getpelican/pelican-plugins#35]
I've been using the Pelican LaTeX plugin and it works great!  Thanks!

I noticed that when I use the eqnarray environment in markdown, I have to use triple slashes "\\\" for linebreaks instead of "\\"  Otherwise, it doesn't work.  For example:

$$
\begin{eqnarray}
\nabla \cdot \vec{E} &=& 4\pi\rho \\\
\nabla \cdot \vec{B} &=& 0 \\\
\nabla \times \vec{E} &=& -\frac{1}{c}\frac{\partial \vec{B}}{\partial t} \\\
\nabla \times \vec{B} &=& \frac{1}{c}\left(4\pi\vec{J} + \frac{\partial \vec{E}}{\partial t}\right)
\end{eqnarray}
$$

If someone else can confirm this issue, can this detail be added to the documentation for the LaTeX plugin?

**Comment by barrysteyn** [comment]
@justinmayer - we can close this issue, its been resolved ages ago

**Comment by justinmayer** [comment]
Thanks, Barry.
