### ISSUE TITLE
liquid_tags: Multi-line support?

### ISSUE THREAD

**Issue by dorneanu** [getpelican/pelican-plugins#355]
Hi,

I'd like to have some graphviz dot plugin which supports multi-line. Unfortunately liquid-tags doesn't support multi-line at the moment like the following:

```
{% dot 
    digraph graphname {
        a -> b -> c;
        b -> d;
    }
%}
```

However this line gets replaced properly:

```
{% dot digraph graphname { a -> b -> c; b -> d;} %}
```

Any ideas how to implement this properly? Thx.

**Comment by justinmayer** [comment]
Not sure if this is still a problem. If so, please feel free to comment here so the issue can be re-opened.
