### ISSUE TITLE
liquid tags: Support protocol-less/-relative URLs for embedding videos

### ISSUE THREAD

**Issue by jmcastagnetto** [getpelican/pelican-plugins#361]
Liquid tags should use protoco-less/-relative URLs, so it can work for resources that are available both via HTTP and HTTPS, such as YouTube.

For example in the line https://github.com/getpelican/pelican-plugins/blob/master/liquid_tags/youtube.py#L46,

It has now:
```python
         src='http://www.youtube.com/v/{youtube_id}'
```

That line could be changed to:
```python
         src='//www.youtube.com/v/{youtube_id}'
```

The syntax above is kosher according to: http://tools.ietf.org/html/rfc3986#section-4.2

A typical use case is a blog that is available via HTTP and HTTPS, and embeds a YouTube video. In the current state, when looking at the page via HTTPS, some web browsers (eg. Chrome) will forbid loading the HTTP resource.

**Comment by justinmayer** [comment]
Many thanks for raising the issue, @jmcastagnetto. As mentioned on Paul Irish's [treatise on protocol-relative URLs](http://www.paulirish.com/2010/the-protocol-relative-url/), this technique is now deemed an anti-pattern, for both security and performance reasons.

Addressed via e80c236, wherein we now use HTTPS for all YouTube links.
