### ISSUE TITLE
liquid tags: PATH config not used

### ISSUE THREAD

**Issue by mchwalisz** [getpelican/pelican-plugins#364]
Hi,

liquid_tag plugin doesn't use `PATH` variable form config. It is fixed to `content` in [notebook.py](https://github.com/getpelican/pelican-plugins/blob/master/liquid_tags/notebook.py#L265) and [include_code.py](https://github.com/getpelican/pelican-plugins/blob/master/liquid_tags/include_code.py#L75). Trying to use custom `PATH` yields  to the following error:

```
WARNING: Could not process summary.md
File content/notebooks/summary.ipynb could not be found
```

The page is then not generated.

**Comment by fehiepsi** [comment]
@mchwalisz : You should set `NOTEBOOK_DIR` variable in pelican config file.

**Comment by mchwalisz** [comment]
Sorry for posting this bug again #437.

`NOTEBOOK_DIR` is just ignored. Also this plugin always looks for content in `content` folder. As I'm using different one it is always broken.

**Comment by justinmayer** [comment]
If someone wants to implement a fix for this, please feel free to comment here so the issue can be re-opened.
