### ISSUE TITLE
rmd reader plugin error

### ISSUE THREAD

**Issue by odataID** [getpelican/pelican-plugins#375]
Is there any someone can give me light about this error?
I am new pelican user, I've add plugin path and lists of plugins that I used in pelicanconf.py

`
PLUGIN_PATH = os.path.abspath('./pelican-plugins')
PLUGINS = [# 'assets',
           # 'gravatar',
           # 'pelican.plugins.github_activity',
           'rmd_reader',
           'related_posts',
           'extract_toc',
           # 'cjk-auto-spacing',
           # 'pin_to_top',
           'series',
           ]
`
I got error like this when I tried to run pelican content:
`(u'Pelican does not know how to parse %s', u'/Volumes/RISCHAN/RodataID/content/testplot.Rmd')`

Thank you,

**Comment by mic0331** [comment]
The same happen to me ...

**Comment by wilsonfreitas** [comment]
Hi,

@mic0331 thanks for mentioning me. Unfortunately I haven't seen the first post before.
Being honest, I don't know. Once I declare inside plugin that it has to deal with rmd and Rmd extensions, I understand that it is pelican's job to make the connections.
But, which pelican version are you running? I am with 3.5.0. I know it is outdated and I'm planning to update that soon.
Please, take a look at my project and see if you detect any difference (https://github.com/wilsonfreitas/blog.aboutwilson).

**Comment by justinmayer** [comment]
Not sure if this is still a problem. If so, please feel free to comment here so the issue can be re-opened.
