### ISSUE TITLE
filetime_from_git fails with 'Repo' object has no attribute 'commits'

### ISSUE THREAD

**Issue by a3nm** [getpelican/pelican-plugins#384]
Hi,

When trying to setup filetime_for_git, generation of all files fails with the message "'Repo' object has no attribute 'commits'". I guess the incriminated line is in `filetime_from_git.py`:

    commits = repo.commits(path=path)

Indeed, using the gitpython that I have obtained with `sudo pip install gitpython` on Debian testing (which seems to be version 0.3.2.1 from `/usr/local/lib/python2.7/dist-packages/git/__init__.py` which seems to be the latest version <https://pypi.python.org/pypi/GitPython/>), the `repo.commits` syntax does not work.

I'm assuming that the plugin is expecting a different version of gitpython. In this case, it should perhaps be updated, or at least the exact version of gitpython to use should be specified.

Thanks!

**Comment by justinmayer** [comment]
Addressed via #473 and therefore now closed.
