### ISSUE TITLE
liquid_tags plugin refusing to load

### ISSUE THREAD

**Issue by claman** [getpelican/pelican-plugins#385]
I'm trying to load the vimeo and youtube modules, but they're not loading. There's not even an error message when I run `pelican -v`.

They're in the right plugin folder; I can load other plugins, just not this one.

I'm using Pelican 3.5

**Comment by Azd325** [comment]
Did you add the plugin config to your pelican config?

**Comment by claman** [comment]
As in, specifically enable liquid_tags.vimeo and liquid_tabs.youtube? I have.

**Comment by Azd325** [comment]
Hmm youtube is working for me in 3.5. 
Can you provide your plugin path and plugins config?

**Comment by claman** [comment]
PLUGIN_PATHS = ['./plugins']
    PLUGINS = ['readtime', 'liquid_tags.vimeo', 'liquid_tags.youtube']

The readtime plugin works as advertised. Strangely, no errors are showing up when I generate the site.

**Comment by Azd325** [comment]
Can you produce an error if you leave the video id out of the liquid tag in
the template.

Alex Claman <notifications@github.com> schrieb am So., 11. Jan. 2015 00:30:

**Comment by claman** [comment]
This is what comes up when I remove the video ID.

    ERROR: Could not process ./videos.md
      | Error processing input, expected syntax: {% youtube id [width height] %}
