### ISSUE TITLE
liquid_tags vimeo plugin not writing to file correctly

### ISSUE THREAD

**Issue by claman** [getpelican/pelican-plugins#396]
I have an article with the correct embed code: `{% vimeo 75196023 640 480 %}`

When I run pelican to generate the site, the article page isn't generated correctly.

According to the reference, what should be generated is this:

    <div class="videobox">
            <iframe src="//player.vimeo.com/video/75196023?title=0&amp;byline=0&amp;portrait=0"
                        width="640" height="480" frameborder="0"
                        webkitAllowFullScreen mozallowfullscreen allowFullScreen>
            </iframe>
    </div>

What's actually being generated is this:

    <div class="videobox">
      <iframe src="//player.vimeo.com/video/75196023?title=0&amp;byline=0&amp;portrait=0"
        width="640" height ...
    </div>

As near as I can tell from looking at the plugin file, the regex, search, and assigning of values are all working properly, but the height isn't being written properly.

**Comment by Azd325** [comment]
I tried your vimeo tag```{% vimeo 75196023 640 480 %}``` . It works properly for me.
Is your plugin folder up to date?

**Comment by claman** [comment]
My plugin folder is (now) up to date. The article page with the video embed is being generated correctly, but the index page is displaying the error listed above.

**Comment by FRidh** [comment]
@claman could you check with `SUMMARY_MAX_LENGTH = None` ?

**Comment by claman** [comment]
@FRidh in pelicanconf.py?
