### ISSUE TITLE
Add LaTeX extension parameter passing with Render Math

### ISSUE THREAD

**Issue by digitalvapor** [getpelican/pelican-plugins#401]
What do you think of adding a pelicanconfig variable to pass extra extensions to [render_math](https://github.com/getpelican/pelican-plugins/tree/master/render_math). If you look at the [mathjax script template](https://github.com/getpelican/pelican-plugins/blob/master/render_math/mathjax_script_template) there are already some extensions included. 

An example extension that I would want to implement:

* http://docs.mathjax.org/en/latest/tex.html#mhchem
* https://en.wikibooks.org/wiki/LaTeX/Chemical_Graphics.

also see [mathjax extension docs](http://docs.mathjax.org/en/latest/tex.html#tex-and-latex-extensions). I'll add it if you want me to and it fits the plugin community standards.

**Comment by barrysteyn** [comment]
Hi @digitalvapor 

I am the developer of this plugin. Apologies, I have been travelling (and working), so I am only looking at this now. 

Yes, I like your idea. I will add the ability to add extensions and defer to you to test. Thanks for using the plugin and making this suggestion. The only way things get better is if people like you ask for them, so again, thanks.

**Comment by meduvigo** [comment]
+1

**Comment by digitalvapor** [comment]
@barrysteyn awesome, thanks

**Comment by barrysteyn** [comment]
@digitalvapor I have added the feature you requested, I just need you to test it and ensure that we are on the same track. Please can you clone https://github.com/barrysteyn/pelican-plugins and use the render_math plugin from there.

If this is what you want, I will pull request it to the official pelican plugin repo.

**Comment by barrysteyn** [comment]
This is solved in PR #415
