### ISSUE TITLE
neighbor plugin - sort by filename?

### ISSUE THREAD

**Issue by stevepowell99** [getpelican/pelican-plugins#403]
Neighbors plugin is useful for next and previous links. 
but I am now sorting my articles by basename using     

```
{% for article in articles|sort(attribute='source_path  ')%}        
```

in my template. any way to get the neighbors plugin to do the same?

**Comment by stevepowell99** [comment]
I worked it out: 
        articles.sort(key=(lambda x: x.date), reverse=(True))

has to be changed to

        articles.sort(key=(lambda x:os.path.basename(x.source_path or '')))

and you have to import os at the start

**Comment by justinmayer** [comment]
Glad you found a workaround.
