### ISSUE TITLE
Google Analytics Plugin

### ISSUE THREAD

**Issue by meduvigo** [getpelican/pelican-plugins#408]
I have an idea of doing a Pelican plugin for Google Analytics users.
Anyone can contribute please.
Thanks.

**Comment by justinmayer** [comment]
Um, what? Most themes already include the GA JS snippet. What precisely are you talking about?

In the future, perhaps consider including more detail in your issue description.

**Comment by nicchub** [comment]
@meduvigo please see the pelican documentation: http://docs.getpelican.com/en/3.5.0/settings.html , fin "GOOGLE_ANALYTICS" settings, you only need set this constant in your pelicanconf.py with the analitycs ID, also how say justinmayer..most themes already include the GA JS snipper :-)

**Comment by sincerefly** [comment]
@justinmayer I think he want to add the sitemap.xml to google webmasters tools, and google need to use the absolute url but this plugin gen is relative url

 I also have this ploblem, is there a way to let plugin generate xml with full url

**Comment by sincerefly** [comment]
I know the reason...  I didn't set the SITEURL, and setting the SITEURL, the loc will be the absolute url
