### ISSUE TITLE
[i18n_subsites] Unlabeled KeyError for hidden pages with same slug

### ISSUE THREAD

**Issue by Undeterminant** [getpelican/pelican-plugins#409]
Traceback: http://pastebin.com/zEAfBqDY

Python 3.4.2, Pelican 3.5.0, and git version of the plugins.

How to reproduce:

* Run `pelican-quickstart` and make a new pelican site.
* Edit `pelicanconf.py` and add `I18N_SUBSITES = {'fr': {}}` to it
* Create two pages with `slug: page` and `status: hidden`, one with `lang: fr` and one with `lang: en`
* Run `make html`

Note on the origin of this error: I was using `FILENAME_METADATA` and made `404.lang.md` pages which both had `status: hidden`, and it seemed to have broken everything.

**Comment by justinmayer** [comment]
Thanks for the issue report, @Undeterminant. Next time, you might want to use a pastebin for the traceback.  (^_^) 

@smartass101: Any thoughts?

**Comment by Undeterminant** [comment]
Moved traceback to a pastebin, also mentioned which Python/Pelican versions. There you go. :P

**Comment by smartass101** [comment]
First of all, I would like to thank you for reporting an issue the right way, including reproduction steps and a full traceback right from the start :+1: 

For me the mystery is how `content.source_path == '[filename]'` as that should be a valid absolute filename in the first place. Could you please include your `FILENAME_METADATA` setting? Also please make sure you somehow don't override the `source_path` metadata somewhere.

**Comment by Undeterminant** [comment]
I was messing around and found that the `FILENAME_METADATA` parameter didn't actually matter for the error, although I personally use `FILENAME_METADATA = '(?P<slug>.*)\.(?P<lang>.*)'` and `PATH_METADATA = '((?P<category>[^/]*)/)?.*'` for the site on which I initially found the error.

**Comment by smartass101** [comment]
Could you do a `grep '\[filename\]' content/` to see if this is in some file somewhere? I haven't found a way in which the plugin could set `content.source_path = '[filename]'`. Also, I'd be interested in your settings file (at least in the not secret parts).

**Comment by smartass101** [comment]
Oh, and try deleting the cache just in case.

**Comment by Undeterminant** [comment]
Oh, I meant that this was the filename of the file in question. I probably should have been clear about that. It was `/tmp/test/content/page/404.fr.md` when I tested it to figure out how to reproduce it.

**Comment by smartass101** [comment]
Oh, ok, that would make more sense :wink:. I'll try to reproduce it and determine a reasonable fix.

**Comment by smartass101** [comment]
Thank you for reporting this issue @Undeterminant, there was indeed a problem with hidden contents not being recorded in the native url database. I added some pages to the test suite inspired by your use case, so we still have 100% coverage.

Sorry for the delay, had a lot of exams in the past few weeks.

**Comment by Undeterminant** [comment]
It's no problem! Thank you so much for making a fix for this.
