### ISSUE TITLE
SUMMARY_MAX_LENGTH can break liquid tags

### ISSUE THREAD

**Issue by FRidh** [getpelican/pelican-plugins#411]
If a liquid tag is used at or around `SUMMARY_MAX_LENGTH` the actual markup the liquid tag creates is cut, causing e.g. video displaying on the index page to fail. Obviously on the article page everything works fine.

I am quite sure this also causes #396.

The easiest solution is to set `SUMMARY_MAX_LENGTH = None`

**Comment by claman** [comment]
Any idea why this happens? It's not really a problem since it can be fixed by setting `SUMMARY_MAX_LENGTH`, but it might be good idea to either fix it if possible or make a note of it somewhere.

**Comment by justinmayer** [comment]
Addressed via linked PR.
