### ISSUE TITLE
Related Posts plugin produces different results at each run

### ISSUE THREAD

**Issue by aladagemre** [getpelican/pelican-plugins#419]
This causes lots of changes in the source code at each run. When we store the files on git, it's a mess. Maybe a deterministic method could be better.

**Comment by avaris** [comment]
It *is* deterministic in the sense that you should get same output if you don't change the input. The only random-looking part is related to the way `dict`s work in python. If you have a bunch of articles with same score, and `RELATED_POSTS_MAX` has to cut it in the middle, small changes might affect which ones are chosen in a seemingly random way.
