### ISSUE TITLE
Undesired <html> and <body> tags produced

### ISSUE THREAD

**Issue by stephane-caron** [getpelican/pelican-plugins#422]
extract_toc inserts <html> and <body> tags inside my pages:

```
<div class="sidebar">
<nav>
<html><body><div class="toc" id="">
<ol class="simple">
<li><a class="reference internal" href="#authors" id="id1">Authors</a></li>
<li><a class="reference internal" href="#abstract" id="id2">Abstract</a></li>
<li><a class="reference internal" href="#bibtex" id="id3">BibTeX</a></li>
</ol>
</div></body></html>
</nav>
</div>
```

These should be stripped at the output of BeautifulSoup.

**Comment by Tastalian** [comment]
Here is a fix: https://github.com/Tastalian/pelican-plugins/commit/1e1f8999b9b86dd109a4b39810e3b8727b7f5a93

**Comment by justinmayer** [comment]
Not sure if this is still a problem. If so, please feel free to comment here so the issue can be re-opened.
