### ISSUE TITLE
thumbnailer: broken expand_gallery()

### ISSUE THREAD

**Issue by phoracek** [getpelican/pelican-plugins#432]
`expand_gallery()`
- has not a proper **docstring**
- has unused variable `thumbnail_prefix`
- calls `resizer()` without `root` parameter and therefore explodes. In another use case of `resizer()` we pass `pelican.settings.get("IMAGE_PATH", DEFAULT_IMAGE_DIR))` to it.

**Comment by justinmayer** [comment]
If someone wants to work on this, please feel free to comment here so the issue can be re-opened.
