### ISSUE TITLE
(Assets) SASS & SCSS compiling with media debug queries

### ISSUE THREAD

**Issue by Demonax** [getpelican/pelican-plugins#440]
I am stumped on this problem. Both SASS and SCSS are compiling, but I am getting a large number of media queries of this sort in my compiled CSS:

`@media -sass-debug-info{filename{}line{font-family:\0000310}}`

Not only that, but options passed to SASS_STYLE ('compact', 'compressed') do not seem to have any effect. 

In `pelicanconf.py` I have set `SASS_DEBUG_INFO = False`, and took a shot at mucking around with ASSET_CONFIG:

`ASSET_CONFIG = (( 'sass', 'debug_info = false' ),)`

No luck yet. I am far from expert in any of these tools, so I'm out of ideas.

**Comment by avaris** [comment]
IIRC, any config to [webassets components](http://webassets.readthedocs.org/en/latest/builtin_filters.html#sass) needs to be passed through `ASSET_CONFIG`. You defining `SASS_STYLE` or `SASS_DEBUG_INFO` in `pelicanconf.py` doesn't have any effect. `ASSET_CONFIG` format it `('config', 'value')`, so you need to use:

``` python
ASSET_CONFIG = (
    ('sass_style', 'compact'),
    ('sass_debug_info', 'False') # I don't remember if it's case sensitive or not
) 
```

**Comment by atoohill** [comment]
Has anyone else seen this issue and found any solutions? I'm seeing the same items that Demonax sees.

**Comment by avaris** [comment]
@atoohill my suggestion isn't working?

**Comment by Demonax** [comment]
I never could get it to work myself. I tried the suggestions for ASSET_CONFIG, and when those didn't work I tried default Sass options and a few other things, but I never could get the compiled CSS to respect the commands passed to it.

**Comment by avaris** [comment]
@atoohill I just tested and `ASSET_CONFIG` is working fine for me. FWIW, boolean settings should be actual booleans:

```python
ASSET_CONFIG = (
    ('sass_style', 'compact'),
    ('sass_debug_info', False),
) 
```

Can you show the settings you use and the relevant bits from the theme that uses assets?

**Comment by atoohill** [comment]
Thanks @avaris, your  comment on booleans made the difference. Now we can do sass_styles of 'compact' and 'compressed' and it works great.  Thanks!

**Comment by justinmayer** [comment]
Seems like this has been sorted out, at least for @atoohill. Thanks, @avaris!
