### ISSUE TITLE
liquid_tags with pelican 3.5.0 fails to generate correctly

### ISSUE THREAD

**Issue by jojanaho** [getpelican/pelican-plugins#441]
Combining liquidtags and pelican v 3.5.0 seems to break e.g. youtube tag (probably others as well)?

By tracing the problem a bit, looks like `LiquidTags.extendMarkdown` is never called, and that's possible the reason why liquidtags are not registered as markdown extensions?

Liquidtags seem to be working ok with 3.3.0, so there's probably a breaking api change somewhere.

**Comment by avaris** [comment]
I can't replicate the problem. I tested a bit and `youtube` tag seems to be working for me. This is what I did:

**pelicanconf.py**
```python
# ...
PLUGIN_PATHS = ['/path/to/plugins']
PLUGINS = ['liquid_tags.youtube']
# ...
```

**test.md**
```markdown
Title: Test
Date: 15-03-2015

Some content

{% youtube VIDEO_ID %}
```
And I get the youtube video embedded in the output file.

Can you specify what you do that's not working?

**Comment by jojanaho** [comment]
Thanks for checking this out.
Looks like error was somehow related to my `cache`-directory. After removing it, video was embedded properly.
