### ISSUE TITLE
ToC plugin breaks markdown extension attr_list

### ISSUE THREAD

**Issue by heyalexej** [getpelican/pelican-plugins#456]
When working with [inline or block level attributes](http://pythonhosted.org/Markdown/extensions/attr_list.html), the toc plugin seems to be breaking it's functionality.
I'm using the most recent version (b8b9858da98fa594377e21a4cbaa8154b26e7e98) and tried to debug it for some time but couldn't figure it out.

```
Title: My Fancy Title
Date: 2015-03-01
Slug: the-sluggish-slug
Icon: power-off

[TOC]

# May The Force Be With You

![some alt text](https://i.imgur.com/gYBkS3C.jpg){: style="width:100%"}   


## Another Title

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt... 
```

I tried every possible combination of inline, block level, with or without spaces etc.

**Comment by justinmayer** [comment]
Not sure if this is still a problem. If so, please feel free to comment here so the issue can be re-opened.
