### ISSUE TITLE
render_math: '<' in mathjax_script_template trips some validators

### ISSUE THREAD

**Issue by a3nm** [getpelican/pelican-plugins#460]
Hi,

The recent support for "responsive" in render_math means that mathjax_script_template now contains the '<' character. As this gets added as-is to the rendered HTML, this may be problematic when generating markup that is designed for XML or XHTML parsers. (It trips up my own validation, using tidy -xml.)

Of course, that's a fairly minor problem (this presence of unescaped '<' in a script element isn't flagged by the W3C validator when generating HTML5, for instance, and it poses no rendering issue in any browser that I know of). However I think it would be cleaner to wrap the code of mathjax_script_template in a CDATA section as described here: http://stackoverflow.com/q/66837/414272. This has essentially no downsides as the CDATA markup is in a JS comment and will be happily ignored by anything that does not understand it.

Do you think that's a good idea? Thanks!

**Comment by barrysteyn** [comment]
Hi

Sorry I have taken so long to comment. This can definitely be done very quickly, and I can't see any downsides to doing this. I can implement it and publish it quickly - do you still want it?

**Comment by a3nm** [comment]
Yes, I'm still interested, it would be great if you could take care of this!

Thanks :)

**Comment by barrysteyn** [comment]
Okay, give me two days or so.

**Comment by a3nm** [comment]
Hi, I was just wondering if you had made any progress on this? Thanks!

**Comment by justinmayer** [comment]
@barrysteyn: Any updates on this issue? 😊

**Comment by a3nm** [comment]
Hi! I'm not sure exactly, why has this issue been closed? Has the problem been fixed somehow? Thanks!

**Comment by justinmayer** [comment]
Closed it by accident. That said, I'm inclined to wait to re-open until we hear from @barrysteyn.

**Comment by a3nm** [comment]
@barrysteyn, any updates about this? Thanks!

**Comment by a3nm** [comment]
Hi @justinmayer, as we are not hearing any comments for @barrysteyn, probably this issue should be reopened? Thanks!
