### ISSUE TITLE
Cloning multimarkdown_reader fails

### ISSUE THREAD

**Issue by debugger22** [getpelican/pelican-plugins#479]
Cloning `multimarkdown_reader` fails due to SSH error.

**Comment by willpatera** [comment]
`.gitmodules` url for `multimarkdown_reader` should be changed to use `https`. Making this change will solve the problem. Just open `.gitmodules` and change the url parameter to: `url = https://github.com/dames57/multimarkdown_reader.git`  

I have made this change in [my fork here](https://github.com/willpatera/pelican-plugins/blob/master/.gitmodules#L78).

**Comment by willpatera** [comment]
Merged. This issue can be closed I think.
