### ISSUE TITLE
(Assets) Specify input from variables

### ISSUE THREAD

**Issue by justmytwospence** [getpelican/pelican-plugins#483]
Is there any way to have the webassets plugin operate on a CSS file that is in the content directory, rather than the theme directory? I'm writing a theme and would like for a `CUSTOM_CSS` path to be specified in pelicanconf.py so that custom CSS can be added to the webasset minification without needing to fork the theme repo itself.

**Comment by justinmayer** [comment]
If someone wants to work on this, please feel free to comment here so the issue can be re-opened.
