### ISSUE TITLE
notebook plugin problems with newest IPython 3

### ISSUE THREAD

**Issue by cranmer** [getpelican/pelican-plugins#484]
I'm using travis to deploy my pelican site. My requirements.txt file had 
`ipython[notebook]`

but during build I get
`
/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/IPython/nbformat/current.py:19: UserWarning: IPython.nbformat.current is deprecated.
- use IPython.nbformat for read/write/validate public API
- use IPython.nbformat.vX directly to composing notebooks of a particular version
  """)
/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/IPython/nbformat/current.py:75: UserWarning: reads_json is deprecated, use reads
  warnings.warn("reads_json is deprecated, use reads")
`

If I change to:
`ipython[notebook]==2.4`
then it works, but would be nice to be compatible with v3.

**Comment by jfosorio** [comment]
This issue is related with the fact that in version <3.0 there is something called  worksheets that was removed in the following versions. I modified locally /pelican-plugins/liquid_tags/notebook.py class SubCell like in the inset and it works. 

```python
class SubCell(Preprocessor):
    """A transformer to select a slice of the cells of a notebook"""
    start = SliceIndex(0, config=True,
                       help="first cell of notebook to be converted")
    end = SliceIndex(None, config=True,
                     help="last cell of notebook to be converted")

    def preprocess(self, nb, resources):
        nbc = deepcopy(nb)
        if LooseVersion(IPython.__version__) < '3.0':         
            for worksheet in nbc.worksheets:
                cells = worksheet.cells[:]
                worksheet.cells = cells[self.start:self.end]
        else:
            nbc.cells = nbc.cells[self.start:self.end]
        return nbc, resources

    call = preprocess # IPython < 2.0

```

**Comment by justinmayer** [comment]
Pull request #466 was just merged and includes some enhancements related to `liquid_tags` and IPython 3. Would you please test the latest version of the plugin and report back as to whether this issue still remains? (cc: @jfosorio)

**Comment by cranmer** [comment]
Working for me (also using cell selection).  Thanks!
