### ISSUE TITLE
photo galleries error

### ISSUE THREAD

**Issue by lgwapnitsky** [getpelican/pelican-plugins#489]
when adding the "gallery:" tag at the beginning of my md article files, I'm receiving the following when processing:

ERROR: Could not process gallery/test.md
  | __init__() missing 1 required positional argument: 'root'

I've added the proper code to the template file, bu no luck

**Comment by pxquim** [comment]
Which plugin are you using, @lgwapnitsky? Gallery or Photos?

**Comment by mwcz** [comment]
I get this too when using the gallery plugin.
