### ISSUE TITLE
Direct Templates in the Sitemap

### ISSUE THREAD

**Issue by aladagemre** [getpelican/pelican-plugins#504]
I'm using sitemap plugin. I created a direct template called 'blog' and listed latest blog posts on this page, similarly english and turkish pages (see below).

However, sitemap plugin will not put these direct templates (blog, english, turkce) into sitemap.xml. Is this a missing feature or am I doing something wrong?

DIRECT_TEMPLATES = (('index', 'tags', 'categories', 'authors', 'archives', 'search', 'blog/index', 'english/index', 'turkce/index'))

(Some unimportant pages like search.html, authors.html are not indexed either but they are not important since I'm single author and search is not meant to be indexed.)

**Comment by ziogaschr** [comment]
Is this similar to `TEMPLATE_PAGES`? Has `DIRECT_PAGES` renamed to `TEMPLATE_PAGES`?
I would like to have this ability.

**Comment by mitchtbaum** [comment]
https://github.com/getpelican/pelican/wiki/Tips-n-Tricks#generate-sitemapxml

**Comment by Scheirle** [comment]
Fixed by #696

**Comment by justinmayer** [comment]
Thanks for the nudge, @Scheirle!  (^_^)
