### ISSUE TITLE
i18n_subsites: Doesn't play nice with save_as

### ISSUE THREAD

**Issue by plaes** [getpelican/pelican-plugins#506]
I'm trying to setup a custom index page (and also translated index page) like this:

index.md which contains `save_as: index.html`

And also index-ee.md with similar: `save_as: ee/index.html`

Unfortunately the dev server points me to `ee/index/` for translation, but it's not found.

**Comment by Alexqw** [comment]
I'm using i18n_subsites and also am overwriting my index page. The way I do it is:

* no save_as directive in the index page

pelicanconf.py
* Remove "index" from DIRECT_TEMPLATES
* PAGE_URL = '{slug}.html' in 
* PAGE_SAVE_AS = '{slug}.html'

And it works just fine. Granted, by PAGE URL setup is odd (joys of the customer wanting me to match the old site's... unfortunate... layout), but it does work.

**Comment by Alexqw** [comment]
Sorry, if it wasn't clear, but you want to make sure your index page's slug resolves to "index". Whether that's messing with your pelicanconf's SLUGIFY_SOURCE of just using the "slug" field in your content page(s).

**Comment by justinmayer** [comment]
@plaes: Were you able to resolve your `i18n_subsites`-related issue?

**Comment by JulienPalard** [comment]
For future readers, there's a way to have a translated custom index page without changing `PAGE_URL`:

- Have a `save_as: index.html` **on both pages** (as you would do for a non-translated custom index page).
- Have a `lang:` **on both pages** as you would do for any translated content.
- Add an empty `URL` attribute **on both pages** so the cross-language links are short (not to `/pages/...`).

In Markdown it looks like:
```
lang: fr
URL:
save_as: index.html
```

and

```
lang: en
URL:
save_as: index.html
```

That's it.
