### ISSUE TITLE
SyntaxError: can't assign to literal when using subcategory plugin

### ISSUE THREAD

**Issue by xh84** [getpelican/pelican-plugins#519]
i git clon subcategory plugin and add codes of the following to my Pelican configuration file:

PLUGIN_PATHS = ['plugins/pelican-plugins']
PLUGINS = ['subcategory', ]

'SUBCATEGORY_SAVE_AS' = os.path.join( 'subcategory', '{savepath}.html')
'SUBCATEGORY_URL' = 'subcategory/{fullurl}.html'

when i use 'pelican content' command, it tells 'SyntaxError: can't assign to literal'.

**Comment by avaris** [comment]
I realize you copied that from the plugin's Readme but it's wrong. `'SUBCATEGORY_SAVE_AS'` is a string and you can't assign to it. They should be

```python
SUBCATEGORY_SAVE_AS = os.path.join('subcategory', '{savepath}.html')
SUBCATEGORY_URL = 'subcategory/{fullurl}.html'
```

Readme needs an update.

**Comment by xh84** [comment]
can you give me a example?

i set it like this:
'SUBCATEGORY_SAVE_AS' = 'subcategory/{slug}.html'
'SUBCATEGORY_URL' = 'subcategory/{slug}.html'

it also tells me error

**Comment by avaris** [comment]
Right side is fine. Problem is the left side. `'SUBCATEGORY_SAVE_AS'` should be `SUBCATEGORY_SAVE_AS` (*no quotes*). Similar for `SUBCATEGORY_URL`.

**Comment by xh84** [comment]
Oh......., it is my fault!

can i set it like this:
SUBCATEGORY_SAVE_AS = 'subcategory/{slug}.html'
SUBCATEGORY_URL = 'subcategory/{slug}.html'

it tells me :
CRITICAL: 'article' is undefined

**Comment by xh84** [comment]
after debug i find the code below causing this:
<a href="{{ SITEURL }}/{{ article.category.url }}">{{ article.category}}</a>

i create a subcategory.html template similar to the category.html, and add the codes according to subcategory plugin's readme

**Comment by xh84** [comment]
can someone help?

**Comment by avaris** [comment]
@xh84 can you show your `subcategory.html`?

**Comment by xh84** [comment]
{% extends "article_list.html" %}
{% block title %}{{ category }} - {{ SITENAME }}{% endblock %}
{% block meta %}
    <meta name="author" content="{{ AUTHOR }}" />
    <meta name="keywords" content="{{ category }}" />
{% endblock %}
{% block breadcrumbs %}
    {% if DISPLAY_BREADCRUMBS %}
    <ol class="breadcrumb">
        <li><a href="{{ SITEURL }}" title="{{ SITENAME }}"><i class="fa fa-home fa-lg"></i></a></li>
        <li><a href="{{ SITEURL }}/{{ article.category.url }}" title="{{ article.category }}">{{ article.category }}</a></li>

		{% for subcategory in article.subcategories %}
		<li {% if subcategory == category %}class="active"{% endif %}>
		<a href="{{ SITEURL }}/{{ subcategory.url }}">{{ subcategory.shortname }}</a>
		</li>
		{% endfor %}
    </ol>
    {% endif %}
{% endblock %}

**Comment by xh84** [comment]
{% extends "article_list.html" %}
    {% block title %}{{ category }} - {{ SITENAME }}{% endblock %}
    {% block meta %}
        <meta name="author" content="{{ AUTHOR }}" />
        <meta name="keywords" content="{{ category }}" />
    {% endblock %}
    {% block breadcrumbs %}
        {% if DISPLAY_BREADCRUMBS %}
        <ol class="breadcrumb">
            <li><a href="{{ SITEURL }}" title="{{ SITENAME }}"><i class="fa fa-home fa-lg"></i></a></li>
            <li><a href="{{ SITEURL }}/{{ article.category.url }}" title="{{ article.category }}">{{ article.category }}</a></li>

		{% for subcategory in article.subcategories %}
		<li {% if subcategory == category %}class="active"{% endif %}>
		<a href="{{ SITEURL }}/{{ subcategory.url }}">{{ subcategory.shortname }}</a>
		</li>
		{% endfor %}
        </ol>
        {% endif %}
    {% endblock %}

**Comment by avaris** [comment]
I'm not sure what you want to display there but `subcategory.html` is supposed to be similar to `category.html`. In other words, you have a bunch of articles associated with that subcategory in `articles` variable (not just a single article). So, I assume you should have a loop in there over that?

```jinja
{% for article in articles %}
   ...
{% endfor %}
```

**Comment by xh84** [comment]
i use "pelican-bootstrap3" of pelican-themes and custom it.
i just copy category.html and rename it to subcategory.html(there is no loop for the articles), and then i add the codes according to subcategory plugin's readme 

and i check the pelican default theme "simple", and its category.html is below:

    {% extends "index.html" %}
    {% block content_title %}
    <h2>Articles in the {{ category }} category</h2>
    {% endblock %} 

there is no loop also and  it just use "{{ category }}"

**Comment by xh84** [comment]
anyway, it test according to your advice, and there is no error
