### ISSUE TITLE
Dateish produces "TypeError: expected string or buffer"

### ISSUE THREAD

**Issue by marktani** [getpelican/pelican-plugins#522]
My settings in pelicanconf.py:

> PLUGINS_PATHS = ['/home/marktani/pelican-plugins']
> PLUGINS = ['dateish']
> DATEISH_PROPERTIES = ['modified']

In my article I have the markdown property
> Modified: 2015-08-03 18:00

If I run pelican, I get the aforementioned error message.

I tracked it down to line 28 in dateish.py
> setattr(article, field, get_date(value))

Any ideas?

**Comment by avaris** [comment]
`pelican` itself treats `modified` metadata as a date and converts it to a datetime object. You don't need a plugin for that.

**Comment by marktani** [comment]
Oh, I wasn't aware of that; just to confirm:
using
> DATEISH_PROPERTIES = ['start_date', 'end_date']
works with dateish as intended, and I can still call strftime on modified in a template.

Thanks for the help :)
