### ISSUE TITLE
optimize_images converts images on every save when using devserver

### ISSUE THREAD

**Issue by arthurlogilab** [getpelican/pelican-plugins#526]
When editing a post in devserver mode, on every save of the content instead of just regenerating the html for that post. optimize_images re-runs on all images, and so does some unnecessary crunching. 

Would it be possible to disable it in this mode or make it a bit smarter (look at change times on the files) ?

**Comment by MinchinWeb** [comment]
What I do is the `optimize_images` plugin is only listed in the plugins on my `publishconf.py` file, and not in my `pelicanconf.py` file. This means that the plugin only gets called when I "publish" my site.

**Comment by justinmayer** [comment]
Good suggestion, @MinchinWeb. Thanks!
