### ISSUE TITLE
liquid_tags.notebook: ImportError: cannot import name v1 with ipython-3.2.1

### ISSUE THREAD

**Issue by yangj1e** [getpelican/pelican-plugins#536]
I tried to use `liquid_tags.notebook` plugin, but with ipython-3.2.1 I got the error:

```
ERROR: Cannot load plugin `liquid_tags.notebook`
  | ImportError: cannot import name v1
```

Does `liquid_tags.notebook` support ipython-3.x?

**Comment by justinmayer** [comment]
Hi @yangj1e. The commit history indicates that the answer to your question is "Yes": https://github.com/getpelican/pelican-plugins/commit/4b4aa408d9e0c8f4c61275e4e06c4788d48763fc

That said, I have no personal experience with that plugin.

**Comment by aavanian** [comment]
Wrong dependancies I think. Use "pip install IPython[notebook]==3.2.1" and that should work.

**Comment by yangj1e** [comment]
It does not work either.

I used ipython 2.4.1 for a while, which works with the plugin. But after recent updates, I got the following error:

```
ERROR: Could not process blog/visualize-hog.md
  | TraitError: No default value found for None trait of <liquid_tags.notebook.SubCell object at 0x109fa90d0>
```

I tried to upgrade IPython to 4.0, but unfortunately I got the same import error as https://github.com/getpelican/pelican-plugins/issues/542

**Comment by aavanian** [comment]
@yangj1e 
May I ask a few more precisions:
* my previous comment, `pip install IPython[notebook]==3.2.1` didn't solve your issue before the PR? after the #543 PR? (though I don't think the PR should affect this outcome)
* under ipython 2.4.1, PR #543 breaks what was working for you previously?
* for ipython 4.0, did you install the dependancies (in particular ipython) this way `IPython[notebook]`?
* Which python are you running (2.7? 3.4?)

@justinmayer 
I was rechecking what I did and realized that somehow, some debug code made it in the PR, I'll send you a new one but would like to see if I can solve this issue first. Apologies for that.

**Comment by yangj1e** [comment]
@aavanian Sorry, my bad. I didn't do `pip install IPython[notebook]` because I'm using zsh and I need to escape the brackets otherwise there is an error, which made me go back to `pip install ipython`.

So `pip install IPython[notebook]` solves the problem, thank you.

**Comment by aavanian** [comment]
No worries! Glad I could help.
