### ISSUE TITLE
i18n_subsites not generating correct URL's

### ISSUE THREAD

**Issue by zeridon** [getpelican/pelican-plugins#537]
Hi Guys,

I am trying to setup a multilingual site with fallback to the default lang. The setup seems fine but some of the urls are not generated properly (this is still on the devserver)

Setup
````
I18N_SUBSITES = {
        'bg': {},
        'en': {}
        }
I18N_UNTRANSLATED_ARTICLES = 'keep'
I18N_UNTRANSLATED_PAGES = 'keep'
DEFAULT_LANG = u'bg'

PAGE_URL = '{lang}/{slug}.html'
PAGE_SAVE_AS = '{lang}/{slug}.html'
PAGE_LANG_URL = '{lang}/{slug}.html'
PAGE_LANG_SAVE_AS = '{lang}/{slug}.html'
````

What is expected:
* Sites show normally

What is observed:
* http://localhost:8080/ - shows normally - ````<link rel="stylesheet" href="/theme/css/main.css" />````
* http://localhost:8080/bg/ - shows normally, semibroken - ````<link rel="stylesheet" href="/./theme/css/main.css" />````
* http://localhost:8080/en/ - broken - ````<link rel="stylesheet" href="/en/../bg/theme/css/main.css" />````

In the theme i have:
````        <link rel="stylesheet" href="{{ SITEURL }}/{{ THEME_STATIC_DIR }}/css/{{ CSS_FILE }}" />````

There is a single page with no content
````
Title: Testing multilingual

No language defined so it is generated in both langs
````

pelican: 3.6.0
plugin: latest from git

Any help would be appreciated

**Comment by justinmayer** [comment]
@smartass101: Any ideas on how to assist Vladimir with this?

**Comment by smartass101** [comment]
I'm sorry it didn't work out. I think the problem is that you define a sub-site for a language of the main site. The plugin adds sub-sites for extra languages. If you really want to have `/bg` point to the Bulgarian version, just add a symlink `bg -> ./`  or use a `Alias` directive in your web server.

**Comment by zeridon** [comment]
If i read this correctly this means i should not define the main language in the ```I18N_SUBSITES``` var but only the additional ones. Am i correct in assuming this?

**Comment by smartass101** [comment]
yes

**Comment by justinmayer** [comment]
@zeridon: If you have other questions about this issue, please comment here and I can re-open if necessary.
