### ISSUE TITLE
liquid_tags.notebook raises ImportError

### ISSUE THREAD

**Issue by terrycojones** [getpelican/pelican-plugins#542]
I have python 2.7.6 in a virtualenv on Mac OS X 10.10.3, with ipython 4.0.0 and the master branch of pelican-plugins. In my pelicanconf.py I put `liquid_tags.notebook` in my plugins. When I try to make, I get the following:

```
$ make html
[ ! -d /Users/fred/dark-matter/www/output ] || find /Users/fred/dark-matter/www/output -mindepth 1 -delete
pelican /Users/fred/dark-matter/www/content -o /Users/fred/dark-matter/www/output -s /Users/fred/dark-matter/www/pelicanconf.py
/Users/fred/.virtualenvs/dmp/lib/python2.7/site-packages/IPython/nbconvert.py:13: ShimWarning: The `IPython.nbconvert` package has been deprecated. You should import from ipython_nbconvert instead.
  "You should import from ipython_nbconvert instead.", ShimWarning)
ERROR: Cannot load plugin `liquid_tags.notebook`
  | ImportError: No module named filters.highlight
```

In `pelican-plugins/liquid_tags/notebook.py` both halves of this `if` raise the import error:

``` python
try:
    from IPython.nbconvert.filters.highlight import _pygments_highlight
except ImportError:
    # IPython < 2.0
    from IPython.nbconvert.filters.highlight import _pygment_highlight as _pygments_highlight
```

**Comment by aavanian** [comment]
IPython 4.0 does indeed break this plug-in but strangely, in my situation (Python 3.4 though), it wasn't breaking there (only a warning for this import).

I'm about to do a PR that fixes the one call that breaks the plugin for IPython 4.0

**Comment by justinmayer** [comment]
@terrycojones: Can you try Alexandre's version in pull request #543 and see if that resolves the situation for you?

**Comment by terrycojones** [comment]
This problem went away after I read about the changes in IPython 4.0 and did a `pip install jupyter`. Closing.

**Comment by terrycojones** [comment]
Argh, sorry, I missed the comments here. I'll reopen.

**Comment by terrycojones** [comment]
@justinmayer @aavanian  Yes, thanks, `make html` runs cleanly under the `aavanian:liquid_tags_forward` branch.  Note that the original error went away when I simply modernized my environment for ipython 4. But after doing so I still got an `AttributeError` raised when the code tripped over the `IPython.nbformat` usage. I fixed that by doing

```python
try:
    import nbformat
except ImportError:
    # IPython < 4.0
    nbformat = IPython.nbformat
```

But @aavanian's PR looks like it addresses various other issues, as well as just the `nbformat` one. So, LGTM. Thanks again!
