### ISSUE TITLE
i18n_subsites: Linking/pretty URL

### ISSUE THREAD

**Issue by patdavid** [getpelican/pelican-plugins#545]
Not sure if this was covered somewhere that I missed, but I currently have a default page being generated as:

```
site.com/about/index.html
site.com/about/
```

Is there a method to make a translation for a subsite map to the same type of output?  That is, for the same file above:

```
content/about/index.md
```

I have a translated version:

```
content/about/index.fr.md
```

I would like the translation to now output to the same location, but in the subsite (ie):

```
site.com/fr/about/index.html
site.com/fr/about/
```

As it is right now, the French translation will be output as:

```
site.com/fr/about/index.fr.html
```

@smartass101 - any hints?

**Comment by smartass101** [comment]
I think some of your URL settings may not be right. However, without seeing your settings and the page sources (at leas the relevant URL settings and page metadata) I cannot guess much.

**Comment by patdavid** [comment]
Thank you @justinmayer - I honestly lost track of this issue and must have worked through it long ago! :)
