### ISSUE TITLE
share_post: plugin is unusable ('summary' var non existent)

### ISSUE THREAD

**Issue by davidmarquis** [getpelican/pelican-plugins#549]
Plugin won't compile as 'summary' variable on line 42 of share_post.py is not found

**Comment by kernc** [comment]
So https://github.com/getpelican/pelican-plugins/commit/fcdab23806fea19f69fc71b840cbd93e03512562 is to be reverted. I apologize for not inspecting it thoroughly when rebasing. The changes just applied so cleanly. :]

**Comment by davidmarquis** [comment]
No worry, do you want me to submit a pull request to revert it?

**Comment by kernc** [comment]
Why not? :smiley:
