### ISSUE TITLE
pelican-plugins/pdf/ extension to md

### ISSUE THREAD

**Issue by deguss** [getpelican/pelican-plugins#573]
dear developer @kylewm ! Is there a way to get working the pdf generator on markdown files also? Many thanks!

**Comment by kylewm** [comment]
Hi @deguss, unfortunately I didn't write the PDF extension -- I just refactored it out of the main repository into a separate plugin a couple years ago during a code sprint.

The plugin itself delegates the actual conversion to an rst2pdf library. If there's a comparable markdown-to-pdf library, it should be easy to adapt, but I'm not seeing any great candidates in a quick search...

**Comment by deguss** [comment]
thank you! I am also not able to find any usable tool for converting md to pdf. I should rather search for html2pdf.

**Comment by trovao** [comment]
Hi @deguss, you might want to check whether this new update to the PDF plugin works for you.

PS: Sorry about the pull request spam.

**Comment by justinmayer** [comment]
Not sure if this is still a problem. If so, please feel free to comment here so the issue can be re-opened.
