### ISSUE TITLE
share_post: pelican can't find images when plugins enabled

### ISSUE THREAD

**Issue by sanjayankur31** [getpelican/pelican-plugins#577]
I enabled this plugin in pelicanconf, and then started getting these:

```
[asinha@cs-as14aho-2-herts-ac-uk  UH-biocomputation-web(master *=)]$ make publish ; make serve
pelican /home/asinha/Documents/02_Code/00_repos/01_others/UHBiocomputation/UH-biocomputation-web/content -o /home/asinha/Documents/02_Code/00_repos/01_others/UHBiocomputation/UH-biocomputation-web/output -s /home/asinha/Documents/02_Code/00_repos/01_others/UHBiocomputation/UH-biocomputation-web/publishconf.py 
WARNING: Unable to find `/images/assoc-small.gif`, skipping url replacement.
WARNING: Unable to find `/images/BoB.png`, skipping url replacement.
WARNING: Unable to find `/images/Purkinje_bw.png`, skipping url replacement.
WARNING: Unable to find `/images/2purk_calcium.jpg`, skipping url replacement.
WARNING: Other resources were not found and their urls not replaced
```

The images really do not show up in the generated files.

Not really sure why this is happening. Disabling the plugin lets pelican work normally. The normal pelicanconf is here: https://github.com/UHBiocomputation/UH-biocomputation-web/blob/master/pelicanconf.py

**Comment by avaris** [comment]
Known issue. Well... kind of. See #556

**Comment by sanjayankur31** [comment]
I see there's kind of a fix in the last comment. Unfortunately, I don't really know what it means. I'll look at it, but it'll be nice if someone that already knows how pelican works could quickly fix it ;)
