### ISSUE TITLE
[tipue_search] Generated JSON should not include siteurl

### ISSUE THREAD

**Issue by bittner** [getpelican/pelican-plugins#590]
The `tipue_search` plugin generates JSON with and absolute URL value (i.e. protocol + domain + document path). This way it's impossible to use the site with (or test changes on) the search results locally.

The culprit is [tipue_search (line 55)](https://github.com/getpelican/pelican-plugins/blob/master/tipue_search/tipue_search.py#L55), which composes the `page_url` as SITEURL + document path. It should be changed to `page.url` only:

``` python
page_url = page.url
```

This should be safe when the `search.html`, which displays the search results, is located on the same level as the result documents. I think we can take this for granted.

**Comment by justinmayer** [comment]
The way this is generally handled in Pelican is to use two configuration files: one for local development (with `SITEURL = ''`) and one for production use (with `SITEURL = 'https://example.com'`). You can see how this is done by running `pelican-quickstart` and inspecting the resulting pair of configuration files.

With the solution you have proposed, there would be no way to generation JSON with fully-qualified URLs.

**Comment by bittner** [comment]
Could you explain why there is a need for fully-qualified URLs in the JSON? It is just used for the search results displayed by the `search.html` of the generated project it's part of. The URL paths are relative to that project.

**Comment by justinmayer** [comment]
I see your point. If is something you (or anyone else) would like to work on, please feel free to comment here so the issue can be re-opened.

**Comment by bittner** [comment]
Please note that [I placed a PR](https://github.com/getpelican/pelican-plugins/issues/591) 1.5 years ago. Looks like it's still good (no merge conflicts). If you're willing to merge it that would be helpful. I may be able to give up on [my own fork](https://github.com/bittner/pelican-plugins/tree/master/tipue_search).

**Comment by justinmayer** [comment]
Missed that. My mistake. Merged your PR.
