### ISSUE TITLE
Named footnotes

### ISSUE THREAD

**Issue by MartinThoma** [getpelican/pelican-plugins#606]
I would like to have the following feature:

It should be possible to add names to the footnote, like

``` text
Aufbauend auf dem Tutorial können wir in weiteren Treffen über aktuell führende
Netze, wie *AlexNet*[ref name="AlexNet"]Alex Krizhevsky, Ilya Sutskever, Geoffrey E. Hinton, "[ImageNet Classification with Deep Convolutional
Neural Networks](http://www.cs.toronto.edu/~fritz/absps/imagenet.pdf)", 2012.[/ref] oder *GoogLeNet* [2] diskutieren. Wie in [ref name="AlexNet" /]
```

Something similar is already been used on Wikipedia (e.g. see the first reference with the a-g anchors t get back in https://en.wikipedia.org/wiki/Germany#References)

**Comment by MartinThoma** [comment]
(for https://github.com/getpelican-plugins/simple_footnotes.git)

**Comment by justinmayer** [comment]
Hi Martin. Would you like to work on implementing the feature you proposed?

**Comment by braunmagrin** [comment]
Hello, I guess I could work on it. But I would need a little bit more info from @MartinThoma, I'm not sure that I understood it completely. The idea is to be able to refer to the same footnote more than once?

**Comment by MartinThoma** [comment]
@justinmayer No, I don't want to work on this.

@braunmagrin It would be awesome if you could do it :-) Yes, the idea is to refer to the same footnote more than once.

**Comment by Scheirle** [comment]
If you are using Markdown you can simply use the Markdown footnotes extension: https://pythonhosted.org/Markdown/extensions/footnotes.html

You just have to activate it, it included in the standard Markdown library.

**Comment by ahmetalpbalkan** [comment]
@Scheirle how do you activate it in pelican?

**Comment by Scheirle** [comment]
@ahmetalpbalkan in Pelican 3.7 and probably earlier version it is enabled by default.
By default Pelican adds the [`extra`](https://pythonhosted.org/Markdown/extensions/extra.html) extension and that pulls in the `footnote` extension.

But if you want to add it manually:
```
MARKDOWN = {
    'extensions' : ['markdown.extensions.footnotes'],
}
```

**Comment by braunmagrin** [comment]
So can we close this issue then?

**Comment by justinmayer** [comment]
Thanks to @Scheirle for pointing out a solution and to @braunmagrin for the reminder.  (^_^)

**Comment by MartinThoma** [comment]
The syntax for footnotes is `[^1]`: https://python-markdown.github.io/extensions/footnotes/

One problem I have with it is if the footnote is in a (HTML) table.
