### ISSUE TITLE
photos-plugin: Photos in article are using wrong hard-coded URL instead of SITEURL

### ISSUE THREAD

**Issue by skettlitz** [getpelican/pelican-plugins#607]
When including an photo as image in an (.rst-)article as

     .. image:: {photo}name.jpg

It is correctly recognized and resized. The image src-URL however is wrongly translated.

In photos.py in detect_content the line

                origin = os.path.join('/photos', photo)

hard-codes the location without respecting SITEURL. This works when the blog is located in the top directory on the server (e.g. when running the server with "make serve"). When the blog is located in a subdirectory or when the photos are located on another location, this fails.

Therefore I suggest to introduce an option PHOTO_BASEURL and to change the above line to

                origin = os.path.join(settings['PHOTO_BASEURL'], photo)

with PHOTO_BASEURL = SITEURL as default when not set in the pelicansettings.py.

The galleries are not affected by this bug since their URLs are encoded in the Jinja-Templates which include SITEURL in the appropriate place.

**Comment by pxquim** [comment]
Sorry for the delay, @skettlitz.

I am afraid that you are exercising a part of the plugin that I have not really used myself.

Anyway, I would prefer:

    origin = os.path.join(settings['SITEURL'], 'photos', photo)

But this is still untested. I will look into this further.

**Comment by pxquim** [comment]
@skettlitz, pull request #653 should fix this.
