### ISSUE TITLE
Marking the summary portion of the article with read_more_link

### ISSUE THREAD

**Issue by ahmetalpbalkan** [getpelican/pelican-plugins#624]
Hi folks, I'm coming from a wordpress background and we used to have `<!--more-->` to mark the summary of the article to be shown on the index page.

I'm using [`read_more_link` plugin](https://github.com/getpelican/pelican-plugins/tree/master/read_more_link) and `SUMMARY_MAX_LENGTH = 80`, however that is not working really well as it sometimes takes a lot more than I intended. 

I realized there is `summary:` in the article metadata, however that appears to be something single-line and requires HTML to add links etc.

I am wondering if there is a solution that I am missing? I appreciate any help, thanks in advance.

**Comment by avaris** [comment]
Did you consider [summary](https://github.com/getpelican/pelican-plugins/tree/master/summary) plugin?

**Comment by ahmetalpbalkan** [comment]
@avaris it's a shame I haven't seen it already. That actually works and just setting 

```py
SUMMARY_END_MARKER = '<!-- more -->'
```

 makes it backwards-compatible with my nearly 10-year old articles from WordPress migration.
