### ISSUE TITLE
pelican_comment_system: python3 compatability

### ISSUE THREAD

**Issue by dirk-olmes** [getpelican/pelican-plugins#639]
I'm running pelican on python3 and recently discovered pelican_comment_system. But it seems the code does not work on python3:

  File "/pelican-env/pelican-plugins/pelican_comment_system/pelican_comment_system.py", line 22, in <module>
    from . comment import Comment
SystemError: Parent module '' not loaded, cannot perform relative import

Converting the relative imports to "normal" imports works fine. But I guess that would break python2 compatability ...

**Comment by Scheirle** [comment]
pelican_comment_system should work with python 2 and 3 (on my system it does; Pelican 3.6.3; Python 3.4.3 and 2.7.6).
The referenced line was added for python 3 support.

The Question is why in your case the Parent module is not loaded.
Do you execute/access the pelican_comment_system directly?

**Comment by dirk-olmes** [comment]
Sorry for the false alarm. It turns out to be misconfiguration on my side - wrong combination of PLUGIN_PATHS and PLUGINS in the pelican config.

It's good to know that python3 is supported, though. Maybe you could mention it in the README of the plugin?
