### ISSUE TITLE
Feed_summary plugin conflits with i18n_subsites.

### ISSUE THREAD

**Issue by linevych** [getpelican/pelican-plugins#650]
When I try to enable `feed_summary` with `i18n_subsites`, I've got the next error:

```
jinja2.exceptions.UndefinedError: 'gettext' is undefined
```

Without `feed_summary` `i18n_subsites` works perfectly. Any ideas how to fix it?

**Comment by justinmayer** [comment]
@linevych: Did you ever find a solution to your problem?

**Comment by linevych** [comment]
Nope. 
After all I decided to licence my blog under CC-BY 4.0 and allow users to read what I'm writing in any news app that they want.

**Comment by justinmayer** [comment]
Understandable. Cheers.
