### ISSUE TITLE
Mathjax broken when using liquid_tags.notebook

### ISSUE THREAD

**Issue by flothesof** [getpelican/pelican-plugins#651]
Hi everyone,

I'm using the liquid_tags.notebook extension to embed a Jupyter notebook (or IPython notebook) in a blog post. 
It works approximately, except for the fact that MathJax equations don't get rendered the way they should.

When I put the following into my markdown file:

```
{% notebook integration_test.ipynb %}
```

I get the following output when rendered:
![image](https://cloud.githubusercontent.com/assets/2360669/12505740/dc2de5ba-c0e9-11e5-8b45-b59912315fd4.png)

Checking the source for the MathJax part, I find:

```
<div class="inner_cell">
<div class="text_cell_render border-box-sizing rendered_html">
<p>A little MathJax:</p>
$$
\alpha = x^3
$$
</div>
</div>
```

Is this a problem with the Jupyter exporter or is this a problem with the plugins? Could anyone help me to fix this?

Thank you in advance,
Florian

**Comment by drorata** [comment]
Is this issue solved? I face the same problem

**Comment by justinmayer** [comment]
Anyone know if this problem still persists?

**Comment by justinmayer** [comment]
If someone can reliably reproduce this with current versions of the relevant components, please comment here with explicit details.
