### ISSUE TITLE
Is there a way to stop liquid tags from being wrapped in a <p> tag?

### ISSUE THREAD

**Issue by mandaris** [getpelican/pelican-plugins#659]
I'd like the code that I create not be in paragraphs so that the css can be applied properly.

**Comment by justinmayer** [comment]
@mandaris: Were you able to find a solution to your problem here?

**Comment by mandaris** [comment]
@justinmayer The solution that I found was to find plugin for markdown. The problem ultimately lies in how python markdown parses the document.

Thank you for continuing the work on the project. I think I understand it can be hard to have all these questions from people and not as much help answering them.
