### ISSUE TITLE
How to debug md_inline_extension

### ISSUE THREAD

**Issue by mpf** [getpelican/pelican-plugins#667]
The `md_inline_extension` is not working — neither the default extension `[]...[]` or custom extensions. (And no errors are issued.) What is the best way to go about debugging the problem? (I'm using pelican v. 3.6.3).

**Comment by justinmayer** [comment]
@mpf: Were you able to find a solution to your problem here?

**Comment by mpf** [comment]
It's been a couple of years since I submitted this issue. It's hard to remember exactly what happened back then. Thanks for checking in!

**Comment by justinmayer** [comment]
@mpf: My pleasure. Sorry to have taken so long to follow up!
