### ISSUE TITLE
sitemap fails on python3

### ISSUE THREAD

**Issue by fxer** [getpelican/pelican-plugins#698]
@ziogaschr Using python 3.5.1 getting the error:

```CRITICAL: AttributeError: 'dict' object has no attribute 'iteritems'```

Looks like it's this usage of .iteritems() without checking to see if .items() should be used instead:
```
# add template pages
for path, template_page_url in self.context['TEMPLATE_PAGES'].iteritems():
```

**Comment by ziogaschr** [comment]
@fxer thanks for finding it.

Can you try the fix as I am not able to test it right now?
Sorry for breaking the plugin at the first place.

**Comment by fxer** [comment]
Yep your PR gets it working under python3 again, thanks @ziogaschr!
