### ISSUE TITLE
sitemap creates 404 urls if category/tag/author is disabled

### ISSUE THREAD

**Issue by fxer** [getpelican/pelican-plugins#701]
Hey Chris, guess I ran into two related issues. I have disabled Author and Category urls on my site, even though behind the scenes folders exist, but I don't display any of that info on the website via:

```
CATEGORY_URL = False
AUTHOR_URL = False
```

Which causes these entries in my sitemap.xml:

```xml
<url>
<loc>http://localhost:8000/False</loc>
<lastmod>2011-07-29T13:58:00-07:53</lastmod>
<changefreq>daily</changefreq>
<priority>0.5</priority>
</url>
<url>
<loc>http://localhost:8000/False</loc>
<lastmod>2011-07-29T13:58:00-07:53</lastmod>
<changefreq>daily</changefreq>
<priority>0.5</priority>
</url>
```

So I attempted to exclude those pages with the config setting:
```
 'exclude': ['category/', 'author/'],
```

But then Pelican throws this error when generating the site:

```
CRITICAL: TypeError: expected string or bytes-like object
```

The error appears to be on line [257](https://github.com/getpelican/pelican-plugins/blob/master/sitemap/sitemap.py#L257), in the generate_output function:
```python
for page in pages:
   self.write_url(page, fd)
```

Enabling category/author urls in pelican immediately clears the problem and sitemap excludes them from sitemap.xml as expected, but then category/author information appears elsewhere on the website since they are no longer disabled.

Not sure the cleanest solution so I don't have a PR without spending more time in the code, but I'm happy to do some digging later if you don't immediately see the fix/have time, thanks @ziogaschr!

**Comment by ziogaschr** [comment]
Can you try add these values in `pelicanconf.py`?

```
# Disable for now as they are not needed
CATEGORY_SAVE_AS = ''
AUTHOR_SAVE_AS = ''
```

**Comment by fxer** [comment]
Boom everything works as expected with that addition, nice workaround!

**Comment by ziogaschr** [comment]
That's great. :)

Can you close the issue?
