### ISSUE TITLE
i18n_subsites and events plugin do not work together

### ISSUE THREAD

**Issue by stieglma** [getpelican/pelican-plugins#705]
As in the title, this ticket is about the fact that these plugins do not work together. The events plugin produces IOErrors while trying to write the calendar files and when fixing this an issue with duplicate entries in the calendar files appears. I fixed this already and provide the solution in the pull request #704

**Comment by justinmayer** [comment]
Thanks, Thomas. In the future, feel free to submit a pull request without a corresponding issue. (i.e., you can combine both functions in the pull request)  (^_^)
