### ISSUE TITLE
whitespace issues

### ISSUE THREAD

**Issue by mclearc** [getpelican/pelican-plugins#712]
all of my search results have `code{white-space: pre;}` in the beginning of the first line of every content entry (i.e. after the title and link for each entry). It is the first entry in the "text" area in the "tipuesearch_content.json" file. There it says  `"text":"code{white-space: pre;}`. It seems to begin every "text" entry.

The jinja entry looks like this:

````
{% block scripts %}
{% if 'assets' in PLUGINS %}
{% include 'include/minify_tipuesearch.html' with context %}
{% else %}
    <script type="text/javascript" src="{{ SITEURL }}/{{ THEME_STATIC_DIR }}/tipuesearch/tipuesearch_content.js"></script>
    <script type="text/javascript" src="{{ SITEURL }}/{{ THEME_STATIC_DIR }}/tipuesearch/tipuesearch_set.js"></script>
    <script type="text/javascript" src="{{ SITEURL }}/{{ THEME_STATIC_DIR }}/tipuesearch/tipuesearch.min.js"></script>
    {% endif %}
    <script>
    $(document).ready(function() {
      $('#tipue_search_input').tipuesearch({
        'mode' : 'json',
        'show': 10,
        'newWindow': false,
        'contentLocation': 'tipuesearch_content.json'
      });
    });
    </script>
{% endblock %}
````

I've  [checked with](https://github.com/Tipue/Tipue-Search/issues/36#) the tipuesearch developer, but they sent me here. Any idea what I'm doing wrong? I'm using tipue-search 5.0 with son mode.

**Comment by Scheirle** [comment]
You are using pandoc in `standalone` mode to read your content:
https://github.com/mclearc/colinmclear.net-pelican/blob/master/pelicanconf.py#L65

Therefore pandoc will generate a standalone html document:
```html5
<!DOCTYPE html>
<html>
<head>
    ...
    <style type="text/css">code{white-space: pre;}</style>
    ...
</head>
<body>...</body>
</html>
```
This document is now the base, pelican and all the plugins have to work with.
But pelian expects only the content of the body!

So everything is funky and tipue_search misbehaves.

But also your normal output is broken: Line 145: `view-source:http://colinmclear.net/2015/maintain-a-cv-in-html-and-pdf`

**Comment by mclearc** [comment]
Thanks! Removing the standalone option did the trick!
