### ISSUE TITLE
Caught exception "KeyError: 'src'". Reloading.

### ISSUE THREAD

**Issue by beauvais** [getpelican/pelican-plugins#716]
When I add the PLUGIN_PATHS entry to my pelicanconf.py file, I get a regenerate exception.

`Caught exception "KeyError: 'src'". Reloading.`

```
# Plugin stuff

PLUGIN_PATHS = ['plugins']
PLUGINS = ["representative_image"]
```

Here is my directory tree:

.```
├── content
├── output
├── plugins
│   ├── ace_editor
...
│   ├── representative_image
...
│   └── yuicompressor
└── themes

```

What am I doing wrong?
```

**Comment by justinmayer** [comment]
Where is your pelicanconf.py file in that hierarchy?

**Comment by beauvais** [comment]
It's in the root directory (same as content/, output/, ...)

![screen shot 2016-05-16 at 18 25 57](https://cloud.githubusercontent.com/assets/724619/15297749/b1c9f872-1b93-11e6-9f6c-33415ac2b8c8.png)

**Comment by beauvais** [comment]
Is this where it's supposed to be? I haven't moved it from the quickstart :)

**Comment by alysivji** [comment]
I'm getting the same error when trying to install representative_image.

Did this ever get sorted?

```console
$ pelican --verbose
CRITICAL: KeyError: 'src'
```

**Comment by justinmayer** [comment]
Not sure how to reproduce this. Please feel free to comment here if you feel the issue should be re-opened.
