### ISSUE TITLE
Error when using webassets with virtualenv wrapper

### ISSUE THREAD

**Issue by Scot3004** [getpelican/pelican-plugins#728]
Ubuntu 14.04 
pelican --version: 3.6.3
mkvirtualenv --python=`which python3`pelican
workon pelican
pip install pelican
pip install webassets
make html
CRITICAL: TemplateSyntaxError: Encountered unknown tag 'assets'.
make: *** [html] Error 1

**Comment by avaris** [comment]
Your settings?

**Comment by Scot3004** [comment]
https://gist.github.com/Scot3004/abbd74312802bfa27f905bcdbf39b221

**Comment by Scot3004** [comment]
already installed this theme, but... i making my own

**Comment by avaris** [comment]
You don't have plugins configured. You need the `assets` plugin.

**Comment by Scot3004** [comment]
sorry my miss, its rigth i forgotten to add plugins_path folder.
