### ISSUE TITLE
liquid_tags/notebook: NOTEBOOK_DIR is not defined

### ISSUE THREAD

**Issue by dorneanu** [getpelican/pelican-plugins#732]
Hi!

Usually you define in your `pelicanconf.py` where to find the (ipython) notebook by using`NOTEBOOK_DIR`. In the current version of `liquid_tags/notebook.py` you have:

``` .python
nb_dir =  preprocessor.configs.getConfig('NOTEBOOK_DIR')
nb_path = os.path.join('content', nb_dir, src)
```

However `NOTEBOOK_DIR` is not defined. I've checked that by printing out `nb_path` and `preprocessor.configs.getConfig('NOTEBOOK_DIR')`.

Any ideas? Thx in advance.

**Comment by justinmayer** [comment]
@dorneanu: Were you able to find a solution to your problem here?
