### ISSUE TITLE
filetime_from_{git,hg} docs refer to nonexistent variable "updated"

### ISSUE THREAD

**Issue by logological** [getpelican/pelican-plugins#740]
The documentation for the `filetime_from_git` and `filetime_from_hg` plugins refer to a nonexistent variable `updated`.  According to the source code this variable is actually named `modified`.

**Comment by justinmayer** [comment]
In the future, feel free to submit a pull request that includes the issue details, as opposed to submitting the issue first/separately.  (^_^)
