### ISSUE TITLE
pelican's asset plugin doesn't appear to work with webassets 0.12

### ISSUE THREAD

**Issue by erickt** [getpelican/pelican-plugins#777]
For [this week in rust](https://github.com/cmr/this-week-in-rust/tree/134956bb9c353f08494b0666f3554fb51acfbd3c), we're getting the following error with webassets 0.12:

```
CRITICAL: scss: subprocess returned a non-success result code: 65, stdout=, stderr=Error: File to import not found or unreadable: bootstrap-overrides.
       Load path: /Users/erickt/projects/rust/this-week-in-rust
        on line 44 of standard input
  Use --trace for backtrace.
```

However with 0.11.1, everything builds fine.

**Comment by avaris** [comment]
Possibly a bug introduced in webassets 0.12: miracle2k/webassets#466

**Comment by justinmayer** [comment]
@erickt: Were you able to find a solution to your problem here?

**Comment by kdeldycke** [comment]
FTR the `webassets` plugin has been migrated to https://github.com/pelican-plugins/webassets and its unit-tests seems to indicate everything is fine with the underlaying dependencies.

I guess this issue can be closed as outdated.

**Comment by justinmayer** [comment]
Agreed. Thanks, Kevin!
