### ISSUE TITLE
Error in render-math plugin

### ISSUE THREAD

**Issue by ClemensFMN** [getpelican/pelican-plugins#834]
I get an error when trying to use the render_math plugin. 

pelicanconf.py:

    PLUGIN_PATHS = ['pelican-plugins']
    PLUGINS = ['render_math']

start pelican via `make devserver` and get

    DEBUG: Pelican version: 3.7.0
    DEBUG: Python version: 3.5.2
    DEBUG: Adding current directory to system path
    DEBUG: Temporarily adding PLUGIN_PATHS to system path
    DEBUG: Loading plugin `render_math`
    DEBUG: Registering plugin `render_math`
    DEBUG: Restoring system path
    Traceback (most recent call last):
      File "/home/clnovak/Desktop/p/blog/pelican-plugins/render_math/math.py", line 272, in mathjax_for_markdown
        pelicanobj.settings['MD_EXTENSIONS'].append(PelicanMathJaxExtension(config))
    KeyError: 'MD_EXTENSIONS'

    Error - the pelican mathjax markdown extension failed to configure. MathJax is non-functional.

If I do not append the settings in line 272 of math.py but set them (i.e. `pelicanobj.settings['MD_EXTENSIONS'] = PelicanMathJaxExtension(config)`), I do not get an error, but math rendering does not work either.

**Comment by jerryasher** [comment]
I think this commit barrysteyn/pelican_plugin-render_math@c156b407bb8f9c62e2902f251d640a4c55aa0f58 as part of 
barrysteyn/pelican_plugin-render_math#39 will fix the issue.

As a github noob, I'm not sure what to do since the version of render_math in Barry's repo is ahead of the current one in the released pelican-plugins repo. Should I submit a pull request to fix it here and now, or wait for Barry to merge it and push it?

**Comment by Iv** [comment]
One more relevant fix:  https://github.com/getpelican/pelican-plugins/pull/858

**Comment by danmackinlay** [comment]
There are a few versions of the plugin around now;
AFAICT the one in this repo should be canonical and the other branches are works-in-progress. If you want to attract the attention of the maintainer @jerryasher I believe the method is to mention them in the support tickets.

**Comment by justinmayer** [comment]
Fixed via merged PR #973.
