### ISSUE TITLE
[Question] Is it possible import HTML/CSS/JavaScript site?

### ISSUE THREAD

**Issue by Kristinita** [getpelican/pelican-plugins#839]
### 1. Briefly

Is it possible import to Pelican site, written only in HTML, CSS and JavaScript?

### 2. Detail

I never use CMS or site generators, I write my static sites only in HTML, CSS and JavaScript. Now I want to use Pelican. What I must do, that quickly import my site to Pelican? My site — **<http://kristinita.ru>**, page example of my site — **<http://kristinita.ru/Sublime-Text/SashaSublime>**.

### 3. Did not help

I read documentation page [**Importing an existing site**](http://docs.getpelican.com/en/3.6.3/importer.html#examples), but in that page I see import information only about CMS.

Thanks.

**Comment by Kristinita** [comment]
Sorry, wrong repository.

**Comment by justinmayer** [comment]
With some minor modifications, you can use your existing HTML files as your source content (that is, in place of Markdown or reST files).

Docs > Writing Content > Metadata > paragraphs about using HTML files as content
