### ISSUE TITLE
Can't get Liquid_Tags to work with Pelican 3.7.1

### ISSUE THREAD

**Issue by Bridouz** [getpelican/pelican-plugins#842]
Hi,

I've recenty discovered the _Liquid_Tags_ plugin and want to use it for images rendering but it seems I'm not able to get it working.

I clone pelican-plugins repo and add Liquid_Tags as a plugin
`# Plugins
PLUGIN_PATHS = ['plugins']
PLUGINS = ['frontmark', 'pelican-toc', 'liquid_tags.img']`

And then in a markdown files I added : `{% img /images/solus/conkysolus20161215.png %}`

but it doesn't render the image and the html generated file render the liquid_tag as text.

Did I miss something ?

Thanks

**Comment by iGormilhit** [comment]
I'm learning how to use `pelican`, but according to [the pelican documentation](http://docs.getpelican.com/en/3.6.3/content.html#linking-to-static-files), shouldn't you write something like `{% img {filename}/images/solus/conkysolus20161215.png %}` ?

This way, it works for me, with `pelican` 3.7.1 and the `liquid_tags.audio` plugin.

**Comment by Bridouz** [comment]
Sorry for the delay,

I found that my issue came from the _pelican-frontmatter_ plugin. Disabling it made _liquidtags_ to work.
