### ISSUE TITLE
bootstrapify warning

### ISSUE THREAD

**Issue by lll9p** [getpelican/pelican-plugins#845]
Python 3.6+pelican 3.7.1

when I `make html` it shows warnings below:

```
\AppData\Local\Programs\Python\Python36\lib\site-packages\bs4\__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 193 of the file \AppData\Local\Programs\Python\Python36\lib\runpy.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "lxml")

  markup_type=markup_type))
```

and additional ``<html><body>`` shows before every ``<div class="section" id="id1">``

after I changed line25 in .\plugins\bootstrapify\bootstrapify.py to 
`    soup = BeautifulSoup(content._content, "html.parser")`

problem fixed.

**Comment by ingwinlu** [comment]
your plugin is outdated, update it

**Comment by justinmayer** [comment]
@lll9p: Please let us know if you need further assistance. Better yet, please find us on the [#pelican channel](http://docs.getpelican.com/en/stable/contribute.html#the-pelican-irc-channel). 😄
