### ISSUE TITLE
gzip_cache: Potential for a user-facing exclude option?

### ISSUE THREAD

**Issue by janw** [getpelican/pelican-plugins#852]
I recently started using the `gzip_cache` plugin on my site, and I am shipping some extra files through Pelican that do not benefit from compression really, and just clutter up the output folder. Mostly because they will not be used in the classic "serve a static HTML website" kind of way, but more as direct file downloads.

Therefore I contemplated extending the plugin to implement such a feature in compliance with other Pelican `pelicanconf.py` options à la `PAGE_EXCLUDES`, `ARTICLE_EXCLUDES`, and the like. I just wanted to check in before going about it, if there are other opinions about such a feature?

**Comment by justinmayer** [comment]
Hi @janwh. Is this something you would like to work on implementing?

**Comment by sagamusix** [comment]
I need this feature too. It could be done as simply as adding this to the `should_compress` function:
```python
    for extension in settings.get('GZIP_CACHE_EXCLUDE_TYPES', []):
        if filename.endswith(extension):
            return False
```

Should I submit a PR or can you add it yourself?
