### ISSUE TITLE
subcategory plugin with just folders for subcategories?

### ISSUE THREAD

**Issue by colmoneill** [getpelican/pelican-plugins#856]
Hi, I'm confused and can't work out if the subcategory plugin is meant to be used the way I intend it to be:

Can I enable the plugin, add `PATH_METADATA= '(?P<subcategory_path>.*)/.*'` to my settings, make folders as I desire subcategories, adjust the template and get the plugin to work as so, or does each article page need a metadata field in it's head that details the subcategory?

I can't seem to understand if it's meant to extend categories the way they exist in Pelican (but only one level deep) or if it needs extra metadata in the file's metadata keys?

@mfitzp Would you be able to help me out?

Thank you very much!

**Comment by mfitzp** [comment]
To answer this (so it can be closed) there are two options with the subcategory plugin:

1. Provide the subcategory information in the header of the article templates.
2. Add the `PATH_METADATA` variable and use folder-based subcategories.

You can use either 1 or 2, you don't need both.
