### ISSUE TITLE
NOTEBOOK: TypeError: write() argument 1 must be unicode, not str

### ISSUE THREAD

**Issue by pyaster** [getpelican/pelican-plugins#866]
The liquid plugins are set and loaded properly, but for a simple ipython notebook with a single line like this

http://localhost:8888/notebooks/example.ipynb

> Hello world

and an example.md file like this

> Hello
> {% notebook example.ipynb %}
> End

fails and the pelican console shows

> ERROR: Could not process example.md
>  | TypeError: write() argument 1 must be unicode, not str
> Done: Processed 12 articles, 0 drafts, 0 pages and 0 hidden pages in 1.79 seconds.

My platforms is:

Jupyter 4.3.0
Python 2.7.10
macOS Sierra 10.12.3

What I'm missing?

**Comment by pyaster** [comment]
Thats works for me:

in notebook.py replace 

> with open('_nb_header.html', 'w') as f:
>            f.write(header)
>        notebook.header_saved = True

by

> with open('_nb_header.html', 'w') as f:
>            f.write(unicode(header))
>        notebook.header_saved = True

**Comment by Florents-Tselai** [comment]
Yeap, this solved it for me as well. It looks like its a liquid_tags thing though. There should be an elif python version check there

**Comment by justinmayer** [comment]
@pyaster / @Florents-Tselai: Would you consider submitting a PR to address the issue discussed here?

**Comment by newptcai** [comment]
Also met this problem.

**Comment by justinmayer** [comment]
If someone can confirm this problem also affects Python 3, please comment here with appropriate steps to reproduce.
