### ISSUE TITLE
i18n_subsites seems to not working properly with MarkDown files

### ISSUE THREAD

**Issue by jadjay** [getpelican/pelican-plugins#869]
==>content/news_2017_libre-et-change-en.md <==
Title:       Reminder: FSM 2017 CFP
Category:    News
Slug:        libre-et-change
Date:        2017-03-07
Tags:        cfp
lang:        en
Summary:     Less than three weeks are left to submit a proposal!

Less than three weeks are left to submit your proposal!

* * *
==> content/news_2017_libre-et-change-fr.md <==
Title: Rappel: CFP et note d'intention
Category:    News
Slug:        libre-et-change
Date:        2017-03-03
Tags:        cfp
lang:        fr
Summary:     Il reste moins d'un mois pour soumettre une proposition!

Il vous reste moins d'un mois pour proposer vos interventions!

* * *

  pelican content/
> WARNING: There are 2 original (not translated) items with slug "libre-et-change": 
>  content/news_2017_libre-et-change-en.md
>  content/news_2017_libre-et-change-fr.md

By the way default lang is set to "fr" ...

**Comment by jadjay** [comment]
I copy the thought  I had on irc://irc.freenode.net:6667/#pelican 

I think pelican and i18n_subsites need a metadata tag like default_translation: true to define wich article has to be the "by default" translation

 For exemple : A website with fr,en,es,it
 default is en
 5 article available in the 4 languages
 but the 6th one is translated in fr and en

 you don't want to copy the fr article for es and it (es and are more able to read french than english)

If you could set default language for this article is fr, then this article is copied for each language without the {slug}-{lang}.html probleme

The workaround is to have one file without the lang: tag but then you can't have only 2 translations and a default for the others

Thanks for your answers :)

**Comment by justinmayer** [comment]
@jadjay: Were you able to find a solution to your problem here?

**Comment by jadjay** [comment]
Erf one year later i can't remember, i think i used the workaround

**Comment by justinmayer** [comment]
Glad it worked out. Cheers.
