### ISSUE TITLE
read_more_link: full URL permalink in READ_MORE_LINK_FORMAT

### ISSUE THREAD

**Issue by ahmetb** [getpelican/pelican-plugins#870]
READ_MORE_LINK = ' <span class="read-more"><nobr>Read more &rarr;</nobr></span>'
    READ_MORE_LINK_FORMAT = "<a href='{url}'>{text}</a>"

It looks like `{url}` is supported by read_more_link plugin according to its README. However I can't just make it work with `{{SITEURL}}` (which changes between local dev and prod -- due to pelicanconf vs publishconf).

Any ideas how to generate a full URL with `READ_MORE_LINK_FORMAT`?

**Comment by jorgesumle** [comment]
There is another plugin for read more links (https://github.com/getpelican/pelican-plugins/pull/813), but it has the same problem.

**Comment by jorgesumle** [comment]
I solved the issue for another_read_more_link: https://github.com/fangpeishi/another_read_more_link/pull/3

**Comment by justinmayer** [comment]
Glad y'all found a workaround.
