### ISSUE TITLE
[Bug] [Interlinks] Incorect details and summary tags conversion

### ISSUE THREAD

**Issue by Kristinita** [getpelican/pelican-plugins#885]
### 1. Summary

If I use [**Interlinks**](https://github.com/getpelican/pelican-plugins/tree/master/interlinks) plugin, [**`<details>` and `<summary>` tags**](http://www.hongkiat.com/blog/html5-details-summary-tags/) incorrect convert for me.

### 2. Settings

Part of my `pelicanconf.py` file:

```python
PLUGIN_PATHS = ['pelican-plugins']
PLUGINS = [
    'interlinks',
]

INTERLINKS = {
    'kristinita': 'http://kristinita.ru/#gsc.tab=0&gsc.q='
}
```

Part of my `Kristinita.md` file:

```html
<details><summary>Santa</summary>

Kristina</details>
```

### 3. Steps to reproduce

I build my site use any command, for example:

```shell
pelican content
```

### 4. Expected behavior

If Interlinks disable:

```html
<p><details><summary>Santa</summary></p>
<p>Kristina</details></p>
```

### 5. Actual behavior

If Interlinks enable:

```html
<p><details><summary>Santa</summary></details></p>
<p>Kristina</p>
```

### 6. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Python:**
3.6.1
**Pelican:**
3.7.1
**Python Markdown:**
2.6.8
**BeautifulSoup4**
4.5.3

Thanks.

**Comment by Kristinita** [comment]
@aquinzi , ping.

**Comment by aquinzi** [comment]
Thanks for reporting, let me take a look so I can solve it :)

**Comment by aquinzi** [comment]
Fixed it and have just sent a pull request.

**Comment by Kristinita** [comment]
Thanks, now I don't get this problem!

**Comment by andyli** [comment]
Do you think the "Expected behavior" is really correct? Aren't the tags incorrectly nested?
```
<p><details><summary>Santa</summary></p>
<p>Kristina</details></p>
```
