### ISSUE TITLE
[photos]: generate thumbnails of exact specified size?

### ISSUE THREAD

**Issue by gavinzbq** [getpelican/pelican-plugins#902]
Hello,

I am thinking about adding a feature to **photos** plugin so that thumbnails could be created with specified dimensions precisely (not catering aspect ratio). As a matter of aesthetics, gallery consisting of same-sized thumbnails may be more desired, like this [example](http://soultomount.press/2017May/light-landscape.html) I built.

By the way, I combined **photos** and **thumbnailer** to create the above webpage.

**Comment by NicolasLM** [comment]
Hey,
See #963 for an implementation of a very similar concept.

**Comment by justinmayer** [comment]
@gavinzbq: Feel free to build upon Nicholas's work and submit a pull request. Thanks!
