### ISSUE TITLE
[Interlinks] Last update to interlinks has broken <img> tags

### ISSUE THREAD

**Issue by mlabbe** [getpelican/pelican-plugins#920]
Unfortunately, the accepted PR request described here breaks <img> tags in the Interlinks plugin: https://github.com/getpelican/pelican-plugins/commit/e4c2f1691ae243474067c3844339d82c44657c56

The error appears to be on line 56, where `str(link)` refers to a variable that doesn't exist.  

To reproduce this:

 1. Install latest Pelican 3.7 and configure Interlinks plugin (below)
 2. Add the following to a markdown document in content: `![text](imgroot>some_img.jpg)`
 3. `make html` and observe that there is one execution error _per link_

# Interlinks Configuration #

Add the following to pelicanroot:

    INTERLINKS = {
       'imgroot': '/postimages/',
    }

**Comment by andyli** [comment]
#886 is indeed buggy, and I think it shouldn't be merged in the first place...

**Comment by aquinzi** [comment]
Sorry for the very long wait to fix this, been kind of busy; just made a pull request.

**Comment by justinmayer** [comment]
Thanks for the fix, @aquinzi.

@andyli / @mlabbe: Hopefully #925 will address the problems you reported. (^_^)
