### ISSUE TITLE
[feed_summary] should discuss Pelican 3.7's  RSS_FEED_SUMMARY_ONLY option

### ISSUE THREAD

**Issue by a3nm** [getpelican/pelican-plugins#926]
Pelican 3.7 has support for a new option, `RSS_FEED_SUMMARY_ONLY`, which makes it possible to only put an article summary in RSS feeds; see [release announcement](https://blog.getpelican.com/pelican-3.7-released.html). This seems to subsume some of the features of the feed_summary plugin. To avoid confusion, it would be nice if the documentation of the feed_summary plugin could be updated to discuss this.

**Comment by justinmayer** [comment]
Hi @a3nm. Would you like to submit a PR with the documentation enhancements you proposed?

**Comment by a3nm** [comment]
Sorry, I don't use the feed_summary plugin myself, so I can't commit the time to understand it well enough to do this. I was just pointing this out as it may interest the maintainer of the feed_summary plugin.

**Comment by justinmayer** [comment]
cc: @florianjacob

**Comment by florianjacob** [comment]
Judging from https://github.com/getpelican/pelican/releases/tag/3.7.0 , everything the feed_summary plugin has done is now the new default behaviour. (Yay!) It should not be used anymore and should be removed.

Just tried, just removing it results in:
```
ERROR: Cannot load plugin `feed_summary`
  | ModuleNotFoundError: No module named 'feed_summary'
```
for the user. Would be nice to note *somewhere* what happened, but probably doesn't justify to put too much effort in it. @justinmayer what to do about this? Is there a standard way to remove a plugin from the repo?

**Comment by justinmayer** [comment]
For now, I'm inclined to leave it in the repo but add a deprecation notice in the ReadMe file, which I will do shortly.

**Comment by a3nm** [comment]
Wonderful, this perfectly addresses the situation I had in mind (users
upgrade to Pelican 3.7, see that their RSS feeds are now summarized,
seacrh online, and think that the feed_summary plugin has something to
do with their problem). Thanks!
