### ISSUE TITLE
Sitemap: Make lastmod, changefreq, and priority optional

### ISSUE THREAD

**Issue by cwfoo** [getpelican/pelican-plugins#932]
There should be a way to make the sitemap not have lastmod, changefreq. and priority fields.
For example, a setting like this would be useful for some:

```
SITEMAP = {
    'format': 'xml',
    'lastmod': None,
    'priorities': {
        'articles': None,
        'indexes': 0.5,
        'pages': 0.5
    },
    'changefreqs': None,
}
```

**Comment by justinmayer** [comment]
@foochuanwei: Is this something you would like to work on implementing?
