### ISSUE TITLE
Separate repositories for each plugin

### ISSUE THREAD

**Issue by oulenz** [getpelican/pelican-plugins#934]
This is an open question to the dev team. Have you considered maintaining each plugin in a separate repository? The advantages I can think of are the following:

* Ability to clone plugins individually
* Easier to submit pull requests if the user has a local repository with only that plugin
* Possibly easier maintenance: more transparent who is responsible for which plugin, separate issues/pull requests

I'm mainly wondering whether you have previously considered this --- you may have excellent reasons for keeping all plugins together.

**Comment by justinmayer** [comment]
Already on the roadmap. Don't have the energy to track down the relevant issue(s). Not sure about timing, but we've talked about it and agree that's the best solution.

**Comment by avaris** [comment]
By the way, there are plugins with their own repositories and added here as submodules. It's up to the dev to make a choice.

**Comment by oulenz** [comment]
@avaris I know, but it would be much more consistent and practical if plugins were submodules regardless of who hosts them.

**Comment by justinmayer** [comment]
@oulenz: That has not been my experience. Submodules have been clunky, awkward, and messy. In any case, soon enough each plugin will have its own repository, which should provide the benefits you originally listed.

**Comment by oulenz** [comment]
@justinmayer Sorry, I meant that it would be consistent if they were all repositories. Whether or not they should also be submodules within a plugins repository (this repository) I have no opinion about.

**Comment by jorgesumle** [comment]
This monstrous repository sucks and should be replaced by a list of plugins (just a README written in Markdown, RST or whatever else). It should only point people to plugins ([plugin name](http://www.example.com)|description|issue tracker|...) which would be in separate repositories. This repository is maintained by people who are very busy and shouldn't be accepting or rejecting pull requests they mostly don't understand very well.
