### ISSUE TITLE
List subcategories on the category page.

### ISSUE THREAD

**Issue by NitishPuri** [getpelican/pelican-plugins#938]
I am using the subcategories plugin and it works fine, however i wanted to list the subcategories present in a category in the category page. Is there a way i can do that? 
I also wanted to show the category tree in the sidebar. But that would only be possible if i can list all the subcategories in a category.
Maybe I can make some modifications to the plugin to expose that information, or use some kind of metadata to the category.  It would be great help if someone can tell me how that can be done.

Thanks.

**Comment by voidplayer** [comment]
see #989

**Comment by justinmayer** [comment]
Closing this in favor of the issue opened by @voidplayer.
