### ISSUE TITLE
Bootstrap-rst repository invalid reference.

### ISSUE THREAD

**Issue by manugarri** [getpelican/pelican-plugins#941]
I see on the [pelican-plugin .config](https://github.com/getpelican/pelican-plugins/blob/76a8be9978bcfddc6dcf05678420fb06ee32cb0d/.gitmodules#L126) that the bootstrap-rst http link is referenced. However, that repo does not exist anymore.

Has it been moved?

**Comment by textbook** [comment]
I think they've taken it private, as my build fails with an authentication error:

```
Cloning into '/home/travis/build/textbook/textbook.github.io-source/pelican-plugins/bootstrap-rst'...
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/aqw/bootstrap-rst/'
fatal: clone of 'https://github.com/aqw/bootstrap-rst' into submodule path '/home/travis/build/textbook/textbook.github.io-source/pelican-plugins/bootstrap-rst' failed
Failed to clone 'bootstrap-rst' a second time, aborting
Failed to recurse into submodule path 'pelican-plugins'
```

**Comment by manugarri** [comment]
Excellent, will close.

**Comment by philshem** [comment]
Issue moved to https://github.com/getpelican/pelican-plugins/issues/1116
