### ISSUE TITLE
[liquid_tags] get pelican config settings in a custom tag?

### ISSUE THREAD

**Issue by epaulson** [getpelican/pelican-plugins#942]
I'm creating a new liquid tag, and I'd like to use some config options. However, it doesn't look like I can get ahold of the pelican config settings in a registered tag/sub-plugin. Instead, anything tag that wants a config setting needs to modify LT_CONFIG in mdx_liquid_tags.py - a workaround added in #321 to deal with #312 

Is there an easier way for an out-of-tree sub-plugin to add config items and get access to the current settings? I'm specifically looking for ways to add my own equivalent of GIPHY_API_KEY as well as getting the PATH variable from instance.settings so I can create a cache directory that my tag code can use. 

Thanks!

**Comment by epaulson** [comment]
PR #945 as one possible solution

**Comment by justinmayer** [comment]
Ostensibly addressed via linked PR.
