### ISSUE TITLE
filetime_from_git files always detected as not committed

### ISSUE THREAD

**Issue by aufarg** [getpelican/pelican-plugins#968]
It seems that the patch from #960 introduce a new bug for python 3 for me. Reverting the commit fix the bug.

Apparently, when looking for commits filtered by file path using the `log` method [here](https://github.com/getpelican/pelican-plugins/blob/master/filetime_from_git/git_wrapper.py#L75), it always result in empty lists if the path is encoded. As such, the plugin will always detect the file as not committed which results in 'date' and 'modified' always assigned to fs time.

I'm using python 3.6.3, pelican 3.7.1, and gitpython 2.1.7 on Linux.

**Comment by barometz** [comment]
Seeing the same behaviour with Python 3.5.3, Pelican 3.7.1, gitpython 2.1.8. Not sure what a fix for this would look like or I'd happily submit one.

**Comment by justinmayer** [comment]
@aufarg: Is this something you would like to work on implementing?
