### ISSUE TITLE
[Bug] [photos] Minimal example

### ISSUE THREAD

**Issue by Kristinita** [getpelican/pelican-plugins#981]
@pxquim, ping.

### 1. Summary

I can't begin to use photos plugin. I get traceback in console:

```python
Process SpawnPoolWorker-3:
Traceback (most recent call last):
  File "c:\python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "c:\python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python36\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "c:\python36\lib\multiprocessing\queues.py", line 337, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'photos'
```

#### 2.1. Environment

+ Windows 10 Enterprise LTSB 64-bit EN,
+ Python 3.6.4,
+ Pelican 3.7.1,
+ python-markdown 2.6.11,
+ pillow 5.0.0,
+ piexif 1.0.13.

#### 2.2. Files

I have `Hairs.jpg` and `Cat.jpg` files in `pictures/kris` folder.

Part of my `pelicanconf.py`:

```python
PLUGIN_PATHS = ['pelican-plugins']
PLUGINS = [
    'photos'
]

PHOTO_ARTICLE = (760, 506, 80)

PHOTO_GALLERY = (1024, 768, 80)

PHOTO_LIBRARY = "pictures"

PHOTO_RESIZE_JOBS = 5

PHOTO_THUMB = (192, 144, 60)
```

Part of my article `SashaTest.md`:

```markdown
image: {photo}kris/Hairs.jpg

Here are my best photos, taken with my favorite camera:

![Hairs]({photo}kris/Hairs.jpg)
![Cat]({photo}kris/Cat.jpg)
```

Part of my `article.html`:

```jinja
{% block base_gallery -%}
{% if article.photo_image %}<a href="{{ SITEURL }}/{{ article.url }}"><img class="post-thumb" src="{{ SITEURL }}/{{ article.photo_image[2] }}" /></a>
{% endif %}
{%- endblock %}
```

Part of my `base.html`:

```jinja
{% block base_gallery -%}{%- endblock %}
```

### 3. Steps to reproduce

I run in console:

    pelican content -s pelicanconf.py

### 4. Expected behavior

Successful `photos` plugin usage.

### 5. Actual behavior

I get traceback:

```python
D:\SashaPelicanTest>pelican content -s pelicanconf.py
Process SpawnPoolWorker-4:
Process SpawnPoolWorker-3:
Traceback (most recent call last):
  File "c:\python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "c:\python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python36\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "c:\python36\lib\multiprocessing\queues.py", line 337, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'photos'
Traceback (most recent call last):
  File "c:\python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "c:\python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python36\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "c:\python36\lib\multiprocessing\queues.py", line 337, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'photos'
Process SpawnPoolWorker-1:
Traceback (most recent call last):
  File "c:\python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "c:\python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python36\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "c:\python36\lib\multiprocessing\queues.py", line 337, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'photos'
```

Thanks.

**Comment by pxquim** [comment]
Greetings @Kristinita!

I was just checking, and `git blame` reports that only 14% of the lines in `photos.py` are actually mine. Of course, this is open source at its best, but it also means that many recent changes to the plugin are quite alien to me.

You probably want to contact Brian Levin about this issue, because he seems to have added multiprocessing.

To help troubleshooting, I would try the setting `PHOTO_RESIZE_JOBS=1`, which seems to disable multiprocessing.

**Comment by Kristinita** [comment]
@bnice5000, ping.

@pxquim , unfortunately, if `PHOTO_RESIZE_JOBS=1`, I get same traceback.

Does it work `photos` plugin for you personally, for your environment?

Thanks.

**Comment by bnice5000** [comment]
@Kristinita and @pxquim I did not add parallel processing. It was added by @fufler in PR #756.

**Comment by pxquim** [comment]
@Kristinita The plugin Photos works in my environment because I am using a very old version...

**Comment by Kristinita** [comment]
@pxquim , thanks, if `PHOTO_RESIZE_JOBS = -1`, I haven't critical error! Please, add information to README of plugin. I close this issue.

But, possible, I found another bugs. Do you plain support plugin? What [**status**](http://www.repostatus.org/) of project?

Thanks.

**Comment by pxquim** [comment]
@Kristinita , the status is "my last version works for me". I am quite amazed that some people have taken the time to improve my initial code. However, I don't quite have the time at this point to troubleshoot and fix issues.

In retrospect, I am quite pleased to have contributed the project to `pelican-plugins` directly, and not to a separate subproject.

- If I had kept the code as my own, I would probably have rejected some of the improvements, and raise the anger of these willing contributors.
- As it is, the code has grown beyond my immediate needs, to the benefit of everyone. It's open source at its best.

**Comment by flothesof** [comment]
Hi everyone,

just to let you know that I ran into exactly the same problem (python 3.5, Win10, pelican 3.7.1).
I worked around it using the PHOTO_RESIZE_JOBS = -1 option.
May I suggest adding this issue under a "known issues" list as well as the workaround to the documentation?
Also, since people run into the risk of seeing this error due to multiprocessing, shouldn't it be disabled by default in the introduction guide and only offered as an option? The rationale would be that something slow that works rather than something fast that doesn't work sometimes is a better choice here.

Should I try and propose a modified README? @pxquim @bnice5000 

Best regards,
Florian

**Comment by bnice5000** [comment]
@flothesof please propose an changes you like. The magic of open source is that if the powers that be like it, it will be approved. To be clear, I am not one of those powers.

As a side note, I don't use this plugin anymore. I created one that met my specific purpose. I may eventually share it but it is not ready for prime time. I am also not sure there is a lot of interest in my plugins, so I haven't been in a rush to clean it up.
