### ISSUE TITLE
[photos] error in photos.py when problem making directories *intermittent*

### ISSUE THREAD

**Issue by verbal007** [getpelican/pelican-plugins#982]
When I run pelican to build my site, I often see this error. The solution/workaround I use is simply re-running pelican and it seems to fix itself... sometimes. Sometimes it'll produce a similar error again, sometimes it will run clean through. Haven't been able to notice a consistent pattern.

```
ERROR: Could not create /projpath/output/photos/2017/0810
  |___
  | Traceback (most recent call last):
  |   File "/projpath/plugins/photos/photos.py", line 279, in resize_worker
  |     os.makedirs(directory)
  |   File "/home/username/env/pelican/lib/python3.6/os.py", line 220, in makedirs
  |     mkdir(name, mode)
  | FileExistsError: [Errno 17] File exists: '/projpath/output/photos/2017/0810'
Done: Processed 9 articles, 1 draft, 3 pages and 0 hidden pages in 2.46 seconds.
```
Running on Manjaro/Arch Linux.

**Comment by pxquim** [comment]
Greetings. You found a race condition introduced by the parallel resizing of photos.
It should go away if you set  `PHOTO_RESIZE_JOBS=-1`, which disables the parallelism.

**Comment by verbal007** [comment]
Thanks @pxquim .  It's obviously slower now, but I prefer the stability over the speed.  Cheers!
