### ISSUE TITLE
sbdy willing to help me set up share_post ?

### ISSUE THREAD

**Issue by arnauldb** [getpelican/pelican-plugins#993]
Hello,

I'm new to Pelican. I installed the share_post plugin, added it in my pelicanconf.py, but now, what is next ? How to add it to articles and pages ?

Thank you.

**Comment by justinmayer** [comment]
Please consider reaching out via the Pelican IRC channel, as noted in the [How to Get Help](http://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the documentation. Thanks!
