### ISSUE TITLE
[photos] dont make a warning because optional files dont exist

### ISSUE THREAD

**Issue by voidplayer** [getpelican/pelican-plugins#997]
```
WARNING: photos: No EXIF for gallery at file content/auto/photos/banner/exif.txt
WARNING: photos: No captions for gallery at file content/auto/photos/banner/captions.txt
WARNING: photos: No blacklist for gallery at file content/auto/photos/banner/blacklist.txt
```

I have ~1k articles. All of them with photos

~1k * 3 warnings = ~3k WARNINGs every time i rebuild the blog because i dont use these optional files. Please consider downgrading the importance to NOTICE instead of WARNING

**Comment by justinmayer** [comment]
See also: http://docs.getpelican.com/en/stable/settings.html#logging

That said, I agree that perhaps these could be NOTICE level instead of WARNING. Is that something you'd be willing to submit a PR for, @voidplayer?
